### ISSUE TITLE
Single block tanks accept non-fluid containers

### ISSUE THREAD

**Issue by xarses** [draknyte1/GTplusplus#101]
And conveyors will accept  non-fluid items like dusts and other random crap. On top of this, a conveyor can't pull items from the input slot so it just stays there. 

I'm not sure anything can be done since this is the same behavior as fluid-hatches directly in GT5u

**Comment by draknyte1** [comment]
Inherit behaviour from GT fluid tank logic.
It doesn't actually cause any issues though.

**Comment by xarses** [comment]
It does cause issues, since they just accept random crap from pipes causing them to need a item filter, which also requires power
