### ISSUE TITLE
Broken Oredict Registration

### ISSUE THREAD

**Issue by MineWitherMC** [draknyte1/GTplusplus#102]
Frameboxes and blocks have oredict registration before blocks themselves (according to GT). Example:
``` A broken ore dictionary registration with name frameGtSelenium has occurred. It adds an item (type: class gtPlusPlus.core.item.base.itemblock.ItemBlockGtFrameBox) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod GT++ report it to them! ```
GT++ 1.5.0.1-Beta

**Comment by draknyte1** [comment]
Don't care. Forge is a bitch.
