### ISSUE TITLE
MultiSizeTools

### ISSUE THREAD

**Issue by Rbhbkkacer** [draknyte1/GTplusplus#103]
MultiSizeTools not working with stone from underground biomes. They dig up only one block instead of 9.

**Comment by draknyte1** [comment]
What is the name of the stone?
Like, the item name preferably.

<UndergroundBiomes:stone> or something I guess.
Hold the stone and type /mt hand then let me know.

**Comment by Rbhbkkacer** [comment]
UndergroundBiomes:igneousStone:[0..7]
UndergroundBiomes:igneousCobblestone:[0..7]
UndergroundBiomes:igneousStoneBrick:[0..7]
UndergroundBiomes:metamorphicStone:[0..7]
UndergroundBiomes:metamorphicCobblestone:[0..7]
UndergroundBiomes:metamorphicStoneBrick:[0..7]
UndergroundBiomes:sedimentaryStone:[0..7]
UndergroundBiomes:igneousStoneBrickHalfSlab:[0..7]
UndergroundBiomes:igneousStoneBrickFullSlab:[0..7]
UndergroundBiomes:metamorphicStoneBrickHalfSlab:[0..7]
UndergroundBiomes:metamorphicStoneBrickFullSlab:[0..7]
UndergroundBiomes:igneousStoneHalfSlab:[0..7]
UndergroundBiomes:igneousStoneFullSlab:[0..7]
UndergroundBiomes:metamorphicStoneHalfSlab:[0..7]
UndergroundBiomes:metamorphicStoneFullSlab:[0..7]
UndergroundBiomes:igneousCobblestoneHalfSlab:[0..7]
UndergroundBiomes:igneousCobblestoneFullSlab:[0..7]
UndergroundBiomes:metamorphicCobblestoneHalfSlab:[0..7]
UndergroundBiomes:metamorphicCobblestoneFullSlab:[0..7]
UndergroundBiomes:sedimentaryStoneHalfSlab:[0..7]
UndergroundBiomes:sedimentaryStoneFullSlab:[0..7]
UndergroundBiomes:stairs:[0..55]
UndergroundBiomes:wall:[0..55]
UndergroundBiomes:sedimentary_monsterStoneEgg:[0..7]
UndergroundBiomes:metamorphic_monsterStoneEgg:[0..7]

**Comment by Rbhbkkacer** [comment]
ore dictionary:
<ore:stone>
<ore:stoneBricks>
<ore:cobblestone>
for these blocks:
UndergroundBiomes:igneousStone:[0..7]
UndergroundBiomes:igneousCobblestone:[0..7]
UndergroundBiomes:igneousStoneBrick:[0..7]
UndergroundBiomes:metamorphicStone:[0..7]
UndergroundBiomes:metamorphicCobblestone:[0..7]
UndergroundBiomes:metamorphicStoneBrick:[0..7]
UndergroundBiomes:sedimentaryStone:[0..7]

**Comment by Rongmario** [comment]
Recoding of tools are being doing.

**Comment by draknyte1** [comment]
Yeah I was hoping your recode would fix this sorta thing. :)

**Comment by DimaKuzmin** [comment]
in file UtilsMining function getBlockTipe add code:

                if (block instanceof BlockStone) {
			return true;
		}

**Comment by draknyte1** [comment]
They're pending a complete rewrite by @rongmario. He's just on holidays. 

Why I have touched them in a while to fix them.

**Comment by draknyte1** [comment]
Multitools were removed in https://github.com/draknyte1/GTplusplus/commit/ac8b633866da6d7bcc085d23f74b5873e4fa4c27. Closing as issue no longer relevant.
