### ISSUE TITLE
Some GT++ alloy ingots take too long to make

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#105]
Most of the GT++ blast smelter alloys take much longer to solidify than they do to smelt which seems backwards. The relationship between the times does not seem consistent either:

  Staballoy, 74.5 secs/144mB to smelt, 745 secs/ingot to solidify
  Inconel-690 ingot, 45secs/144mB to smelt, 85 secs/ingot to solidify  
  Maraging Steel 300, 3.5 secs/144mB to smelt, 84 secs/ingot to solidify
  Tantalloy-60, 19.8 secs/144mB to smelt, 495 secs/ingot to solidify
  Tantalloy-61, 45 secs/144mB to smelt, 495 secs/ingot to solidify

It is worth noting that the ingot solidification time seems to be the same as the smelting time, but the time per 144mB smelted changes because the output volumes are different. I understand you've used the overall atomic weight to calculate times, hence why staballoy is so high for instance. If you are following that logic you should be multiplying the time by the output volume of the blast smelter probably too - which will make matters even worse of course. Regardless, I suggest you do do that - maraging steel is way too fast for instance, and that which also mean the blast alloy smelter's times are proportional to the solidification times.

In addition, the smelting times of heavy alloys like Staballoy are too onerous (see bottom of text). First, their times do not appear to scale linearly in the normal GT fashion. For alloys in the Cr-Ni range (ie. iron/steel-ish, around 55) the numbers come out okay, similar to  stainless steel (av. atomic weight ~56.6 takes 85 secs/ingot to smelt in EBF - similar to the GT++ steel-like alloys), but for something like Staballoy (average atomic mass 219) your numbers are disproportionately higher. With a linear approach it would take 417 secs per 144 mB to smelt, not 745 secs.

That is still too long IMHO, especially given how Staballoy is an entry-level alloy. If you don't wish to diverge from the  GT approach I suggest you change the ratio of Uranium to Titanium in Staballoy (a separate issue perhaps).

Further, the time to solidify plates and blocks is much less, for instance with Staballoy it is 1 sec for a plate (144mB), 14 secs for a block (1296mB) and a fraction of a second for a nugget vs 745 secs for an ingot. I suggest you change it so that the time to solidify is either directly proportional to the liquid volume or to the volume:surface area ratio (a more realistic approach, though then you'd need to make plates faster, in theory). Given the GT norm is 1 sec/ingot and 14 secs/block that suggests the latter. In addition, the GT++ alloy fluids just take too long to solidify (thinking of ingots here). A GT steel or stainless steel ingot takes 1 sec to solidify, and they both have comparable overall densities (atomic weight averages) to maraging steels. Why the latter should take 80x longer to solidify I don't understand. I strongly encourage you to significantly reduce the solidification times by at least a factor of 10. Or just make them all the same as GT liquid metals (1 sec/ingot).

Finally, for those listed above (you might note those are the pipe ones - there is no easy way to find GT++ alloy ingots in NEI other than by searching "Alkalus" and that's what comes up) there are no nugget to ingot recipes. This would at least allow a work-around but does not address the core issue.

PS. It also takes 1,750 secs to smelt staballoy in a normal HV EBF, which means to produce the 160 ingots required for 16 blast smelter heat containment coils to get on the GT++ ladder takes 77.8 hours of smelting. This seems a little onerous.

**Comment by draknyte1** [comment]
![2017-07-05_17 48 45](https://user-images.githubusercontent.com/3060479/27854478-48eabe14-61aa-11e7-8d45-8be301a18296.png)
![2017-07-05_17 48 57](https://user-images.githubusercontent.com/3060479/27854477-48aa61b6-61aa-11e7-9c8c-1f3e1a086db6.png)
![2017-07-05_17 49 01](https://user-images.githubusercontent.com/3060479/27854480-492887bc-61aa-11e7-9e7d-06490b1d9804.png)
![2017-07-05_17 49 04](https://user-images.githubusercontent.com/3060479/27854481-495e0414-61aa-11e7-9c51-d4820799d9c0.png)
![2017-07-05_17 49 11](https://user-images.githubusercontent.com/3060479/27854476-4889b70e-61aa-11e7-884b-67dcde4dd562.png)

This may be residual from using an older version, but I think it's something I already fixed for solidification.

**Comment by katecw** [comment]
A couple of edits:

1) Dropped a nought off the time to make enough Staballoy for the blast smelter calc. It's 78 hours not 7.8.
2) I was using atomic weight not mass (ie. not counting the neutrons as you pointed out). Im still coming out with lower numbers for staballoy though.

**Comment by katecw** [comment]
Cant see what alloys you're showing in those images, but as I said above the plate solidification times are not an issue. It is the ingot times that are too long - the same as the blast smelter times (which are to produce multiple ingots worth usually).

**Comment by draknyte1** [comment]
```
//Ingot
			if (GT_Values.RA.addFluidSolidifierRecipe(
					ItemList.Shape_Mold_Ingot.get(0), //Item Shape
					material.getFluid(144), //Fluid Input
					material.getIngot(1), //output
					32, //Duration
					8 //Eu Tick
					)){
				Utils.LOG_WARNING("144l fluid molder for 1 ingot Recipe: "+material.getLocalizedName()+" - Success");
			}
			else {
				Utils.LOG_WARNING("144l fluid molder for 1 ingot Recipe: "+material.getLocalizedName()+" - Failed");
			}
```

Not sure where this breaks..

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/cc3f4015208e1fa4e75972f8f2c8aa5677733666.
