### ISSUE TITLE
Add "Alkalus" to all GT++ stuff

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#106]
There is currently no way to see just GT++ items in NEI since it's search ignores non alphanumeric characters. I therefore suggest that you add "Added by: Alkalus - [GT++]" to every GT++ item. Currently only some of them have it.

**Comment by draknyte1** [comment]
Use '@mod.gt++' in NEI.

**Comment by draknyte1** [comment]
The 'Added by: Alkalus - [GT++]' is on everything from GT++ that isn't registered under the GT++ Mod ID. For example, Machines I add all fall under Gregtech and I cannot change that, so they get this tooltip to show users/players where they are from.
