### ISSUE TITLE
Nuclear Power

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#11]
So, I want other peoples thoughts on how to implement nuclear reactors.

I wish to use molten salts but otherwise it's open as to how people would like it implemented.
Varying outputs in terms of power and isotopes (Breeder reactors will be a thing too.)

@leagris @bear989 @muramasa- @dream-master

Remaining:
> Add recipes for each casing and the Controller.
> Improve build design, add another layer or two.

**Comment by MaDmaxwell311** [comment]
I would reccomend molten salt reactors as another type. Additionaly, it would be nice to se, assuming your reactors are multiblocks, that each type of reactor, uranium, thorium, plutonium, salt, would have to be built differently.

**Comment by MaDmaxwell311** [comment]
Ugh sorry for spam, hit the enter key for a new line and comment was posted. What I was going to say was, you should have as a return item, nuclear waste that can be centrifuged to get different elements.  Much in the same way as reactorcraft does this. Anyways,  I will think about it more tommorow.

**Comment by draknyte1** [comment]
Any and all suggestions are welcome.

Molten salt is already something I am considering, easily achievable through solar towers.

**Comment by Muramasa-** [comment]
I have always wanted a GT Nuclear Reactor of some sort. Maybe Naquadah can be included too.

My wishes would be to also allow the reactor to heat coolant (Which could be pretty easy with an optional Input Hatch) to use with the Large Heat Exchanger and also, when it's done, PR with the head fork please!

**Comment by draknyte1** [comment]
Being a GT Multiblock, it's not realistically that hard to make..

The biggest pain will probably be the recipe handler, to be honest,

**Comment by draknyte1** [comment]
Considering this is it's own type of Reactor, I'll probably do a quick implementation of it this afternoon.
https://en.wikipedia.org/wiki/Liquid_fluoride_thorium_reactor

Thorium is always overlooked as a viable option, but no longer :D

**Comment by MaDmaxwell311** [comment]
Okay, one thing I would recommend would be reading up on this page, https://en.wikipedia.org/wiki/Nuclear_reactor . The one thing that would make your reactors different and far better than any other reactor at present would be make them realistic, and by that I mean make it more than just a plop down and forget reactor. Make them require monitoring and have the possibility of a meltdown, have certain blocks that when in use are radioactive and must be sealed in a room, should you go in the room you only have a minute to live regardless of the amour you are wearing due to the extreme radiation. Yes I know this would be a lot of work, but ti would make your mod stand out and it would be unique. As always, I will be thinking of more things for you.

**Comment by Muramasa-** [comment]
Thinking about Naquadah some more:
It could possibly be the best "fuel" for the reactor, but of course requires fusion for a steady supply. Maybe along with the option of creating plasma from fusion, you could manufacture Naquadah and use that in a Fluid Nuclear Reactor for extremely efficient power.

**Comment by draknyte1** [comment]
```
            generateIC2FluidCell("HydrofluoricAcid");
			generateIC2FluidCell("SulfurDioxide");
			generateIC2FluidCell("SulfurousAcid");
			generateIC2FluidCell("SulfuricApatite");
			generateIC2FluidCell("UraniumHexaFluoride");
			generateIC2FluidCell("UraniumTetraFluoride");
			generateIC2FluidCell("ThoriumTetraFluoride");
```

Slowly adding the components to create Molten Salt Fuels, as well as the materials for Pebble bed reactors. Trying to keep everything as realistic as possible, Nq is definitely a viable option for very high tier reactors.. just wonder if using it directly as fuel or making it into a salt fuel is better :D

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/73f56f9ee834b6dfffcbd786429899e6910482cc - Did some more work on FLiBe fuels.

**Comment by draknyte1** [comment]
![2016-11-07_00 15 29](https://cloud.githubusercontent.com/assets/3060479/20039010/ebc8919a-a488-11e6-94f1-a06c2258ceca.png)
![2016-11-07_01 23 04](https://cloud.githubusercontent.com/assets/3060479/20039012/ee2064d6-a488-11e6-89a0-9d8f16389da4.png)
![2016-11-07_01 23 10](https://cloud.githubusercontent.com/assets/3060479/20039013/ee207d18-a488-11e6-8a9b-ef65bff24217.png)
![2016-11-07_01 23 14](https://cloud.githubusercontent.com/assets/3060479/20039014/ee76883e-a488-11e6-9e96-8c36ee7bf7ed.png)
![2016-11-07_01 23 21](https://cloud.githubusercontent.com/assets/3060479/20039015/ee78c806-a488-11e6-9d58-c10ccead9214.png)

**Comment by Armagedon13** [comment]
http://ieer.org/resource/classroom/types-of-nuclear-reactors/ the breader reactor sound good

**Comment by draknyte1** [comment]
Fast Breeders will be next. 
LFTR type is already complete.

**Comment by Armagedon13** [comment]
You can change the fusion reactor? To make it more difficult, have a multiblock and generate more energy?

**Comment by draknyte1** [comment]
I could add more tiers for Fusion, if it's not difficult enough. Please explain your idea in a bit of detail and I'll see what I can do. :)

**Comment by draknyte1** [comment]
![2016-12-27_21 38 27](https://cloud.githubusercontent.com/assets/3060479/21576809/ffbde214-cf89-11e6-9925-13e73ef8195a.png)
![2016-12-27_21 38 33](https://cloud.githubusercontent.com/assets/3060479/21576807/ffbb1e1c-cf89-11e6-98d5-277f30428210.png)
![2016-12-27_21 38 35](https://cloud.githubusercontent.com/assets/3060479/21576804/ffb9d138-cf89-11e6-90d4-466954e4c8e9.png)
![2016-12-31_18 27 02](https://cloud.githubusercontent.com/assets/3060479/21576808/ffbcc37a-cf89-11e6-9f4f-6dd76debde8e.png)
![2016-12-31_18 27 04](https://cloud.githubusercontent.com/assets/3060479/21576806/ffbb02b0-cf89-11e6-9bda-cdc2d3998b3f.png)
![2016-12-31_18 27 05](https://cloud.githubusercontent.com/assets/3060479/21576805/ffba42d0-cf89-11e6-82ce-c64853a85b4b.png)

**Comment by draknyte1** [comment]
finished in https://github.com/draknyte1/GTplusplus/commit/a35fbfbbeacbfb131b56e11bfa9d04740dd01d4e
