### ISSUE TITLE
Crashed trying to shift-click stuff into the bronze workbench

### ISSUE THREAD

**Issue by WarlordWossman** [draknyte1/GTplusplus#110]
Just gut the bronze workbench and tried to shiftclick a stack of oak logs in and the game crashed.
[crash-2017-07-12_03.11.19-client.txt](https://github.com/draknyte1/GTplusplus/files/1140622/crash-2017-07-12_03.11.19-client.txt)

**Comment by draknyte1** [comment]
Mod version?

**Comment by WarlordWossman** [comment]
Sorry thought it would be in the log. GT Plus Plus 1.5.6a

**Comment by bear989** [comment]
dont forget to disable the recipe for it, it has other bugs

**Comment by draknyte1** [comment]
It probably was... but I'm not sure how you've got this issue unless you've built the mod yourself from source or if you're playing New Horizons.

**Comment by WarlordWossman** [comment]
Yeah was in GT:NH but the last version is experimental anyways. I will try to reproduce it once we get a more stable version and tell you if it still exists.

**Comment by draknyte1** [comment]
GTNH literally builds my source code into versions, so between my pre-releases any issues arising is usually due to me Doing half jobs on stuff before coming back to finish it. (Due to work/sleep/etc)

This issue should be fixed in the next pre-release.
