### ISSUE TITLE
"Updating Screen Events" crash on v1.5.6-Pre-Release

### ISSUE THREAD

**Issue by Namikon** [draknyte1/GTplusplus#111]
We've traced down the weird "ScreenEvents" crash to GT++.
This crash happens with GT++ Version *GT-PlusPlus-1.5.6-Pre-release*, but not with *GT-PlusPlus-1.5.0-Beta*.

Related Stacktrace: https://pastebin.com/SL1sC1ak
Related issue: GTNewHorizons/NewHorizons#1651

**Comment by draknyte1** [comment]
I do like how you guys run into issues that I've never encountered.
Since adding the code causing this issue, I've looked up several hundred recipes without a crash in both SSP and SMP testing.

Easy fix though.

**Comment by draknyte1** [comment]
Probably in 16hr~ when I'm finished work and have driven home for the weekend. Let me see what I can do while at work.

**Comment by MixSt** [comment]
I can confirm, that your repo can not be compiled from the box . Many errors taken while compile. Could you create and put compiled version somewhere?

**Comment by draknyte1** [comment]
Repo is only missing GT & IC2, so that you grab the latest. Otherwise it builds fine. 

I don't have access to my laptop or desktop until Monday. So can't compile anything sorry.
