### ISSUE TITLE
Bypass Alloy smelting

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#114]
It is currently possible to bypass smelting most GT++ Alloys in the Electric Blast Furnace by using a Fluid Extractor-Solidifier setup. I'm assuming this is un-intended.

![untitled1](https://user-images.githubusercontent.com/30293976/28372251-e9f0308e-6ca7-11e7-8e9a-5406257ca668.png)
![untitled](https://user-images.githubusercontent.com/30293976/28372252-e9f65112-6ca7-11e7-8a5d-c9f270132214.png)

Using the latest GT++ version compiled from GitHub (7/18/2017)

**Comment by Rongmario** [comment]
Should disable Fluid Extractor recipes, that should patch it.

**Comment by draknyte1** [comment]
Currently it's added for every item based on material. Should be an easy fix.
