### ISSUE TITLE
"Errors - Tell Alkalus" Ingot

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#115]
Disabling Custom Fluid Pipes in the cfg makes the Simple Washer uncraftable. The Clay Pipe in the recipe is replaced with an Error Ingot.

![alkingot](https://user-images.githubusercontent.com/30293976/28437000-ad0686a0-6da1-11e7-90cc-4b46d3569f5b.png)

**Comment by Rongmario** [comment]
To-do: Implement better flexibility and checks. I'll submit a pull req.

**Comment by draknyte1** [comment]
This is why the error I got exists. So that things like this get flagged. If you just wanna check the config during washer loading and use copper alternatively, were sweet.

**Comment by Rongmario** [comment]
Sure thing b0ss

**Comment by draknyte1** [comment]
@Rongmario Where are we with this?
I will fix it today if you haven't gotten around to it yet.
