### ISSUE TITLE
Alloy Blast Smelter bug

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#116]
Putting a single Configuration 1 circuit into the Blast Smelter produces either Molten Terrasteel (if EnderIO compat. is enabled) or Molten Pulsating Iron (compat. is disabled).

![untitled](https://user-images.githubusercontent.com/30293976/28460015-c18eed7a-6e18-11e7-8065-a9506296cd96.png)
![untitled1](https://user-images.githubusercontent.com/30293976/28460016-c190d8d8-6e18-11e7-848e-64051b3866b8.png)

Using the latest GT++ version compiled from GitHub.

**Comment by Rongmario** [comment]
What GT version are you using?

**Comment by npawk12** [comment]
Using the latest GT version compiled from Github (July 22nd)

**Comment by draknyte1** [comment]
I don't see how the enderio config changes the output.

**Comment by npawk12** [comment]
Enabling debug mode in the config and looking at the logs, it seems the Phased Iron recipe loads before the Terrasteel recipe. I'm guessing disabling the compat makes the Phased Iron recipe error first and skips the rest of the errored recipes. 

Sidenote: Every recipe from Botania (Terrasteel, Manasteel, Elementium) seems to error.
