### ISSUE TITLE
Optifine Rendering Bug

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#117]
Using Optifine and GT++ together makes GT++ Casings render weird while looking at them from certain directions.
Normal GT casings or blocks do not suffer from this. 

![untitled](https://user-images.githubusercontent.com/30293976/28460323-31c65c8a-6e1a-11e7-87e7-e9750b09495e.png)

Using Optifine HD U D8 and the latest GT++ compiled from GitHub.

**Comment by draknyte1** [comment]
Not something I can fix.

**Comment by draknyte1** [comment]
This is caused by Casings allowing transparency.
It's one of those things that I am half minded about fixing because I'd like them to retain it and the issue is from Optifine at the end of the day..

**Comment by Rongmario** [comment]
This is caused by Optifine's D8 shader addition + improvements on the dynamic lightning, glad its an easy fix.

**Comment by draknyte1** [comment]
I just disabled transparency. :(
