### ISSUE TITLE
Forestry Compatibility Issues 

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#119]
With GT++ installed the Alveary Block names seem to mess up. The Swarmer is named as Alveary Frame Housing, the Alveary Fan is renamed to Alveary Mutatron and the rest of the Alveary blocks have names like Alveary 1, Alveary 2 etc. Disabling the compatibility in the config doesn't fix it.

Using Forestry 4.2.16.64 (last ver for 1.7), GT++ compiled from Github on 7/28 and Gendustry 1.6.4.135.

![alkpls](https://user-images.githubusercontent.com/30293976/28719512-d6c2af66-73b2-11e7-9b4a-af574fe2adf4.png)
![untitled](https://user-images.githubusercontent.com/30293976/28719515-d85f7fac-73b2-11e7-8726-261f5dda2a07.png)
![untitled1](https://user-images.githubusercontent.com/30293976/28719521-dabe9d64-73b2-11e7-9aa8-eb3145e4af14.png)

**Comment by draknyte1** [comment]
Are custom alveary frames enabled?

**Comment by npawk12** [comment]
If you mean Custom Alveary Blocks then yes.

**Comment by draknyte1** [comment]
Yeah the custom ones are broken and I should probably look into fixing them. Couldn't figure out how to add custom ones properly last time.

**Comment by Dream-Master** [comment]
I got the same issue in GTNH.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1724

**Comment by draknyte1** [comment]
It's not a new issue. I'm very aware.

**Comment by Dream-Master** [comment]
Yes but i ask on Binnies side because i thought it might an issue on thier side (or the devs behind it).

**Comment by draknyte1** [comment]
Totally unrelated to Binnies.

**Comment by npawk12** [comment]
Seems like a temporary fix is deleting/editing en_US.lang to restore old block names. Although the Frame Housing and Mutatron get changed then. Seems like its trying to copy the name of whatever block is Alveary.2 and Alveary.3

**Comment by draknyte1** [comment]
Forever fixed in https://github.com/draknyte1/GTplusplus/commit/ba6fd91908ca2c888c18606c00134586d2bc9c6d.
