### ISSUE TITLE
Potin Creation Methods

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#120]
It takes 13.3s to make Potin Dust in a LV mixer which can directly be smelted into ingots while using the ABF it takes 40s to make Liquid Potin at HV. I'm assuming the former is un-intended.

Using latest GT from Github and IC2 2.2.827. Also using latest GT++ from Github.

![1](https://user-images.githubusercontent.com/30293976/28773788-a0585668-75f3-11e7-8181-fa86f8d5f7b6.png)
![2](https://user-images.githubusercontent.com/30293976/28773791-a38d2016-75f3-11e7-90e1-4c8fcf630b20.png)
![3](https://user-images.githubusercontent.com/30293976/28773795-a63b03dc-75f3-11e7-8b68-0600625144cb.png)

**Comment by draknyte1** [comment]
I see lately you've posted a few issues.
If possible could you adhere to the guidelines for issue creation?
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Times taken for ABS'ing has changed a lot lately.
It's not intended per-say, but the times are generated totally differently.
This will apply to nearly any material without a blast furnace recipe.

**Comment by npawk12** [comment]
Will do. For minor issues should I open seperate issues for each of them or bunch them all together?

**Comment by draknyte1** [comment]
Whichever you prefer, I am easy going.
Just make sure the title reflects either 'Thing is broken' or 'Collection of issues' sort of thing. :)
