### ISSUE TITLE
Redstone alloy cables have no selection box in world [1.5.6]

### ISSUE THREAD

**Issue by AmishInvader** [draknyte1/GTplusplus#121]
1.5.6

Redstone alloy cables have no selection box when placed in the world, so they can't be broken/picked up once placed.

Placing a machine or something they connect to next to them will give them a selection box, but it isn't the correct size.  Redstone alloy wires do not have this issue.

**Comment by draknyte1** [comment]
Please refer to this format. https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

It's probably a gregtech issue.

**Comment by AmishInvader** [comment]
GT   5.09.31.19
IC2  2.2.828a

Redstone alloy cables (from GT++ not red alloy cables from base GT), when placed in the world, have no selection box.

Placing a machine or something they connect to next to them will give them a selection box, but it isn't the correct size.  The bare wire version of these cables do not have the issue, nor do any other base GT cables.
Repeatable
Singleplayer
Not a major issue

**Comment by draknyte1** [comment]
I am not sure how to resolve this one sorry.
Nothing I can do within GT++ as I simply just call
`makeWires(Material, Voltage, Amp, isInsulated);`

**Comment by bear989** [comment]
they are also not red, but i am just being picky at this point

**Comment by draknyte1** [comment]
> they are also not red, but i am just being picky at this point

Cannot fix that, since Gregtech itself doesn't give that material any colour.
Same reason the Cables made from BigReactor materials aren't yellow or blue.

Something Blood Should Fix really..
