### ISSUE TITLE
Computer Cube gets consumed in crafting (Minor) [v1.5.9]

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#122]
The Computer Cube gets consumed when used to craft a Tesseract Generator. Since the tooltip says its "Reusable", I'm assuming this is un-intended. 

Using the latest GT from Github and IC2 ver 2.2.827.

**Comment by draknyte1** [comment]
It's actually intended.
The 'Reusable' tooltip is related to the fact it's not a single use battery.
