### ISSUE TITLE
Large Chemical Reactor Textures are bugged [1.5.9]

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#123]
As of v1.5.9, the LCR along with Hatches/Buses in the multiblock seem to take on a texture simillar to an IDSU. Removing GT++ or using a previous version seems to fix the issue. 

Using the latest GT from Github and IC2 2.2.827.

![after](https://user-images.githubusercontent.com/30293976/29167910-3369b062-7dd5-11e7-93dc-d56d57a9b3d6.png)
![before](https://user-images.githubusercontent.com/30293976/29167911-33a6c808-7dd5-11e7-965f-612f88680cee.png)

**Comment by draknyte1** [comment]
Issue occurs because the LCR is using my texture range and will be fixed in the next GT release.
