### ISSUE TITLE
Wire Factory Benefits [1.5.9]

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#124]
Currently the Wire Factory consumes the same total EU and has the same processing time as its single block counterpart. Tested by crafting 1x Graphene Wire, Fine Gold Wire and 1x Gold Wire with a MV Hatch and timing it with a stopwatch.

Using the latest GT from Github and IC2 2.2.827.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/b0e7e05c12db75e16031d2d9b3050210987668e4.
