### ISSUE TITLE
Add 25 new ores [Idea]

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#127]
# New Ores to be added by GT++

Geikielite - https://en.wikipedia.org/wiki/Geikielite
Geikielite is a magnesium titanium oxide mineral with formula: MgTiO3.

Zimbabweite - https://en.wikipedia.org/wiki/Zimbabweite
Zimbabweite is a mineral; formula (Na,K)2PbAs4(Nb,Ta,Ti)4O18.

Titanite - https://en.wikipedia.org/wiki/Titanite
Titanite, or sphene (from the Greek sphenos (σφηνώ), meaning wedge[4]), is a calcium titanium nesosilicate mineral, CaTiSiO5. Trace impurities of iron and aluminium are typically present. Also commonly present are rare earth metals including cerium and yttrium; calcium may be partly replaced by thorium.

Zirconolite - https://en.wikipedia.org/wiki/Zirconolite
Zirconolite is a mineral, calcium zirconium titanate; formula CaZrTi2O7. Some examples of the mineral may also contain thorium, uranium, cerium, niobium and iron; the presence of thorium or uranium would make the mineral radioactive. It is black or brown in color.[2]

Crocoite - https://en.wikipedia.org/wiki/Crocoite
Crocoite is a mineral consisting of lead chromate, PbCrO4

Nichromite - https://en.wikipedia.org/wiki/Nichromite
Nichromite (Ni,Co,Fe)(Cr,Fe,Al)2O4 is a black cubic metallic mineral and member of the spinel group

Yttriaite - https://en.wikipedia.org/wiki/Yttriaite-(Y)
Yttriaite-(Y) is an exceedingly rare mineral, a natural form of yttrium oxide, Y2O3

Samarskite - https://en.wikipedia.org/wiki/Samarskite-(Y)
Samarskite is a radioactive rare earth mineral series which includes samarskite-(Y) with formula: (YFe3+Fe2+U,Th,Ca)2(Nb,Ta)2O8 and samarskite-(Yb) with formula (YbFe3+)2(Nb,Ta)2O8. The formula for samarskite-(Y) is also given as: (Y,Fe3+,U)(Nb,Ta)O4.

Zircon - https://en.wikipedia.org/wiki/Zircon
Zircon ( /ˈzɜːrkɒn/[6][7] or /ˈzɜːrkən/[8]) is a mineral belonging to the group of nesosilicates. Its chemical name is zirconium silicate and its corresponding chemical formula is ZrSiO4.

Gadolinite - https://en.wikipedia.org/wiki/Gadolinite
Gadolinite, sometimes known as ytterbite, is a silicate mineral consisting principally of the silicates of cerium, lanthanum, neodymium, yttrium, beryllium, and iron with the formula (Ce,La,Nd,Y)2FeBe2Si2O10. It is called gadolinite-(Ce) or gadolinite-(Y), depending on the prominent composing element (Y if yttrium predominates, and Ce if cerium)

Lepersonnite-(Gd) - https://en.wikipedia.org/wiki/Lepersonnite-(Gd)
Lepersonnite-(Gd) is a very rare rare-earth and uranium mineral with the formula Ca(Gd,Dy)2(UO2)24(SiO4)4(CO3)8(OH)24·48H2O.

Xenotime - https://en.wikipedia.org/wiki/Xenotime
Xenotime is a rare earth phosphate mineral, the major component of which is yttrium orthophosphate (YPO4).

Yttrialite - https://en.wikipedia.org/wiki/Yttrialite
Yttrialite or Yttrialite-(Y) is a rare yttrium thorium sorosilicate mineral with formula: (Y,Th)2Si2O7.

Yttrocerite - https://en.wikipedia.org/wiki/Yttrocerite
Yttrocerite is a variety of the mineral fluorite with a chemical formula CaF2+(Y,Ce)F3.

Polycrase - https://en.wikipedia.org/wiki/Polycrase
Polycrase or polycrase-(Y) is a black or brown metallic complex uranium yttrium oxide mineral with formula: (Y,Ca,Ce,U,Th)(Ti,Nb,Ta)2O6. 

Zircophyllite - https://en.wikipedia.org/wiki/Zircophyllite
Zircophyllite is a complex mineral, formula (K,Na)3(Mn,Fe)7(Zr,Ti,Nb)2Si8O24(OH,F)7.

Zirkelite - https://en.wikipedia.org/wiki/Zirkelite
Zirkelite is an oxide mineral with formula: (Ca,Th,Ce)Zr(Ti,Nb)2O7.

Lanthanite - https://en.wikipedia.org/wiki/Lanthanite
Lanthanites are a group of isostructural rare earth element (REE) carbonate minerals. This group comprises the minerals lanthanite-(La), lanthanite-(Ce), and lanthanite-(Nd). This mineral group has the general chemical formula of (REE)2(CO3)3·8(H2O). Lanthanites include La, Ce, and Nd as major elements and often contain subordinate amounts of other REEs including praseodymium (Pr), samarium (Sm), europium (Eu) and dysprosium (Dy). The lanthanite crystal structure consists of layers of 10-fold coordinated REE-oxygen (O) polyhedra and carbonate (CO32−) groups connected by hydrogen bonds to interlayer water molecules, forming a highly hydrated structure.

Hibonite - https://en.wikipedia.org/wiki/Hibonite
Hibonite ((Ca,Ce)(Al,Ti,Mg)12O19) is a brownish black mineral with a hardness of 7.5-8.0 and a hexagonal crystal structure. It is rare.

Cerite - https://en.wikipedia.org/wiki/Cerite
Cerite is a complex silicate mineral group containing cerium, formula (Ce,La,Ca)9(Mg,Fe+3)(SiO4)6(SiO3OH)(OH)3. The cerium and lanthanum content varies with the Ce rich species (cerite-(Ce)) and the La rich species (cerite-(La)). Analysis of a sample from the Mountain Pass carbonatite gave 35.05% Ce2O3 and 30.04% La2O3

Agardite - https://en.wikipedia.org/wiki/Agardite
Agardite is a mineral group consisting of agardite-(Y), agardite-(Ce), agardite-(Nd), and agardite-(La). They comprise a group of minerals that are hydrous hydrated arsenates of rare earth elements (REE) and copper, with the general chemical formula (REE,Ca)Cu6(AsO4)3(OH)6·3H2O.

Fluorcaphite - https://en.wikipedia.org/wiki/Fluorcaphite
Fluorcaphite is a mineral with the chemical formula (Ca,Sr,Ce,Na)5(PO4)3F. It is found in the Kola Peninsula in Russia. Its crystals are hexagonal (dipyramidal class). It is light to bright yellow and leaves a white streak. It is transparent and has a vitreous luster. It is rated 5 on the Mohs Scale. Fluorcaphite is radioactive.

Florencite - https://en.wikipedia.org/wiki/Florencite-(Sm)
Florencite-(Sm) is a very rare mineral of the plumbogummite group (alunite supergroup) with simplified formula SmAl3(PO4)2(OH)6. Samarium in florencite-(Sm) is substituted by other rare earth elements, mostly neodymium. 

Cryolite - https://en.wikipedia.org/wiki/Cryolite
Cryolite (Na3AlF6, sodium hexafluoroaluminate) is an uncommon mineral.

Pyroxene - https://en.wikipedia.org/wiki/Pyroxene#Pyroxene_minerals
The pyroxenes (commonly abbreviated to Px) are a group of important rock-forming inosilicate minerals found in many igneous and metamorphic rocks. Pyroxenes are silicon-aluminum oxides with Ca, Na, Fe, Mg, Zn, Mn, Li substituting for Si and Al. The general formula is XY(Si,Al)2O6 (where X represents calcium, sodium, iron+2 and magnesium and more rarely zinc, manganese and lithium and Y represents ions of smaller size, such as chromium, aluminium, iron+3, magnesium, cobalt, manganese, scandium, titanium, vanadium and even iron+2).

**Comment by Antillar** [comment]
Are these ores going to use GT oregen system? There may be issues with generating them because of this. Also do you plan to do ore mixes and what stats to assign to those mixes if you do?

**Comment by draknyte1** [comment]
This was already discussed on discord. 

They will spawn in GT mix veins. 
There will not be issues and I don't know why you think there will be. 

They will generate in a different dimension and not the overworld. 
Mixes will be ores of similar types, as real life.
