### ISSUE TITLE
Make native ores give bonuses on pulverization

### ISSUE THREAD

**Issue by redmage17** [draknyte1/GTplusplus#128]
say 3x and if you have way to add all GT ores to Thaumcraft without hard coding that would be nice. Would be a nice buff for both TC and GT and bring it on par with some other ore multiplication mods

**Comment by draknyte1** [comment]
Did you still want me to look into this or did you want to do it?

**Comment by codewarrior0** [comment]
Warning: Electro-Magic Tools already does this. Crushing a native cluster gives 22 tiny dusts and nothing else.

**Comment by draknyte1** [comment]
I know fuck all about TC.
So, I'm happy not to do it at all.

**Comment by redmage17** [comment]
Native clusters are what you get by either mining with a Pickaxe of the core, or using alchemy to purify the ore into a native cluster.Both require a decent bit of progress and knowledge about TC.   By default all the purified ores do is smelt into 2 ingots. It also does not include a majority of GT Ores. I will probably go through and do PR for the missing native clusters so I can balance them. But being able to pulverized the existing ores into x3 or x4 crush ore would be ideal.
