### ISSUE TITLE
Redstone Cables Bugs [1.6.02] Updated for 1.6.05

### ISSUE THREAD

**Issue by venturaguy101** [draknyte1/GTplusplus#133]
Several issues I want to point out with the redstone cables:

1) Cables cannot be cut/removed by using wire cutters, pick axes (both standard and GT picks), drills, etc.  Once they are placed there currently no way to remove them.  The drill drilled stone right behind the cable like it was not even there
2) You cannot place covers on the cables like the other GT cables.  So there is no way to prevent them from not connection to other cables or machines unless you put the cover on the other machines.
3)  Unable to place the cable on the cable.  I was only able to place cables if it was next to a stone block.  You are unable to stack cable vertically unless next to a wall or pillar.
4)  Visual glitch when you walk up to the cable you walk into the cable and it disappears. 
5)  Cosmetic issue/suggestion:  The cables should have a red wire color since using redstone instead of the silver color.

**Comment by draknyte1** [comment]
All issues except (5) have been fixed here - https://github.com/draknyte1/GTplusplus/commit/c59b80a99039231df35d6cb39afbf57904ca86b9.

Gregtech itself does not give this material a colour, co I cannot fix that unfortunately.

**Comment by venturaguy101** [comment]
I just noticed that I was using 1.6.02.  Is there are release that has the other fixes?

**Comment by Technus** [comment]
The color could be fixed with an override and new constructor if you really want to.
