### ISSUE TITLE
Solar generator bug?

### ISSUE THREAD

**Issue by Invincible92** [draknyte1/GTplusplus#134]
Hi Alkalus

It seems the solar generator has its GUI swapped with the solar boiler; I have not tested if it outputs EU or not. I leave attached a screenshot showing it.

![2017-09-24_23 41 21](https://user-images.githubusercontent.com/11424960/30805967-1e947f3a-a1f4-11e7-96ff-1266817d0eba.png)

**Comment by draknyte1** [comment]
Not really a bug, I just never made them a special gui.
They are based on Solar Boiler code, so, I just left them as is.
