### ISSUE TITLE
Add multiblock energy buffer

### ISSUE THREAD

**Issue by 4erk** [draknyte1/GTplusplus#135]
Multiblock structure from 3x3x3 to 5x5x5 (7x7x7) 
Control block (hv, iv, zpm for 3x3x3, 5x5x5,7x7x7) - bottom center - in GUI show stored/max energy, slot for configured circuit
multiblock energy casing min 
maintenance - any problems decrease input and output energy an 10%
input bus - gives batteries/energy crystall (max 432 for 3x3x3 , 2000 for 5x5x5, 5488 for 7x7x7)
output bus - output batteries|crystall (configured circuit 0|none - all, 1 - only empty, 2 - only full charged, 4 - half charged or less, 5 - more, than half charged, 6 - not output)
energy hatch (1  or more, min hv/iv/zpm lvl for control block same lvl) - any casing, - charging only batteries same lvl or less, 
energy dynamo hatch - (1 or more) - output energy and discharging atteries sane lvl or less

**Comment by draknyte1** [comment]
There is already a power storage multiblock.
Which can accept and output any voltage and charge/discharge batteries in the busses.
