### ISSUE TITLE
worldgen crash [1.6.05] 

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [draknyte1/GTplusplus#137]
GT 5.09.31
IC2 2.2.827

Updating from 1.6.02 to 1.6.05 causes a crash when generating a new singleplayer world.

https://pastebin.com/GypG6Xmz

**Comment by draknyte1** [comment]
GT++ Does NOT touch worldgen.
Its another mod at fault.

**Comment by bHXDgiuMa5yLHyC8** [comment]
It's some kind of conflict with Chisel (2.9.5.11). I get this crash playing with just GT++, its dependencies, and Chisel.

https://pastebin.com/mUYav6ST

**Comment by bHXDgiuMa5yLHyC8** [comment]
I tried setting to zero all the values for the types of rock in the chisel configs so that there should be no modded worldgen, but the crash still occurs. Disabling the bonus chest changes the crash log to this:

https://pastebin.com/tgMMXLgj

**Comment by Technus** [comment]
[draknyte1/GTplusplus] Issue opened: #139 Crash when break any block on existing world \[1\.6\.05\] most likely same issue

**Comment by bHXDgiuMa5yLHyC8** [comment]
Thanks!
