### ISSUE TITLE
Hydrofluoric Acid Cell 4198:15

### ISSUE THREAD

**Issue by Cantankerous-Rex** [draknyte1/GTplusplus#140]
When you try and transfer this liquid out of the cell the cell just disappears and no liquid is transferred. Tried it in a fluid canner, manually and in an AE system. This makes getting industrial strength hydrofluoric acid very slow as the only other way seems to be through Apatite mix in the Distillation tower.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/f7faf891fa1106a04f2e2b78f18aa5d161762db2.
