### ISSUE TITLE
Мultiblock machines do not work correctly (Maceration Stack, Sieve, etc..)

### ISSUE THREAD

**Issue by 4erk** [draknyte1/GTplusplus#141]
1. Maceration stack
![image](https://user-images.githubusercontent.com/20582935/31301491-f295fd10-ab02-11e7-8f50-62cd6fb95665.png)
![image](https://user-images.githubusercontent.com/20582935/31301089-29d3ee7a-ab00-11e7-8925-ee050f293211.png)
Regardless of the tier of energy hatch (now, as I understand, the casing is always full tier- from the paladium) it works for 10 seconds and turns off and takes at the same time only one ore block at a time, while working quite slowly. After turning it off, do not turn it back on.
on the screen all the elements (input, outpute, hatch energy)
![image](https://user-images.githubusercontent.com/20582935/31301229-2818953a-ab01-11e7-9ddc-13c2100ab290.png)
![image](https://user-images.githubusercontent.com/20582935/31301237-31a90d78-ab01-11e7-832e-d232c3c07516.png)
2. With the Sieve i have same problem
3. An industrial material press is an analog of a single-block press? Since the recipes of the forming press or compressor  it does not take

4. Incorrect description for Large Thermal Refinery
![image](https://user-images.githubusercontent.com/20582935/31302693-81473ffc-ab0c-11e7-8927-f2d4e82e8a38.png)
![image](https://user-images.githubusercontent.com/20582935/31302698-85c29220-ab0c-11e7-9319-86efb664b7ce.png)
![image](https://user-images.githubusercontent.com/20582935/31302709-a20f5eb8-ab0c-11e7-967f-71877528c1fe.png)

**Comment by draknyte1** [comment]
I am aware of this and currently trying to resolve the multiblock issue.

The Material press is a bending machine.
The Thermal centrifuge is 3x2x3 (L x H x W)

**Comment by 4erk** [comment]
1. Okay. I'm waiting for the next releases.
2. Then the industrial press does not work.
![image](https://user-images.githubusercontent.com/20582935/31303179-f032b388-ab11-11e7-8556-ad1e071ab4c8.png)
3. My mistake. Sorry, I was not paying attention.

**Comment by draknyte1** [comment]
I am not sure what broke all the multiblocks.. So I'll do another release when it's fixed.
The Material press (As the tooltip says) requires the circuit in the input bus still.

**Comment by 4erk** [comment]
https://www.youtube.com/watch?v=0TTgm33IVlQ
Thisi how working (not working) multiblock machines (tested on IV tier components)
