### ISSUE TITLE
Power station do not emit energy and do not charging items

### ISSUE THREAD

**Issue by 4erk** [draknyte1/GTplusplus#142]
![image](https://user-images.githubusercontent.com/20582935/31302115-e17b7a28-ab07-11e7-89e8-610a01f4434c.png)
* all hatches and buffers IV tier
Power station do not emit energy from dynamo hatch and do not charging items in input or output bus (discharging too)

+ idea: add support energy sensor kit of nuclear controll addon

**Comment by YinScape** [comment]
Can confirm, also having this issue but with a few differences.
The buffers charge extremely slowly, and with 1.6.09, the multiblock fails to assemble in multiplayer but not in singleplayer.

**Comment by draknyte1** [comment]
Should now be resolved.
