### ISSUE TITLE
Override wrong names and functions of Alveary blocks

### ISSUE THREAD

**Issue by leagris** [draknyte1/GTplusplus#145]
#### Wrong ~~Alveary blocks~~ overrides:
https://github.com/draknyte1/GTplusplus/blob/master/src/resources/assets/forestry/lang/en_US.lang#L1-L8

```
tile.for.alveary.0.name=Alveary
tile.for.alveary.1.name=Alveary ERROR
tile.for.alveary.2.name=Alveary Frame Housing
tile.for.alveary.3.name=Alveary Mutatron
tile.for.alveary.4.name=Alveary 1
tile.for.alveary.5.name=Alveary 2
tile.for.alveary.6.name=Alveary 3
tile.for.alveary.7.name=Alveary 4
```

#### Correct Forestry Alveary blocks assignments:
https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/en_US.lang#L1105-L1112

```
tile.for.alveary.0.name=Alveary
tile.for.alveary.1.name=Alveary Entrance
tile.for.alveary.2.name=Swarmer
tile.for.alveary.3.name=Alveary Fan
tile.for.alveary.4.name=Alveary Heater
tile.for.alveary.5.name=Alveary Hygroregulator
tile.for.alveary.6.name=Alveary Stabiliser
tile.for.alveary.7.name=Alveary Sieve
```

**Comment by Dream-Master** [comment]
yea have the same error wrote this script.

https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Forestry.zs#L2829-L2848

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/e3209d57bfa5e9a07846acca8f3e220127ce4e1f.
