### ISSUE TITLE
[1.6.02] Tree Farmer

### ISSUE THREAD

**Issue by KorGgenT** [draknyte1/GTplusplus#146]
1.
![image](https://user-images.githubusercontent.com/30208401/31474253-8c38c606-aec7-11e7-975c-9befc5cf2d3b.png)
The GUI doesn't show the correct amount of energy stored and the max storage. it just loops through -32000 and 32000.

2.
![image](https://user-images.githubusercontent.com/30208401/31474269-a5de7ee8-aec7-11e7-938b-d127bc6dcc28.png)
Saws don't break.

3.
![image](https://user-images.githubusercontent.com/30208401/31474278-afe25d74-aec7-11e7-8937-bd292deb34a6.png)
Portable scanner doesn't give useful output. It should show my energy hatches and stuff.
Also, 5 problems?

4.
![image](https://user-images.githubusercontent.com/30208401/31474292-cd90363e-aec7-11e7-8aa1-3f46433fbc50.png)
The Tree farmer doesn't follow GT multiblock conventions. It should say the hatches and buses and maintenance hatches that are required for the machines to run, in addition to the fertiliser cost, or if it's optional. (some of this stuff could just be put on a wiki page i suppose)
Perhaps an alternate fix is to show problems in the gui like traditional GT machines, like "missing output hatch" etc.

**Comment by MoXiaoFreak** [comment]
I followed the convention but I couldn't make it work.You said it requires hatches and buses,but where should I set them down?Could you please take another screenshot of the whole multiblock?

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/31576310-13bfad56-b0c6-11e7-855d-59203cbb4bd1.png)
from left to right: Maintenance hatch, output bus, energy hatch, controller, input hatch, input bus.

**Comment by Dream-Master** [comment]
@draknyte1 any idea on this issue?

**Comment by Technus** [comment]
@draknyte1  should be addressed in the merge

**Comment by draknyte1** [comment]
I left this open because I saw your fix commits ages ago and knew they'd come across.

**Comment by draknyte1** [comment]
Should be fixed in https://github.com/draknyte1/GTplusplus/commit/57cbeeecd11b429347bbe31ef4f28a97ad721a50.
