### ISSUE TITLE
Crash with 1.6.07 release, -05 is fine

### ISSUE THREAD

**Issue by Auge103** [draknyte1/GTplusplus#147]
As the title says, game crashes on load with -07, with -05 it works.

"cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gtPlusPlus/xmod/forestry/HANDLER_FR"

Crashreport: 
https://0bin.net/paste/UuCP8pE8c7-oXaLE#EHioZo7dmuKrBlpSimLpXjGZnhRdQRMRfRbDz-Mw1ny

**Comment by Scrik** [comment]
+ 
please add config Disable forestry!
I use MineFactoryReloaded

**Comment by draknyte1** [comment]
Sure, Ill fix it when I return from vacation in a month.
