### ISSUE TITLE
Pollution Scrubber uses Turbine Blades very fast

### ISSUE THREAD

**Issue by LOKKO12** [draknyte1/GTplusplus#155]
The LV pollution scrubber uses turbine blades (small steel, large desh) very quick. Both were broken after ~10sec. Is this intended or a bug?
Used Version GT-PlusPlus-1.6.09-release.jar on the Gregtech New Horizons Server Delta. Placed the rotor in the left slot, the carbon filter (Tier 1) in the right slot. The Machine was on a 12A Redstone Alloy Cable. The Chunk had ~450.000 Gibbl.

**Comment by Lithorn** [comment]
Its not just the LV type. Titanium small rotor in a MV went down in about 15s or so. The air filter took no damage.

**Comment by draknyte1** [comment]
I'm aware. They should now use between 1-4000 durability per second. Fixed in dev.
