### ISSUE TITLE
Ore Wash Plant - Phantom Crushed Ores

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#159]
When it comes to the end of a stack. it leaves a "Phantom" crushed ore in the Input Bus that cannot be manipulated by anything or deposited, but can be removed from the Input Bus into the inventory (only with click-and-place, shift-click does not work). This also means that, whenever a stack of 1 is placed, it instantly becomes a phantom crushed ore, and it does not output a crushed ore.

* Observed in GT++ 1.6.99
* GregTech 05.09.32pre1 environment

**Comment by Technus** [comment]
Sounds much like 0 size stack
