### ISSUE TITLE
GT Multitank

### ISSUE THREAD

**Issue by Ldmf** [draknyte1/GTplusplus#16]
Wrong Tool tip (Size: 3xHx3)

![2016-09-25_17 08 08](https://cloud.githubusercontent.com/assets/15316448/18816128/ee02cef6-8342-11e6-843f-a73d805cbcb8.png)

Version: GT-PlusPlus-1.4.8.2-prerelease-hotfix-2

**Comment by draknyte1** [comment]
It can be any height.. As long as it's minimum 4 tall.

Other than in creative testing, I currently don't recommend using one of these..

**Comment by Ldmf** [comment]
ok i was thinking it is a error ^^
