### ISSUE TITLE
[GTNH] MultiA energy hatches for Power station multiblock

### ISSUE THREAD

**Issue by Cinobi** [draknyte1/GTplusplus#161]
There are a multiA energy hatches and dynamo hatches in server, will it work with power station multiblock? If not - add support please.
![2017-12-12_15 03 39](https://user-images.githubusercontent.com/25028786/33883674-b35b7c54-df4d-11e7-8863-336c7d5f04c1.png)
![2017-12-12_15 03 43](https://user-images.githubusercontent.com/25028786/33883675-b380b65e-df4d-11e7-9239-479602ff9db3.png)
![2017-12-12_15 03 55](https://user-images.githubusercontent.com/25028786/33883733-fe8da22e-df4d-11e7-8c1f-8100008c7299.png)

**Comment by Technus** [comment]
Up to UV tier!
