### ISSUE TITLE
Client code on server side

### ISSUE THREAD

**Issue by Technus** [draknyte1/GTplusplus#163]
https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/GTplusplus.java#L75

**Comment by Technus** [comment]
move inside here i guess
https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/GTplusplus.java#L77

**Comment by draknyte1** [comment]
Fixed in #165.
