### ISSUE TITLE
Multiblocks not working properly or just worse than single block machines

### ISSUE THREAD

**Issue by Traxis** [draknyte1/GTplusplus#164]
Just cross-posting this here so you can see it better (hope it helps): https://github.com/GTNewHorizons/NewHorizons/issues/2261

See a copy of the issue below:

-----------------------------------------------------

#### Which modpack version are you using?

2.0.2.0

#
#### If in multiplayer; On which server does this happen?

--
#
#### What did you try to do, and what did you expect to happen?

I'm testing GT++ multiblocks, and find out this:

1. maceration stack processes ores uncorrectly. According to description, in IV in should produse 8*5 items\operation, means 40\operation, but in realty it process 1 item\operation
    https://youtu.be/pauKkRrStvM
    ![2017-12-14_20 48 51](https://user-images.githubusercontent.com/2103169/34017468-3481f248-e126-11e7-88c4-cce6017e98ec.png)

---

2. Industrial sifter
    Works fine, but slow - 1 item\operation too, don't think profit with "more gems" cover it.

---

3. Industrial centrifuge:
    Can't turn in on, nuff said.

---

4. Industrial coke oven
    Works, but insanely slow, pyrolisite do the trick much more speedy.
    And, coke coal recipy for example:
    Pyrolisite: 16 coal -> 16 coke in 32 seconds
    InduCokeOven: 8 coal -> 5 coke in 15 seconds
    Eats more energy@Less efficient@Produse less in some time@req steam

---

5. Industrial material press
    Dunno what this multiblocks suppose to do, can't start it with compressor and forming press recipes.

---

6. Industrial electrolyser
    Works fine, but process 1 item\operation.

---

7. Wire facrory
    Works fine, but still - 1 item\operation.

---

can't test another multiblocks for now, sorry.

Don't think we need "Large multiblock little faster than singleblock machine". I thinked GT++ was added as a replacement for arrays filled with machines, but...

**Comment by LOKKO12** [comment]
I personally think the sifter is balanced, but maybe you could change it to take in 8/16/32/64 Items at IV/LuV/ZPM/UV, with HV/EV/IV/LuV speed. (or similar)
Ideas for the other Multiblocks:
Change it to take in 1 Amp for every 1/2/4/8/16/32/64 (MV/HV/EV/IV/LuV/ZPM/UV), which can be configured by a circuit ( f.e. Cirq 1 = 1A = 16Items per operation at LuV, with LuV+X%speed, Cirq 4 = 4A = 64Items per operation at LuV, with LuV+X%speed)

**Comment by codewarrior0** [comment]
I think this one is more or less fixed.

**Comment by draknyte1** [comment]
Yep. Fixed in 1.7.0.
