### ISSUE TITLE
potin stuff missing

### ISSUE THREAD

**Issue by bear989** [draknyte1/GTplusplus#17]
plates in extruder, plates and double plates in metal bender power costs are off as well

**Comment by draknyte1** [comment]
Do Plates, Dbl plates, etc have a base cost like pipes do?
Since most pipes are 128, some are 512..

**Comment by bear989** [comment]
extruder cost IMO should be 128 RU/t same as all the base materials. plates in the bender should be 32 EU/t same as base materials, the double plates in the bender I do believe are the same cost per tick just long time. These changes will allow the ULV tank to be made without lose once you get to LV power.

**Comment by draknyte1** [comment]
Fixed in Dev, will upload fresh builds with new material changes within the next 12hr, once I have access to do so from my desktop.
