### ISSUE TITLE
Mekanism OreDict changes reversal

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#171]
In 1.6.99, the mods correctly strips Mekanism items of their Forge Ore Dictionary entries, which means that the Mekanism Ore and Circuits are useless for GregTech progression.

In 1.6.103 and 1.6.110, this modification is no longer in effect, and Mekanism circuits and ore can freely be used by GregTech.

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Feel free to edit this one and comment, so it can be reopened.
