### ISSUE TITLE
Large Thermal Boiler multiblock issue

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#172]
In 1.6.99, the multiblock performs normally.

In 1.6.103 and 1.6.110, the multiblock no longer recognises itself as a complete multiblock (even on an inherited multiblock that worked fine in 1.6.99), and also does not recognise tools used on the Maintenance Hatch.

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Feel free to edit this one and comment, so it can be reopened.
