### ISSUE TITLE
Ore Wash Plant multiblock issue

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#173]
In 1.6.99, it works flawlessly.

As of 1.6.110, this no longer works unless you have a Soft Mallet to trigger individual washes, but it does correctly process 2 items.

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Feel free to edit this one and comment, so it can be reopened.
