### ISSUE TITLE
[GTNH] Chemical Dehydrator recipe give Tinkers Aluminum not GT Aluminium

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#174]
[GTNH] Chemical Dehydrator recipe give Tinkers Aluminum not GT Aluminium

GTNH Version 2.0.2.5 (GT++ 1.6.110)

![image](https://user-images.githubusercontent.com/2970688/34319872-b94ea544-e7ec-11e7-9102-fd07a730f1cd.png)

**Comment by Dream-Master** [comment]
Same for Eglin Steel Alloy Blast Smelter

![image](https://user-images.githubusercontent.com/2970688/34319880-071284a8-e7ed-11e7-8b63-26f8eee0d0ae.png)

**Comment by draknyte1** [comment]
I really can't solve this issue because GT is giving you aluminium..

**Comment by Dream-Master** [comment]
But the Tico Aluminum is not the same then gt Aluminium. And GT ignore Tico Ores for unification.
