### ISSUE TITLE
[GTNH][Suggestion] Energy capacity machines/batteries

### ISSUE THREAD

**Issue by Bryfer** [draknyte1/GTplusplus#175]
One thing that has been bugging me for quite some time now is the really huge internal battery sizes of GT++ machines, compared to vanilla GT machines

For example 
LV machines has an internal buffer of 3 244 800 eu, which takes approxly 3.5 hours to fill up using LV power generation
MV machines, 32 000 000 eu, also 3.5hours at MV power generation
IV machines, 2 048 000 000eu, also 3.5hours at IV power generation

so basicly when you make a new gt++ machine you will need to produce energy for 3.5 hours, at that tiers machine just to charge it up fully so you after that get your normal powergrid back.

Same thing goes with battery buffers,. And I havent been able to figure out any good reasons to have an internal capacity this high.

Would it be possible to reduce the internal capacities (also batteries) to better fit into GT power styles?
I belive the best would be to allow this multiplies to be configured by config file? (if some people prefer the huge buffers in other modpacks that is)

There is also an issue on the GTNH github about this (and some modpack related issues) if you would like to read my first post about this.
https://github.com/GTNewHorizons/NewHorizons/issues/2080

**Comment by draknyte1** [comment]
They're not that high.. they're set by Gregtech internal logic. 

GT++ does not add battery buffers, but energy storage blocks. They have a high storage on purpose. Every block in my mod can be disabled, so feel free to turn them off.

**Comment by Bryfer** [comment]
Gregtech medium voltage buffer with 16 batteries;
131072 + (16x400000) = 6 531 072 EU
GT++ MV energy buffer 32 000 000 EU
**SET BY GREGTECH INTERNAL LOGIC**

Btw, I hate to be the one to tell you. but apperently you named the Medium Voltage Energy Buffer wrong. Should be Medium Voltage Energy Storage Block apperently.
Would you like me to edit my OP post so you are able to read it properly?
![image](https://user-images.githubusercontent.com/22825059/34327389-543db956-e8c3-11e7-90ac-010c2be98c26.png)

But I dislike how you really fail to see the issue here. Good day to you Sir.

**Comment by draknyte1** [comment]
I don't see the issue..
They're intended to store 32mil, as the name implies, they buffer energy.

**Comment by Dream-Master** [comment]
Maybe we need to go over the recipes for GTNH
