### ISSUE TITLE
Power Substation works for one tick

### ISSUE THREAD

**Issue by YinScape** [draknyte1/GTplusplus#176]
Currently playing GT:NH, on assembly, the power substation works for several ticks before shutting off.
On a soft-mallet enable, it runs for exactly 1 tick and then shuts off.  Repeated mallet hits make it run one more tick before shutting off.

Running GT++: 1.6.110
GT: 5.09.32.15
This is running on a server, Forge 1.7.10 - 1614.

**Comment by LOKKO12** [comment]
Same for big Sifter with HV hatch.

**Comment by draknyte1** [comment]
Sifter works fine in 1.6.110 @lokko12.

**Comment by Cinobi** [comment]
same for maceration stack, GTNH pack.
