### ISSUE TITLE
Air recycler upkeep is far too expensive

### ISSUE THREAD

**Issue by Fapiko** [draknyte1/GTplusplus#177]
Currently it seems that the air recycler turbine takes the same durability hit regardless of whether it's cleaning up 6 or 16,000 pollution. I suggest that either the damage be scaled by the pollution amount it scrubs, or at the very least some sort of cover/machine is added to detect the pollution levels so we can trigger it on with a redstone signal.

It's far too expensive to run as-is - it eats turbines way too quickly and isn't worth the ingot cost for the turbines.

**Comment by draknyte1** [comment]
There is a pollution detector for just that.

**Comment by Fapiko** [comment]
Ahh, didn't know that existed.
