### ISSUE TITLE
Trinium Duplicatin

### ISSUE THREAD

**Issue by Fapiko** [draknyte1/GTplusplus#179]
Looking through NEI there is a recipe for turning one Trinium dust into one Refined Trinium dust with the mixer:
![2017-12-30_13 11 32](https://user-images.githubusercontent.com/720212/34456402-1450c10e-ed63-11e7-8845-1bf08db352db.png)

One Refined Trinium Dust can then be turned into one Trinium Dust and a Tiny Trinium Dust in the Centrifuge, netting a gain of one tiny:
![2017-12-30_13 13 19](https://user-images.githubusercontent.com/720212/34456406-3752f47e-ed63-11e7-93c5-93888821a9e3.png)

Centrifuge recipe could be changed to only give the Trinium Dust without the tiny.

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Feel free to edit this one and comment, so it can be reopened.

**Comment by Dream-Master** [comment]
@draknyte1 it's a GTNH issue. So Version 110 is used newest ic2 and my GT fork.
https://github.com/GTNewHorizons/NewHorizons/issues/2328

reverse recipe ned to be changed or the by product changed so something useless.
