### ISSUE TITLE
[Question] Mutagenic Frame

### ISSUE THREAD

**Issue by Ldmf** [draknyte1/GTplusplus#18]
Is it correct that the last tick from the Mutagenic Frame dostent kill the bee instandley (3 frams)

Version: **GT-PlusPlus-1.4.8.2-prerelease-hotfix-2**
Version: **gregtech-5.09.23**

**Comment by draknyte1** [comment]
The last 'tick' on any frame does nothing. This is an issue with forestry, not my frames.

**Comment by Ldmf** [comment]
ah ok thx 4 you answer :)

**Comment by draknyte1** [comment]
I assume too many Mutagenic frames can still cause (-) on Princesses, which causes them to die.
