### ISSUE TITLE
Many Multiblocks just randomly shut down 1tick after starting

### ISSUE THREAD

**Issue by LOKKO12** [draknyte1/GTplusplus#180]
Hey there, just want to report that at least 3 Multiblocks doesnt work at all, this includes the Industrial Sifter, the Power Station Node and the Thermal Boilers. They just shut down 1 tick after activation.

**Comment by draknyte1** [comment]
Please report the issue properly.

**Comment by LOKKO12** [comment]
@draknyte1 edited to match your criteria.

**Comment by ajlohr270** [comment]
Will this be reopened? I'm experiencing the same issue with the sifter. (using 1.6.110-prerelease)

**Comment by Dream-Master** [comment]
@draknyte1

**Comment by Dream-Master** [comment]
@draknyte1 this issue is not fixed @draknyte1

**Comment by draknyte1** [comment]
It will remain as such until my personal situation is resolved. Can't really work on anything right now, apologies.

**Comment by Dream-Master** [comment]
sure
