### ISSUE TITLE
Inconel-625 Dust Recipe

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#181]
NEI lists a Mixer recipe of this Dust using Nickel, Iron, Chrome and Molybdenum. However, when placed in the Mixer, it uses the Invar recipe, which uses Nickel and Iron.

Given that this also has a recipe in the Combiner, and that functions correctly, I suggest removing the Mixer recipe to avoid confusion.

GT++ 1.6.110
GregTech 05.09.32pre1
IC2 2.2.827-experimental
GT++ Single Player
Issue Class: Minor

**Comment by draknyte1** [comment]
Yes.. the.. combiner..
I need to redo the recipes for that as a whole since they don't migrate across properly from the mixer.

The Inconel should probably just use Invar.. as should anything else using iron and Nickel in an appropriate ratio..
