### ISSUE TITLE
Ore Wash Plant Multiblock

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#183]
In GT++ 1.6.99, it works flawlessly.

As of GT++ 1.6.110, this no longer works unless you have a Soft Mallet to trigger individual washes, but it does correctly process 2 items.

Issue is ongoing currently and can be reverted by going back to GT++ 1.6.99.

GregTech 05.09.32pre1
IC2 2.2.827-experimental
GT++ Single Player
Issue Class: Major

**Comment by codewarrior0** [comment]
Additionally, the Plant is not overlocked when built with an MV-tier Energy Hatch or higher.
