### ISSUE TITLE
Alloy Blast Smelter isnt working

### ISSUE THREAD

**Issue by alphaNOVAircraft** [draknyte1/GTplusplus#186]
The Alloy blast smelter isnt working, it is  set up correctly (as far as i can say from the tooltip) and nothing blocks the muffler hatch. I tryed out the recipe with should turn energetic alloy dust into its liquid form, i provided the needed energy (mv, direkt connection of the battery buffer with the energy hatch, 4 amp, recipe only needs 1 amp mv). The machine starts, consumes the dust (right circuit is in the input hatch) but stops nearly instand without producing anything. Machine is fully repaired.

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format
