### ISSUE TITLE
GTNH Trinium issue[GTNH, GT++ 1.6.110 lastest]

### ISSUE THREAD

**Issue by Cinobi** [draknyte1/GTplusplus#187]
#### Which modpack version are you using?
Greg: 5.09.32.15
IC2: 2-2.2.828a-experimental
#### What did you try to do, and what did you expect to happen?
Trying to make naqadah alloy in mixer in delta live server.
#
#### What happend instead? (Attach screenshots if needed)
Trinium from recipe turned into GT++ product

![2018-01-04_16 33 27](https://user-images.githubusercontent.com/25028786/34565802-48e57352-f16d-11e7-9e02-79cc378d59bb.png)

**Comment by draknyte1** [comment]
Please report the issue properly.
https://github.com/draknyte1/GTplusplus/wiki/Github-Issue-Format

Feel free to edit this one and comment, so it can be reopened.
