### ISSUE TITLE
Items missing an OVERLAY [v1.6.99-release]

### ISSUE THREAD

**Issue by leagris** [draknyte1/GTplusplus#188]
### Versions:

- Gregtech: v5.09.31
- IC2: v2-2.2.827-experimental

### Dscription:

I was looking at GT++ versus Gregtech material rings and noticed that Gregtech Rings renders a shine overlay, whereas rings and **all items made of GT++ materials are missing an OVERLAY texture**.

### Reproducibility:

- Permanent and Reproducible.
- Noticeable with Gregtech items natively having an OVERLAY texture like rings.
- Even more noticeable with resources packs having more detailed/expanded overlays.

### Environment affected by issue:

- Client-side rendering.

### Criticality:

- MINOR

### Screenshot of Gregtech vs GT++ Ring:

- ![Gregtech vs GT++ Ring](https://user-images.githubusercontent.com/1111474/34628365-50b84eea-f264-11e7-811b-79e0d2a462d5.png)

### Logs:

- Not applicable

**Comment by draknyte1** [comment]
Actually, it's because GT++ uses the metallic texture set. For every machine component.

**Comment by leagris** [comment]
The METALLIC texture set provides OVERLAYs but GT++ does not use or render these.

| |
|--|
| Base METALLIC Texture for Gregtech RING: ![Gregtech:METALLIC/ring.png](https://raw.githubusercontent.com/Blood-Asp/GT5-Unofficial/unstable/src/main/resources/assets/gregtech/textures/items/materialicons/METALLIC/ring.png) |
| OVERLAY METALLIC Texture shine for Gregtech RING: ![Gregtech:METALLIC/ring_OVERLAY.png](https://raw.githubusercontent.com/Blood-Asp/GT5-Unofficial/unstable/src/main/resources/assets/gregtech/textures/items/materialicons/METALLIC/ring_OVERLAY.png) |

May not be rendered here with nice contract, but the ring overlay has a few white pixels corresponding to top right border of ring.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/adc7902fb98a416694e6952bdb9e915307e6f5e9#diff-718efb387c629725910a61fdd556dc02.
