### ISSUE TITLE
Need a recipe to break down Tumbaga

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#189]
While making Rose gold I left the gold and copper in the mixer but removed the circuit, and got a couple of stacks of Tumbaga instead.  However, there is no way to recover the original ingredients.  Recommend adding an electrolyzer or centrifuge recipe to separate the materials back apart.

**Comment by Dream-Master** [comment]
Add a circuit would be much better but a recycle recipe would be nice too.
