### ISSUE TITLE
I cant get any multiblocks to work [1.6.110-final]

### ISSUE THREAD

**Issue by benstuwie** [draknyte1/GTplusplus#190]
ISSUE CONTENT;
GT version 5.09.32
Ic2 version 2-2.2.828a-experimental
I play gtnh, and after an update I can't get any of the gt++ multiblocks to work that I have. My plate bender broke, and later the abf broke in the same way. They will turn on then off immediately. I can soft mallet them, but they never complete a recipe. They have the right amount of power and the recipe is right. I tried remaking the controller block, but that didn't work. 
Kind of a major issue as I can't use any of the multiblocks. I need a bunch of uu and I was thinking of using the uu multiblock

**Comment by draknyte1** [comment]
Gregtech 5.09.32pre1 isn't supported because it's a test build of GT..

So either roll back to 5.09.31 or wait for a proper 5.09.32 release. The state of multiblocks in GT++ 1.6.110 is quite good, the only one with a known issue is the thermal boiler.

**Comment by Dream-Master** [comment]
And the blast alloy smelter. We tested it yesterday on two servers.

**Comment by benstuwie** [comment]
What versions of gtnh? I haven't got it to work in 2.0.2.5/2.0.2.6

**Comment by Dream-Master** [comment]
not working in 2.0.2.5/2.6 in GTNH maybe before. But in lastest GT++ version 110 it not worked for sure.

**Comment by Lithorn** [comment]
Nor the power station or centrifuge
