### ISSUE TITLE
Power Substation Multiblocks

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#20]
Multiblock configurations for Power Storage.
Power Sub Stations will contain many capacitors, capable of storage large amounts of EU at LuV and above. Sub Stations will consume 1% of input power, but will feature many capabilities essential for the long running of your base. (Not sure what yet, but that's why we brainstorm. Please offer suggestions.)
Probably something like this - https://en.wikipedia.org/wiki/Vanadium_redox_battery

Just something I worked on tonight.
![2016-09-03_03 05 26](https://cloud.githubusercontent.com/assets/3060479/18212188/0a47eabc-7185-11e6-9598-178c42ffc285.png)

Probably holds more EU than you'd need to store.

**Comment by leagris** [comment]
If that top blocks are muffler hatches, then please consider not adding them as I see no reason  a substation should produce pollution. Certainly not 4x pollution rate of other multi-blocks structures.

**Comment by draknyte1** [comment]
It doesn't produce pollution~

**Comment by draknyte1** [comment]
@leagris, did you know most multiblocks function perfectly without a muffler? They don't check very hard.

**Comment by draknyte1** [comment]
Finished in - https://github.com/draknyte1/GTplusplus/commit/89097dc4402d73542688638e60ebcd50c21b61e6
