### ISSUE TITLE
The Enum 'Cell_Empty' has not been set to an Item at this time

### ISSUE THREAD

**Issue by FuYang001** [draknyte1/GTplusplus#204]
Game crash with newest GT++ version v1.7.0-prerelease-2
Crash report:
https://pastebin.com/stz8MT28

gregtech-5.09.32.19
IC2 2.2.827-experimental
GTNHCore included

**Comment by draknyte1** [comment]
Dunno. 
It's a GTNH issue..

**Comment by FuYang001** [comment]
Game ran again when I deteled some TFC addons.
