### ISSUE TITLE
Alloy smelter recipes seems to be brocken in GTNH Trinium Titanium Alloy

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#206]
![image](https://user-images.githubusercontent.com/2970688/35650584-e96ceed4-06dc-11e8-9dd4-490b6b71308c.png)
![image](https://user-images.githubusercontent.com/2970688/35650591-eec63c46-06dc-11e8-8f2d-20dbc8b95559.png)

Alloy smelter recipes seems to be brocken in GTNH
(newest source of gt++)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35650738-6b48e9c6-06dd-11e8-8ada-4835d64d3dda.png)
same issue here i guess

**Comment by draknyte1** [comment]
Is it just not getting the Tritium from GTNH?
I turned mine off entirely while your coremod is loaded, to try avoid conflicts.

**Comment by Dream-Master** [comment]
I will check it. Maybe name differs.

**Comment by draknyte1** [comment]
Let me know if this was fixed in https://github.com/draknyte1/GTplusplus/commit/5213ae1be67b53dc6a8622c9d2d2a9ca7f41b0f6#diff-e6a139a0c90d745190b6cb398cc950d9.

**Comment by Dream-Master** [comment]
Ok the recipes not shown anymore but recipes are missing completly. I will add some in m core mod.

**Comment by Dream-Master** [comment]
This recipe still exists in pre 6
![image](https://user-images.githubusercontent.com/2970688/36663213-1e24835e-1ae1-11e8-8e61-10e1c5db7234.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/36663258-56e0f650-1ae1-11e8-931b-d284988ae030.png)
same here

**Comment by draknyte1** [comment]
Did this ever continue happening?

I'll be happy to investigate, otherwise I'll close this issue in a week.

**Comment by Dream-Master** [comment]
will check tomorrow

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40172149-c12ac218-59cd-11e8-9f12-80504b360897.png)
tested with eraly 17 version

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40172207-f754ad68-59cd-11e8-9aca-44b64017d392.png)

**Comment by Dream-Master** [comment]
not fixed so far i can see.

**Comment by draknyte1** [comment]
Reported fixed by users in discord.

**Comment by Dream-Master** [comment]
will try with lastest source later.

**Comment by Dream-Master** [comment]
yes it is fixed
![image](https://user-images.githubusercontent.com/2970688/42840200-53f3ae94-8a06-11e8-9ef1-4af78e9ad06f.png)
