### ISSUE TITLE
[1.7.0pre3] clicking on creative search menu crashes game.

### ISSUE THREAD

**Issue by SuperCoder7979** [draknyte1/GTplusplus#207]
GT version: 32pre1
IC2 version: 828
Click on the creative search menu to crash it; it happened in singleplayer.
It is a major bug, as a misclick can crash the game.
[crash-2018-01-31_22.12.39-client.txt](https://github.com/draknyte1/GTplusplus/files/1684070/crash-2018-01-31_22.12.39-client.txt)

**Comment by draknyte1** [comment]
Issue is caused by every second mod, this is the first stack I've ever seen proving GT++ now does it too.
Anyway, should be fixed today.
