### ISSUE TITLE
Hydroxide LCR recipe causing unpleasantness [GT++ 1.6.110-prerelease]

### ISSUE THREAD

**Issue by Wolozo7** [draknyte1/GTplusplus#215]
GT 5,09,32,19
Industrialcraft-2-2.2.828a-experimental
GTNH-Pack, official server

This is nothing major, but at the moment it's not possible to do multiple recipes in a Large Chemical Reactor if they contain both Hydrogen and Oxygen, because those two make Hydroxide. I think this reaction is added by GT++?

![image](https://user-images.githubusercontent.com/34921674/36077964-48f5bfd8-0f71-11e8-92e5-be708bd95863.png)

Adding a circuit, preferably something rarely used, would fix this issue.

**Comment by draknyte1** [comment]
I don't explicitly add LCR recipes, so this is an issue for Gregtech.

**Comment by Dream-Master** [comment]
Ok maybe not your fault but gt add a way add recipe only to single blocks not to LCR.

**Comment by Dream-Master** [comment]
The LCR recipes are auto added.

**Comment by draknyte1** [comment]
Should be fixed here. https://github.com/draknyte1/GTplusplus/commit/4adca85bdf6955ac356894004b63183ee1c86a0c.
