### ISSUE TITLE
Dark World biome on the Moon

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [draknyte1/GTplusplus#216]
Playing with a test world using only GT++ (pre-4), Advanced Rocketry (1.2.5-63), and their dependencies, there are large patches of Dark World biome generating on the Moon. It doesn't appear to be an ID conflict.

**Comment by draknyte1** [comment]
Could be either a biome or dimension ID conflict..
Otherwise, I have no idea.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I meant it doesn't appear to be a biome ID conflict.

**Comment by draknyte1** [comment]
Did this ever continue happening?

I'll be happy to investigate, otherwise I'll close this issue in a week.

**Comment by bHXDgiuMa5yLHyC8** [comment]
This issue is still occurring as of GT++ 1.7.02.09 and AR 1.7.10 1.4.0-020. Also GT++ is causing water to generate all over the Moon as if it were the Toxic Everglades, which I don't think was the case before.

Is it possible for the user to disable the dark world module?

**Comment by draknyte1** [comment]
The issue exists on ARs side from my first guess, as No other mod misuses the Everglades biome. 

Did you try change the dimension or biome ID?

**Comment by bHXDgiuMa5yLHyC8** [comment]
Changing the biome ids appears to have fixed the problem for now, which puzzles me because they didn't overlap in the first place.
