### ISSUE TITLE
[Balance] Balance suggestion for Power Station

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#227]
Proposal for balancing the power station.

Keep current crafting requirements, including quad lithium cell for control block

Batteries placed in input hatch are drained, and determine capacity of multiblock

Base capacity is 1 quad lithium cell x 100 EU.  Each battery placed in input hatch increases storage capacity by battery capacity x 100.  Input hatch tier determines max battery type tier it can accept.  IE MV tier can accept MV batteries, power crystals, etc.

Alternative is to create two separate tiers for the power station, one at EV/IV which is where it makes sense to consolidate power generation into one location for storage and distribution, and one at top-level tiers.

**Comment by richardhendricks** [comment]
ok, stuffing batteries into the buses doesn't make sense, since it has a vanadium redox cell in the center.  Instead how about this?

Controller validates blocks in the center.

Vanadium redox cells -> storage is equal to 100x MV lithium batts, so 400k * 100 = 40 Meu.

Advanced vanadium redox cells -> storage is equal to 100x IV batts
Recipe is 4 redox cells + IV batt + 8x IV cable

Ultimate vanadium redox cells -> storage is equal to 100x ZPM/UV batts
Recipe is 4 advanced redox cells + ZPM/UV batt + 8x cable

Maybe other tiers too?

This way the machine is kept, but upgraded throughout its life, similar to a EBF or pyrolyse oven getting coil upgrades.

**Comment by codewarrior0** [comment]
Yeah, the only real problem with the power station is the insane energy capacity. Tiered power cells sound like the right solution. Dunno about using regular batteries directly, maybe some exotic materials might be a better choice?

Alternately, allow it to have variable height so you can keep adding more power cells before the next tier of cells opens up.
