### ISSUE TITLE
Crash with latest GT.

### ISSUE THREAD

**Issue by Pilad** [draknyte1/GTplusplus#230]
If enable :     # Restores circuits and their recipes from Pre-5.09.28 times. [default: false]
    B:enableOldGTcircuits=true
Crash: https://pastebin.com/RG2m2gyJ

**Comment by Pilad** [comment]
P.S.     # These may be overpowered, Consult a local electrician. [default: false]
    B:enableSolarGenerators=true 
Not works? Do not produce energy.

**Comment by draknyte1** [comment]
So, your issue is related to Apache Commons, libraries disturbed with minecraft or forge. I Can't fix missing method errors..

I suggest redownload if your client and modpack, so your launcher redownloads the required libraries.

**Comment by Pilad** [comment]
Reinstall MultiMC laumcher. Not works solars generators. Circuits is work. Any ideas?

**Comment by Pilad** [comment]
For circuits need commons-lang3-3.3.2 ))

**Comment by draknyte1** [comment]
Solar generators do work.. they just take forever.. 
As they use solar generator logic and require a large warm-up period.
