### ISSUE TITLE
[GTNH] underpriced bee frame 

### ISSUE THREAD

**Issue by benstuwie** [draknyte1/GTplusplus#232]
the void frame is way too cheap for gtnh. It costs some thaumium and an ender pearl, while the thing it replaces costs a dragon egg, some high tier bee products, thaum infusion tech, and a bunch of essentia. I think, considering gt++ is a tech mod, the gt++ frame should be a tech replacement for the magic void frame. To compensate for the thaum recipe, I'd suggest the gt++ one take 4 base wetware circuits (to force an assembly line requirement), as well as 4 black plutonium plates to force t7 rocket, and a dragon egg to keep some of the original point of the frame. It would be easier for players who are farther along, who want to do bees, but also want their advanced tech to assist them. It also makes the lower tier players use the indented thaum frame, which is much more balanced for MV-EV tiers.

**Comment by draknyte1** [comment]
I just don't get why it's enabled in GTNH?

It's there for when I play without Void frames.. not to exist alongside.

**Comment by Dream-Master** [comment]
i can change the recipe and make a pull request better than disable it.

**Comment by draknyte1** [comment]
But they're identical frames.. think mine is mildly better, but nothing worth keeping them enabled for. End user wouldn't notice a difference.

**Comment by draknyte1** [comment]
Resolved in https://github.com/draknyte1/GTplusplus/commit/03c82e42586171290de26b715263cf8e67200230.
