### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Rongmario** [draknyte1/GTplusplus#235]
https://pastebin.com/uFBKT0gR

**Comment by Baxterzz** [comment]
What version of GT++ Are you running?

**Comment by Rongmario** [comment]
Latest..

**Comment by draknyte1** [comment]
Follow the format or I'll close it. 

Your issue lies in vanilla code, huehuehue.

**Comment by Rongmario** [comment]
Wasn't asking you anyway, wanted to ask people who actually look at code like it is intelligible.

**Comment by draknyte1** [comment]
Should be fixed by https://github.com/draknyte1/GTplusplus/commit/5cd15b7c3218a9b655db6fde9054af88821d3878.
