### ISSUE TITLE
[GTNH]Stainless Steel available via Alloy Blastsmelter

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#236]
![image](https://user-images.githubusercontent.com/2970688/37617151-8471059c-2bb2-11e8-84e4-6dc3b4bb956f.png)

![image](https://user-images.githubusercontent.com/2970688/37617166-8dddb62a-2bb2-11e8-8d4e-eebdd83ce862.png)

GTNH 2.0.3.1 dev
GT++ lastest source from 19.03.2018

@draknyte1 please disable it no one will use an EBF anymore.
Thanks

Are there other recipes too avoiding ebf?

**Comment by draknyte1** [comment]
Yes and I'll be fixing them when back at my computer. This was discussed on discord prior to you posting this issue.
