### ISSUE TITLE
Crash with latest GT and GT++.

### ISSUE THREAD

**Issue by Pilad** [draknyte1/GTplusplus#240]
If enable : # Restores circuits and their recipes from Pre-5.09.28 times. [default: false]
B:enableOldGTcircuits=true
    # Adds custom circuits to expand past the Master Tier. Only really recommended to enable if enableOldGTcircuits is enabled. [default: false]
    B:enableCustomCircuits=true
https://pastebin.com/NUDqBz8f

**Comment by draknyte1** [comment]
Nothing has changed in months regarding this code.. I guess I'll take a look?

**Comment by Pilad** [comment]
This option did not seem to be in the 8 build.
# Adds custom circuits to expand past the Master Tier. Only really recommended to enable if enableOldGTcircuits is enabled. [default: false]
B:enableCustomCircuits=true

**Comment by leagris** [comment]
Ping!

**Comment by draknyte1** [comment]
So, I have sent the fix to @leagris and when she submits it via PR, this shall be resolved.
The issue was actually a lot simpler than I ever thought.
