### ISSUE TITLE
can not start tree farm

### ISSUE THREAD

**Issue by ptk2003** [draknyte1/GTplusplus#245]
Hi.
I can not start working tree farm.

15x15, maintenance, output bus, energy hatch, controller,
input hatch, input bus, all MV tier.
In controller saw is steel.
In input hatch liquid fertiliser, in bus oak saplings.
Farm charging at 3244800 and nothing do.

https://i.imgur.com/rMD1swC.png
https://i.imgur.com/T5aPOa8.png
https://i.imgur.com/Ir0zIB2.png
https://i.imgur.com/OVjPfAD.png
https://i.imgur.com/4ehN6XM.png

What i did wrong?
May be incompatible gt or ic2 version?

GT-PlusPlus-1.7.0-prerelease-10-final
gregtech-5.09.31
industrialcraft-2-2.2.827-experimental
ic2/EJML-core-0.26 auto download

I try other GT++ ver, but same result.

**Comment by draknyte1** [comment]
It doesn't work at all and is undergoing a rewrite code wise. Apologies.
