### ISSUE TITLE
ME Fluid Terminal  Fluid Cell Handling

### ISSUE THREAD

**Issue by Wolozo7** [draknyte1/GTplusplus#246]
GT++ V10, GT 5,09,32,20

I think the recent version broke something with the ME Fluid Terminal. I can't fill Empty Cells with any fluids. Emptying filled cells works fine as well as filling the Universal Fluid Cells. Tested with V8 and 10, no other changes.

**Comment by codewarrior0** [comment]
I've been seeing this too. I thought it was happening randomly on each game restart, but it might actually have something to do with mod load order since I tend to only restart the game after rebuilding one of the mods from source.

**Comment by codewarrior0** [comment]
This might be caused by Thaumic Tinkerer embedding an old version of the AE2 API, and any changes to the mod set are affecting the mod load order (or rather, the API search order) and causing Forge to load the old AE2 API instead of the correct one from AE2 itself.

**Comment by draknyte1** [comment]
I don't see how I can have this issue raised here. 
I don't touch core mechanics of anything but forge.

**Comment by codewarrior0** [comment]
Yeah I'm fairly sure it's this version of TT that's at fault.

https://github.com/GTNewHorizons/NewHorizons/issues/2775
