### ISSUE TITLE
Industrial Extrusion Machine Typo

### ISSUE THREAD

**Issue by Despote00** [draknyte1/GTplusplus#248]
The mouse-over text giving general information on where to put differents hatches/busses for the Industrial Extrusion Machine state that the Muffler Hatch goes to the back center. It's actually the Maintenance Hatch that goes there.

Peace! ^.^

**Comment by draknyte1** [comment]
This has been fixed at some point, so if it's not currently visible in the latest release, it will be in the next. :)
