### ISSUE TITLE
[1.4.9-dev GT++] Void Metal Pipe?

### ISSUE THREAD

**Issue by Ldmf** [draknyte1/GTplusplus#25]
![2016-10-20_13 53 24](https://cloud.githubusercontent.com/assets/15316448/19558784/abbd8a98-96cc-11e6-96c9-9ed8cc015395.png)

Mavy i fund mor things :)

1.4.9-dev GT++
gregtech-5.09.25

**Comment by draknyte1** [comment]
Do you have thaumcraft installed?

**Comment by Ldmf** [comment]
yes i have 

Thaumcraft-1.7.10-4.2.3.5 + addons

**Comment by draknyte1** [comment]
Fixed - https://github.com/draknyte1/GTplusplus/commit/a270a0901863873c5b8a134290428304141df818

**Comment by Ldmf** [comment]
thx 4 the fix :)

and nice mod btw

**Comment by draknyte1** [comment]
I renamed Void metal a few weeks ago back to just Void (The default oredictionary name)
Forgot to change the pipe code.

Thanks for using it :D

**Comment by Ldmf** [comment]
Np i linke you mod so i will help you if i can :)

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/releases/tag/v1.4.9-dev-3 - Has this and other fixes.

**Comment by Ldmf** [comment]
thx 4 the fast dev 3 version :)

**Comment by draknyte1** [comment]
I've fixed a heap of bugs in the past day, thanks to people reporting them. Should be able to release a stable version of 1.4.9 tomorrow or the day after now. 👍🏻
