### ISSUE TITLE
Ores from the Toxic Evergardens do not show up on the Electric Prospectors Scanner

### ISSUE THREAD

**Issue by bartimaeusnek** [draknyte1/GTplusplus#250]
If this has to be fixed on GT-NH side ill make an issure about it there.

Gregtech and IC2 version: 
GT-NH 2.0.3.0 ones
Describe what you were doing when the issue happened. 
Was in Toxic Evergardens, tried to look up some of your ores, couldnt find any with the Electric Prospectors Scanner 
Can you make it happen again?
yes.
Was it single-player or on a server?
Creative Single Player
Is this issue major?
No
GT++ Version as of state of this commit: ffb1b25e67fbb90500f90df3e5704287f1342cb2
Version of the ScannerMod: https://github.com/GTNewHorizons/DetravScannerMod

**Comment by draknyte1** [comment]
Lemme have a gander what the ScannerMod looks for.. My ores are not GT OreTiles, they are just blocks. This is probably the issue?

**Comment by bartimaeusnek** [comment]
yepp i think so.
BTW: Greg made them as TE's so they dont show up on XRAY-Texture Packs.

**Comment by draknyte1** [comment]
Yeah but that doesn't work at all. 
As someone who has used all forms of 1.7.10 X-ray, I can verify. 

Just Greg over complicating things for the sake of it.

**Comment by bartimaeusnek** [comment]
Well ive tried to fix this with an extra if, but as it seems it iterates over the Gregtech Material List here:
https://github.com/GTNewHorizons/DetravScannerMod/blob/master/src/main/java/com/detrav/net/DetravProPickPacket00.java#L137. 

i've added some more code that might fix this, but I cant test right now. will msg you in dc later

**Comment by draknyte1** [comment]
Fixed by https://github.com/GTNewHorizons/DetravScannerMod/pull/6.
