### ISSUE TITLE
Zhuhai cosmetic bug

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [draknyte1/GTplusplus#251]
There is a cosmetic issue where it will leave flowing miscolored blocks of ic2 distilled water along the edges (appears with just GT++ 1.7.0 pre 10 and dependencies, github won't let me upload a screenshot.).

**Comment by draknyte1** [comment]
Can you check and see if this only happens when N/S or E/W or possibly if it happens regardless of direction the controller is facing.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Orientation doesn't seem to matter but I keep seeing "incomplete structure" errors that are getting in the way of testing.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I tried building them in all four cardinal directions within chunk boundaries a couple times, and some of them display "incomplete structure" for no apparent reason.

**Comment by draknyte1** [comment]
Thank you for your testing, I'll be sure to fix this as a top priority once I'm home. Also have to prioritise fixing the Thermal Boiler as well.
