### ISSUE TITLE
Sub-station external casings more expensive with assembler

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#254]
2.0.3.0 GTNH

Substation casing makes 2 by hand
![2018-04-13_22 24 30](https://user-images.githubusercontent.com/1214811/38763820-73f37b44-3f69-11e8-81fd-3fdfb5c19a9a.png)

However, assembler only makes 1 for the same number of raw mats
![2018-04-13_22 25 08](https://user-images.githubusercontent.com/1214811/38763823-85cbc92a-3f69-11e8-9292-814f6b067067.png)

Recommend changing assembler to output 2 or 4?

**Comment by Dream-Master** [comment]
No better reduce shaped crafting to one.

**Comment by Dream-Master** [comment]
Thanks
