### ISSUE TITLE
power substation NC2 display needs maintenance status

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#255]
Current power station Nuclear Control 2 Information Panel information doesn't include maintenance status.

![2018-04-13_23 57 37](https://user-images.githubusercontent.com/1214811/38764530-8419bbde-3f76-11e8-8f66-e375b83b7477.png)

**Comment by Technus** [comment]
Basagna.
![image](https://user-images.githubusercontent.com/4737429/38777516-909b4696-40a9-11e8-9c04-febf36f8d1f4.png)

**Comment by Technus** [comment]
it is GT problem

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7971edd3771ea2e0687e65151fb9b3bca90d2609

**Comment by draknyte1** [comment]
I'll just close this one then, lel.

**Comment by richardhendricks** [comment]
I don't understand how this is a "GT" problem.  I am specifically talking about the *power station* maintenance state.  It is a multiblock, it can need maintenance, and when it does, it wastes extra power.

![image](https://user-images.githubusercontent.com/1214811/38823505-255ba588-416c-11e8-9c55-e0c9cc4ccf80.png)

When I did maintenance on the Power Station, its running costs dropped to 102 EU/t.

```		return new String[]{
				"Ergon Energy - District Sub-Station",
				"Stored EU:" + storedEnergyText,
				"Capacity: " + EnumChatFormatting.YELLOW + GT_Utility.formatNumbers(this.maxEUStore()) + EnumChatFormatting.RESET,
				"Running Costs: " + EnumChatFormatting.RED + GT_Utility.formatNumbers(this.computeEnergyTax()) + EnumChatFormatting.RESET + " EU/t",
				"Controller Mode: " + mode,
				"Stats for Nerds",
				"Total Input: " + EnumChatFormatting.BLUE + GT_Utility.formatNumbers(this.mTotalEnergyAdded) + EnumChatFormatting.RESET + " EU",
				"Total Output: " + EnumChatFormatting.GOLD + GT_Utility.formatNumbers(this.mTotalEnergyConsumed) + EnumChatFormatting.RESET + " EU",
				"Total Costs: " + EnumChatFormatting.RED + GT_Utility.formatNumbers(this.mTotalEnergyLost) + EnumChatFormatting.RESET + " EU",

				"Total Time Since Built: ",
				""+weeks+" Weeks.",
				""+days+" Days.",
				""+hours+" Hours.",
				""+minutes+" Minutes.",
				""+second+" Seconds.",
				"Total Time in ticks: "+this.mTotalRunTime
		};``

**Comment by mitchej123** [comment]
Gregtech, specifically  it's implementation for nuclear info, only looks at the first 8 strings returned from getInfo.  The fix from tec will have it read all of them.


The debug scanner uses the same getinfo but uses all of the strings returned.

**Comment by richardhendricks** [comment]
Sure, I get that, but the problem is that the power station scan info doesn't return maintenance status. 🗡
