### ISSUE TITLE
Electrolyzer allow internal cell to fluid conversion

### ISSUE THREAD

**Issue by tomasbrod** [draknyte1/GTplusplus#256]
Because small electrolyzers had only one fluid input and output, their recipes use cells if multiple fluid inputs or outputs are needed. What I request, is this Cell I/O to be converted to fluids internally, same as Large chemical reactor does.
I understand that there might be complications with recipe lookup, because which fluid to convert to cell, but I just want to make this feature request.

**Comment by draknyte1** [comment]
The LCR intentionally is better to give reason to make it?

**Comment by draknyte1** [comment]
I guess I could do it for the centrifuge and electrolyzer.

**Comment by draknyte1** [comment]
Done in https://github.com/draknyte1/GTplusplus/commit/6a86f38e4eb166eb12763b1ba1428071420663d6.
