### ISSUE TITLE
[1.4.9-dev-3][Question] Output for EnderIO Alloy Smelter is very wrong.

### ISSUE THREAD

**Issue by Ldmf** [draknyte1/GTplusplus#26]
![2016-10-20_15 25 39](https://cloud.githubusercontent.com/assets/15316448/19561608/a9334008-96d9-11e6-832d-ae758ce63553.png)
![2016-10-20_15 25 47](https://cloud.githubusercontent.com/assets/15316448/19561611/a94dc45a-96d9-11e6-8d5b-13997574d3b2.png)

GT++ 1.4.9-dev-3
gregtech-5.09.25
EnderIO-1.7.10-2.3.0.429_beta

maby not you error or only a info with the ingot?

**Comment by draknyte1** [comment]
Not sure why the alloy smelter recipes return silly results. Needs some more examination.

**Comment by draknyte1** [comment]
@blood-asp does gregtech add enderio recipes for anything via the alloy smelter?

**Comment by Ldmf** [comment]
It is a NEI's glitch (show glitch)
![2016-10-20_15 35 38](https://cloud.githubusercontent.com/assets/15316448/19561967/e14bb938-96da-11e6-83df-3a4e5433e99c.png)

**Comment by draknyte1** [comment]
Oh, so it doesn't output strange amounts? Very weird.

**Comment by Ldmf** [comment]
yes it only ouputs one ingot

**Comment by draknyte1** [comment]
Well, probably won't fix it if it's just one material :) 
Not major at all if that's truly the case!

**Comment by Ldmf** [comment]
yes only that one

Blutonium Plate shows the rigth recept 

Only void show the rong one
