### ISSUE TITLE
Crash when B:enableOldGTcircuits=true

### ISSUE THREAD

**Issue by leagris** [draknyte1/GTplusplus#262]
##### Description

Enabling Old GT Circuits patch, causes GT++ to crash:

##### Versions

- Minecraft Forge 10.13.4.1614
- GT-PlusPlus-1.7.0-prerelease-10-final
- gregtech-5.09.32pre4

##### Specific configuration

`GTplusplus.cfg`
```cfg
    # Restores circuits and their recipes from Pre-5.09.28 times. [default: false]
    B:enableOldGTcircuits=true

```

##### Crash reporting
Crash log here: [crash-2018-05-03_10.44.35-server.txt](https://gist.github.com/leagris/e9878b5b37ac04ddc8d900ea8e3de45c)
```
java.lang.IllegalAccessError: The Enum 'Old_Circuit_Primitive' has not been set to an Item at this time!
        at gtPlusPlus.xmod.gregtech.api.enums.GregtechItemList.get(GregtechItemList.java:387) ~[GregtechItemList.class:?]
```

**Comment by Pilad** [comment]
https://github.com/draknyte1/GTplusplus/issues/240
