### ISSUE TITLE
Suggestion : reduce the batch size of the FFPP and add a substitution for hydrofluoric acid

### ISSUE THREAD

**Issue by mergendil** [draknyte1/GTplusplus#268]
As of now we need, for the lithium fluoride only,  
1986 apatite dust for the U235 salt recipe
2239 apatite dust for the Thorium salt recipe
2348 apatite dust for the zirconium salt recipe

I suggest using the gregtech hydrofluoric acid instead, which can be made from pure H and F.

**Comment by NyaDeveloper** [comment]
Might I add that the chemical dehydrator recipe (37 fluorite+16 cells+8064 sulfuric acid) gives you 16 industrial strength HF acid, which
is way more than the sulfuric apatite path. And fluorite comes from mining limestone, and it relatively easy to get some.

While reducing the batch size might be interesting (or just adding a smaller size one should somebody wants it), there's this path I mentioned too.
