### ISSUE TITLE
[GTNH Only] Old Void Frames don't shapeless craft into Oblivion Frames 

### ISSUE THREAD

**Issue by Kortako** [draknyte1/GTplusplus#279]
In the version of GT++ distributed with GTNH update 2.0.4.0 (prerelease-11-final), the Void Frame was removed and it looks like there is supposed to be a shapeless craft recipe to turn any of these new "useless" frames into Oblivion frames, as seen here:

https://github.com/draknyte1/GTplusplus/blob/a580c9245097b5bddcfbab0d49d7667aec836b93/src/Java/gtPlusPlus/xmod/forestry/bees/recipe/FR_Gregtech_Recipes.java#L67

However, in game, this doesn't actually work.  Going into NEI and pressing U only shows the normal research recipe, and putting a useless frame into a crafting grid yields no results.  Anything I'm doing wrong?

**Comment by draknyte1** [comment]
Either magic bees isn't loaded or there's a script to remove the recipe in the script folder. 
This recipe works fine in my older GTNH instance.

**Comment by draknyte1** [comment]
Wonder if that's from the addition of @bartimaeusnek's new frames.
Odd.

**Comment by bartimaeusnek** [comment]
The Recipe will get overwritten by the magic bees script.
Also i dont think my addition should change the old void frames...

**Comment by draknyte1** [comment]
Speaking of frames, the red frames you add have no vanilla recipe. I noticed there is one in GTNH though :p

**Comment by bartimaeusnek** [comment]
so i guess ill rework this recipe:
https://github.com/draknyte1/GTplusplus/blob/4e5ee5845b872b09ba95dbcdaacbf7f9fbe0d699/src/Java/gtPlusPlus/xmod/forestry/bees/recipe/FR_Gregtech_Recipes.java#L110

note to myself

**Comment by draknyte1** [comment]
It's actually pointless because void frames don't even exist and any that did vanished due to the registered name changing. (Oversight on my behalf)
