### ISSUE TITLE
Growthcraft related crash possibly caused by GT++

### ISSUE THREAD

**Issue by walkerjonny** [draknyte1/GTplusplus#28]
Hi, 
I got that crash as I tried to add your mod to my mod folder.
There seems to be an issue with the latest Growthcraft Community Edition mod.
Also it looks like it is caused by GT++.
http://pastebin.com/CHWZBuXK.
You can get Growthcraft Community Edition there:
https://mods.curse.com/mc-mods/minecraft/235092-growthcraft-community-edition#t1:other-downloads.

**Comment by draknyte1** [comment]
I'm aware where to get Growthcraft as I add compatibility for a few things. I'll update the code on my end, thanks for letting me know.

**Comment by draknyte1** [comment]
Fixed here, Tested against 2.4 and 2.5. - https://github.com/draknyte1/GTplusplus/commit/9b74f85667bfe3c3574b392914f8c53ced0be0c9#diff-817932fa2d7dba2f07d5d47f4f0326b1R122
