### ISSUE TITLE
[GTNH] Alkalus Error Ingots

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#280]
Find a few Alkalus Error Ingots in recipes.

Tested in GTNH 2.0.4.1 Dev version with GT pre17 (lastest source)

https://media.discordapp.net/attachments/220804408273797121/448181675252383744/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448181845985853450/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448181939745062912/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448181974998188032/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448182014005346334/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448182093198131200/unknown.png
https://cdn.discordapp.com/attachments/220804408273797121/448182527350407168/unknown.png

**Comment by draknyte1** [comment]
Only the Industrial machines still have error ingot recipes, which are input. (So uncraftable recipe)
For now I'll leave this open until I figure those out.
