### ISSUE TITLE
(1.7.10) crashes when i install the latest gt plus 

### ISSUE THREAD

**Issue by Dwarfy-Dwarftins** [draknyte1/GTplusplus#287]
# Issue Title  
 Provide a general summary of the issue in the Title above, 
 Something descriptive and related to the issue + Mod Version in [].
 Example `Custom GT++ Alveary Frame Blocks do not work [v1.5.0-alpha]`

## Expected Behavior
 If you're describing a bug, tell us what you expect should happen.   
 If you're suggesting a change/improvement, tell us how it should/could work.  

## Current Behavior
when put into mod folder it loads up gaame but right before main menu it crashes
## Possible Solution
 possible incompatiblity to the newest version oof ic2?

## Context
I just think the mod is really cool and im not sure if its an incapability with another mod or if im missing anything else or if the mod needs to be the same update as another mod i have the gregtech latest update and this mods latests update

If not using a modpack:
 * Mod List -  i have a decent mod list but i can list key things like thaumcraft, ic2, buildcraft, twiliightforest. zettaindustires, and mekanism if any of those are to blame possibly? 

Also include:
 * Gregtech version: prerelease 20 hot fix/ latest
 * IC2 version:1.2.1.6
 * Java version:8
 * Operating System:windows 10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x ]    Single Player?
Im sorry for last post and i hope this is more right. i tired filling out what i can provide

**Comment by draknyte1** [comment]
Please contact me on Discord if you would like the dev. copy with this fixed.
Issue regrading IC2C #286 & #287 should be resolved by https://github.com/draknyte1/GTplusplus/commit/76f83ec95d249c8fb1c0e24dfb33662a8c5bd0c6.

**Comment by draknyte1** [comment]
If this is not fixed with the updated version I provide, I will be happy to try resolve this issue further.
Link to Discord:  https://discord.gg/YdXJbgb
