### ISSUE TITLE
GT Extruder consumes rod molds when making GT++ rods.

### ISSUE THREAD

**Issue by PaulMadsen** [draknyte1/GTplusplus#29]
Have tested using a HV extruder with Tantalloy-60 and Tumbaga.

**Comment by leagris** [comment]
@draknyte1 When registering a recipe with a mold, shape or circuit to not be consumed, the stack size of the item to keep must be set to 0.

**Comment by draknyte1** [comment]
Already Fixed - https://github.com/draknyte1/GTplusplus/blob/71d77f859e1e75b79ead43d8c4b8e1d14a8247f4/src/Java/gtPlusPlus/xmod/gregtech/loaders/RecipeGen_Extruder.java
