### ISSUE TITLE
Can't input noble gases in the input hatch. Noble gases cell-less recipe doesn't process in the large centrifuge [v1.7.1]

### ISSUE THREAD

**Issue by mergendil** [draknyte1/GTplusplus#292]
## Expected Behavior
Input noble gases as a fluid in the input hatch of a large centrifuge equiped with 4 output hatches, get co2, helium, methane and deuterium back.

![sans titre](https://user-images.githubusercontent.com/19917766/40789392-978e94cc-64f2-11e8-9f9c-5f771799c1e0.png)

## Current Behavior

1. Can't input noble gases in the input hatch. If you put cells in the slot, the cell doesnt unload. If you try to input it as a fluid, it doesn't get inside the hatch.

I had a batch of noble gases trying to get into the hatch for days and they finally got in somehow. It's a server and i wans't there when it happened, but I can't get more that what's already inside

![sans titre2](https://user-images.githubusercontent.com/19917766/40789445-b7a8eaaa-64f2-11e8-920e-50ff5e0ec3a6.png)

However it shows the 2nd issue : 

2. Even with noble gases inside the input hatch, the large centrifuge won't process it.

## Context
getting the helium without additionnal infrastructure 

## Game Environment

 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Should be fixed in latest releases of GT++.
