### ISSUE TITLE
Several cell-less recipe doesn't process in the large electrolyser [1.7.1]

### ISSUE THREAD

**Issue by mergendil** [draknyte1/GTplusplus#293]
## Expected Behavior
![gt](https://user-images.githubusercontent.com/19917766/40789781-8aec82d2-64f3-11e8-996d-24baad83e49e.PNG)
Input bauxite in the input bus, recipe should gets processed.
The same recipe with cells works well.

## Current Behavior
The recipe below is not getting processed in the industrial electrolyser

I'm guessing the recipes specific to the large electrolyser aren't working too (the ones that doesn't use cells)
Bug confirmed with Biotite as well

## Game Environment

 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Should be fixed in latest releases of GT++.
