### ISSUE TITLE
AlloyBS Crash while inserting nuclear card into monitor

### ISSUE THREAD

**Issue by bashduude** [draknyte1/GTplusplus#294]
## Steps to Reproduce (for bugs)
 1. running alloy blast smelter at 512 while cooking 1\4 of the titan trying to link the card from nuclear control and put it into advanced monitor causes crash

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  gtnh
 * Version used:2042
 * Download Link if possible:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

jeeez . kinda boring to fill all of those lmao
there is crash pastebin

https://pastebin.com/QPDRfa2K

**Comment by draknyte1** [comment]
I deal with too many dickheads, so I sorta have to ask all these questions. Means I'll close anything that doesn't follow my format, as I don't want to dig through crashlogs to find mod versions and shit. 

Will investigate when I'm home from holidays in two weeks. Tbh I don't directly support nuclear control at all.

**Comment by bashduude** [comment]
Yeah i was thinking to create an issue on gtnh, but some1 recommended me to left it there. =)

**Comment by Dream-Master** [comment]
I will look if we can change somethings in gt coce. @bashduude

**Comment by richardhendricks** [comment]
Same issue with me on the Power Sub Station.  I'll have to rollback my instance and remove the sensor card for now.

**Comment by richardhendricks** [comment]
Fixed with Bart's branch above.
