### ISSUE TITLE
Tungsten Carbit doesnt need to be smelted in EBF, can be done with arc furnace and the Cell 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [draknyte1/GTplusplus#295]
Which modpack version are you using?
2.0.3.0 Greg Tech New Horizons

If in multiplayer; On which server does this happen?
Private

You can put Tungsten Carbite dust from gt++ into a cell, if you smelt this cell in the arc furnace, you will recive the two tin for the cell and the Tungsten Carbite in INGOT form, so you dont need to smelt it in the EBF.

![2018-06-02_20 28 51](https://user-images.githubusercontent.com/29660362/40881596-0cc6c348-66cb-11e8-92e5-a281c1d551b1.png)
![2018-06-02_20 28 58](https://user-images.githubusercontent.com/29660362/40881597-0ce3e3ec-66cb-11e8-95bc-16c42981ea44.png)
![2018-06-02_20 29 11](https://user-images.githubusercontent.com/29660362/40881598-0d0060b2-66cb-11e8-8c1e-764c6fbc4e56.png)

Suggestion
Change the arc furnace recipe to get back only the tungsten carbite dust, not the ingot

**Comment by draknyte1** [comment]
Two things.

1) Arc furnace recipes are generated automatically by GT, along with the canning recipe. Can't change either. 

2) unless you're using GT 5.07/5.08, you cannot get GT++ Tungsten Carbide. Gregtech adds it from 5.09 and if that's the case GT++ won't even try.
