### ISSUE TITLE
PRs with GT5U

### ISSUE THREAD

**Issue by Muramasa-** [draknyte1/GTplusplus#3]
Things like the Energy Buffers and Industrial Coke Oven would make really nice additions on Blood's fork.

Have you thought about submitting PRs?

**Comment by draknyte1** [comment]
I have, but decided keeping it as a separate mod is a better idea,
Between GT5.08, GT5.09 and my own Fork, I can maintain cross compat with all 3.

**Comment by draknyte1** [comment]
Give me some time to think about a way for modular addition.
If we added it to the master branch, worlds with my mod in them would have a double of entities.

We'll have to check against particular entities already existing, since just adding them with the same ID's will cause a load failure.

**Comment by draknyte1** [comment]
@Muramasa- what's your best form of contact?

**Comment by Muramasa-** [comment]
@ me on here or PM me on the IC2 forums (Muramasa on there). I get email notifications via both.

**Comment by draknyte1** [comment]
Probably pm you then, Would make a discussion easier.. Unless you wanted to join me for a chat on IRC?

I'm in #gregtech and #gt-dev on Epsernet 24/7

**Comment by Muramasa-** [comment]
Sure, I'm on the IRC now (Name is Muramasa).

**Comment by draknyte1** [comment]
So, I spoke with @OneEyeMaker, His latest PR adds a new black casing class, so If that's accepted I'll use that to integrate the Coke Oven. 

If I add in the Power Buffers or the Coke Oven, I'd like them to Check for the presence of my own mod first and not add them if it's present. This makes compatibility easiest as there are many worlds with these already in them. No point re-adding content already generated by GT++ (My mod)

**Comment by Muramasa-** [comment]
Yep, that seems like the best idea to keep compatibility with all versions.

So I seen you talking on IRC about how @Bogdan-g has made some really nice performance improvements. It would be really nice to have that as well. (When ever you guys get around to it of course.)

**Comment by draknyte1** [comment]
> It would be really nice to have that as well. (When ever you guys get around to it of course.)

That's more of something to ask him, being Russian and some kind of pro Java programmer, most of his commits make little sense. If you look at his Repo, you can see the optimizations he's going for and I doubt he has much interest making any PRs, considering his fork has been separated to it's own branch.

**Comment by Muramasa-** [comment]
Ah ok I see. May I ask when you next talk to him to see if its ok that I commit his improvements to the master branch on his behalf?

**Comment by draknyte1** [comment]
I assume you can just fork his repo, There's quite a few things he hasn't implemented from Experimental so it me be easy to work that way instead of the other. I am lacking a way to translate his comments into any decent readable form so I couldn't tell you from memory what is missing sorry. (Dammit Google and other translator tools)

**Comment by Bogdan-G** [comment]
:hamster:

**Comment by Muramasa-** [comment]
Hello @Bogdan-G!

Can I Pull Request https://github.com/Bogdan-G/GT5-Unofficial/commit/9d05c4844aeab4c07d6e37923507d245349f8dcd to https://github.com/Blood-Asp/GT5-Unofficial and other performance improvements?

**Comment by Bogdan-G** [comment]
@Muramasa- yes, my changes base on GT5U license(or LGPL). If you have questions about my changes, then you ask.

PS hmm will be necessary to register in the repo which license is used to avoid confusion.
