### ISSUE TITLE
[v1.7.1] Zombie pathfinding crash involving gt++ ore

### ISSUE THREAD

**Issue by Creeperologist** [draknyte1/GTplusplus#301]
## Expected Behavior
the ore not to crash the game on path finding

## Current Behavior
crashes on zombie path finding, triggering some function inside of a gt++ ore which results in a crash

## Context
the problem continues to crash the server, each time the server starts back on again it stays up for awhile however the problem does continue to repeat itself

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  Infinitech 2: Fear the Night
 * Version used: .81 ( test version of pack )
 * Download Link if possible: https://www.dropbox.com/sh/37szeajszqxpk66/AAB4P0R-SeYuNmaQjG0WjO03a?dl=0

Also include:
 * Gregtech version: 5.09.32pre4
 * IC2 version: 2.2.2.827 experimenal
 * Java version: 1.8.0_141
 * Operating System: Linux

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

Crash Log: 
[crash-2018-06-08_23.09.33-server.txt](https://github.com/draknyte1/GTplusplus/files/2086983/crash-2018-06-08_23.09.33-server.txt)

**Comment by draknyte1** [comment]
I'll investigate when I'm home next week. Can't really tell from the crash log what's the issue due to the obfuscated function name. Sorry.
