### ISSUE TITLE
No Containment Frame recipe showing in GTNH

### ISSUE THREAD

**Issue by kris449** [draknyte1/GTplusplus#304]
## Expected Behavior
I expect to see the recipe as shown in your wiki.

![image](https://user-images.githubusercontent.com/26042867/41209377-2590cc46-6cf9-11e8-8b4e-8b4f5e8b5d68.png)

## Current Behavior
 No recipe shows up when selecting the item in NEI.

## Steps to Reproduce (for bugs)
 1. Play GTNH
 2. Try to search for the recipe
 3. Fail to find recipe

## Game Environment
 * Modpack Name:  GTNH
 * Version used: 2.0.4.2

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
It _does_ exist (After much debugging) however you cannot see the recipe by clicking the block.
Try view the results of the inputs and it will show up on one of the last pages of shaped crafting (Just check soldering iron uses), this is my only workaround until I can figure out why several blocks refuse to show in NEI.
