### ISSUE TITLE
Large Processing Factory (Suggestion)

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#306]
Suggestion

The Large Processing Factory does:
Compressor
Lathe
Polariser
Extractor
Fermenter
**Distillery**

I'm not sure why it would have Distillery as that is already covered with the Distillation Tower.

It could be better to have **Fluid Extractor** instead of **Distillery** in this multiblock? Also the recipe could be updated to have Fluid Extractor as one of the requirements.

/Highbeam

**Comment by tranceplanet** [comment]
Also a question about the fermenter - do I put the circuit 20 inside the fluid input hatch?

**Comment by tranceplanet** [comment]
Also note
Mode A is called Metalwork.  Mode B is called **Fluid Work** where the Extractor is located.  Does that mean its already a fluid extractor?

**Comment by Prewf** [comment]
In the latest gt++ it should be enabled, the manual wasn't updated though. 
It is:
Laser Engraver (20)
Autoclave (21)
Matter Replicator (22) <-- this one's disabled

**Comment by tranceplanet** [comment]
Ok.  Second suggestion for Mode C)

Remove **Matter Replicator** and replace with **Cutting Machine**.  Assuming both the laser engraver and cutting machine need to be in the cleanroom to work then it'll be quite handy to have both in 1 multiblock with the ability to have multiple laser engraver inputs.

I noticed Mode C appears to be having bugs and reverting to Mode A after reset:  #296 

I'll test that once I have a machine up.

**Comment by Prewf** [comment]
GT++ has one already, it's called the Cutting Factory

**Comment by draknyte1** [comment]
You're aware no multiblocks have clean room or low gravity requires?

The Processing Array and all GT++ multis ignore these special requires. 

The replicator mode will not be changed, it's currently buggy and is disabled until I revise its code. It doesn't use the same code as the other 8 modes, so it had to be rewritten from scratch to imitate the single block in a parallel fashion.

**Comment by Prewf** [comment]
Of "useful" machines that we lack multiblocks for, they are:
-Chemical Bath
-Assembler (the autoassembler right now is broken and doesn't have inherent speed boosts/parallel processing; alk's workin on this one i think)
-Circuit assembler (i think alk said he's not ever gonna do this one)
-Fluid extractor
-Mixer
-Fluid solidifer
-Forge hammer
-Fluid canner/canner

Honestly we probably don't need the last like 5 things but hey I love these multi's I'm not gonna complain if he ever decides to do em

**Comment by Prewf** [comment]
..

**Comment by Prewf** [comment]
I feel like fluid extracting is not as worth it to have for this multiblock. It's already pretty fast to extract fluids from things...

Sorry I know you already committed the change to do the fluid extractor, but what about making it a fluid solidifer instead? Turning molten plastics into sheets (or ingots, or BOTH because this multiblock allows that) at a very fast rate sounds pretty worth it. Fluid solidifier is pretty useful at all stages of the game for stuff like hardening plastics and gelling toluene.

**Comment by draknyte1** [comment]
I'll re-open this and come back to it.

**Comment by Prewf** [comment]
Actually now that i think about it, i'm not sure how you'd go about making the fluid solidifier use a mold in input bus A for a liquid in input bus B, if we have multiple input buses and multiple input hatches...seems 
very difficult to do..

**Comment by Logicus123** [comment]
The autoclave is not working; it stops after a while and eating the ressources; i have enough energy, still doesnt finish its processing

**Comment by Prewf** [comment]
What recipe did you try to do, what was in the input buses and hatches? What tier was the machine in and how much energy did you give it?

**Comment by Logicus123** [comment]
Okay now it worked, just needed an muffler hatch, wasnt there in the discription

**Comment by Prewf** [comment]
@draknyte1 actually, instead of an alloy smelter (which would be useful in its own right), what about a forming press?

Or perhaps a forming press could be a screwdrivered mode for the material press. And replacing fluid extractor with an alloy smelter in the multimachine?

**Comment by Prewf** [comment]
I guess another bad thing about doing a fluid solidifier (and fluid extraction right now) is that the recipe times are ulv recipes that are < 1 second typically, which means that the gt++ algorithm will ignore most (if not all) of the gt++ overclock and the final gt overclocks.

**Comment by Highbeam** [comment]
Material Press (screwdriver mode) doing the Forming Press is a great idea!

Multiple hatches for the different inscriber presses

**Comment by draknyte1** [comment]
At some point i added forming press capabilities to the Material Press Multi. Gonna close this for now unless the Multi-Machine requires review.
