### ISSUE TITLE
ExU Ender Quarry fix

### ISSUE THREAD

**Issue by Prewf** [draknyte1/GTplusplus#308]
# ExU Ender Quarry fix
As requested in #help, this is a ticket for fixing the ender quarry 64x64 block limit.

## Expected Behavior
I'm not sure what changed but instead of 64x64 chunks, it limits the user to 64x64 blocks?

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Place an ender marker more than 64 blocks in x and z directions
 2. Plop down an ender quarry and it says it cant be beyond 64x64

# Context
I think I understand what happened here. We were using an older version of Extra Utilities before 2.0.4.4. At some point in 2016, someone suggested this https://github.com/sameer/ExtraUtilities/issues/1. That commit limits the area to a 64x64 block area and it was coded literally into the source, not using config values like the person in the issue suggested. I guess the latest version of extra utilities was pulled into 2.0.4.4 of new horizons.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GT: new horizons
 * Version used: 2.0.4.4

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by Prewf** [comment]
@draknyte1 sorry was sleeping when u pm'ed me. here's the ticket u wanted ty mr alk

**Comment by Prewf** [comment]
this was fixed i think

**Comment by Dream-Master** [comment]
yes we fix it.
