### ISSUE TITLE
Rocket Engine changes

### ISSUE THREAD

**Issue by Prewf** [draknyte1/GTplusplus#311]
# Rocket Engine changes
There was a discussion on the new horizons github a few weeks ago, but @draknyte1 might've been on vacation. I just thought I'd put a ticket here, the changes shouldn't be that hard to implement. The reasoning behind it is that the rocket engine is better or almost as good as a Large Combustion Engine. The original suggestion was to remove it altogether, but I like players to have the freedom to do things differently if they want to. If they want to use a rocket engine, let them, but we need to make the rocket engine less efficient than the LCE otherwise the LCE has no point in existing.

The suggested changes are here https://github.com/GTNewHorizons/NewHorizons/issues/3048, but I'll post them here for you:
>There's an alternative solution, which is to make the efficiency consistent with the existing single block combustion engines. Since it's decreasing linearly, the GT++ blocks would need:
>
>80% fuel efficiency at EV with 320 pollution per second.
>75% fuel efficiency at IV with 640 pollution per second.
>70% fuel efficiency at LuV with 1080 pollution per second.
>
>The fuel values of existing combustible fuels already acts as a sort of gating. Unless a player has ridiculous amounts of cetane generation (requires 72 L/s at EV, 304 L/s at IV, and 1301 L/s at LuV), they won't be able to keep using cetane past like EV simply because of how much fuel it requires to keep up that level of EU/t.
>
>But if the intention is to deter players from using simple single block generators the higher up in tier you go, you could make the efficiency even worse than this. Maybe 60% down to 50%. That would encourage players to try the LCE or move onto nukes. I'd prefer that over simply removing blocks, since it keeps options open for players (i.e. let people inefficiently make energy, if they want).

## Expected Behavior
The rocket engine numbers would essentially follow the linear pattern set by the existing gregtech single block combustion generators. If @Dream-Master  thinks that's not enough then we could go even lower, starting from 60% efficiency down to 50%.

## Current Behavior
It is currently at:
136% efficiency at EV
120% efficiency at IV
104% efficiency at LuV

## Possible Solution
Just need an appropriate downscaling of the numbers.

## Context
Realistically speaking, this shouldn't affect too many players. Most players around EV either move onto nukes or kinetic/water gens. But if there are a few stragglers who want to stay with cetane/biodiesel in single block generators for personal reasons, I say let them. Just make sure that it's penalized appropriately (so that using the LCE is encouraged; "you want that extra efficiency from your liquid fuels? make an LCE")

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GT:NH
 * Version used: 2.0.4.4

Also include:
Gregtech version: gregtech-5.09.32.23
IC2 version: industrialcraft-2-2.2.828a-experimental
Java version: 1.8
Operating System: Win 10 Home 64-bit

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by richardhendricks** [comment]
Also please add pollution #'s to tooltip.

**Comment by Highbeam** [comment]
I use this single block for the ore drilling platform.  And I too was surprised the efficiency model didn't fit the other single generator blocks so I'd be more than happy to keep the efficiency model on this.

**Comment by draknyte1** [comment]
> Also please add pollution #'s to tooltip.

It never made any.

Adjusted Pollution & Fuel Usage here - https://github.com/draknyte1/GTplusplus/commit/cd4e9d4776bfbe26c7572d5bd8ba667c3c216449#diff-fbf15fdd52ed71a51c4dee99a957029a.
