### ISSUE TITLE
Excessive Liquid Air Gating

### ISSUE THREAD

**Issue by leagris** [draknyte1/GTplusplus#313]
# Overkill Replacement of Compressed air by Liquid Air in centrifuge recipe
GT++ provides a Liquid Air fluid that is obtained via the Advanced Cryogenic Freezer.
GT++ Liquid Air override standard Gregtech centrifuge recipe with compressed air input, with its Liquid Air.
This cause a much higher tech tier gating for separating Air gases.

## Expected Behavior
Do not erase or override Standard Gregtech Recipe.

## Possible Solution
* Keep Standard Gregtech Compressed Air Centrifuge Recipe intact.
* Add own recipe with Liquid AIr, with advantages like efficiency, speed…
* Used GTTweaker for work-around: https://github.com/Beyond-Reality/BeyondRealityModPack/commit/ed4fe78b25711e943a8c1f0b905c37bdef5b2ade

## Context
Production of Noble Gases and Argon.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  Beyond Reality
 * Version used:  2.5.1-r1

Also include:
 * Gregtech version: 5.09.32pre4
 * GT++ version: 1.7.0-prerelease-14-final
 * IC2 version: 2-2.2.828-experimental
 * Java version: openjdk version "1.8.0_162"
 * Operating System: Linux

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ x    Multi Player?

- May relate or be of same domain as https://github.com/draknyte1/GTplusplus/issues/300

**Comment by draknyte1** [comment]
Fluid isn't added by GT++ and has existed in standard GT for ages.
