### ISSUE TITLE
Advanced Boiler tooltip is wrong in GTNH

### ISSUE THREAD

**Issue by chochem** [draknyte1/GTplusplus#314]
# Issue Title  
Advanced Boiler tooltip is wrong, compare [GTNH issue](https://github.com/GTNewHorizons/NewHorizons/issues/3133)

## Expected Behavior
I am using the Advanced Boiler [LV] (also called LV Gt++ Steam Boiler or LV Advanced Steam Boiler in the quest). The tooltip says it produces 250L steam/s.

## Current Behavior
It produces 500L steam/s. Similarly, the MV and HV version produce 1000L/s and 1500L/s instead of the 500/750 found in the tooltip.

## Possible Solution
Change the tooltip. (also possibly check the corresponding config?)

## Context
Tried to use it because of the high charcoal efficiency. Blew up my base because of the unexpected high water usage due to the higher production rate (and the steam to water ratio (25:1) being very different from Railcraft (160:1) and other gregtech stuff (150:1)).

## Game Environment & Modpack
Playing GT:New Horizons, version 2.0.4.5 in singleplayer.

 * Gregtech version: 5.09.32.28
 * IC2 version: industrialcraft-2-2.2.828a-experimental
 * Java version: 1.8.0_151 64 Bit

**Comment by draknyte1** [comment]
The tooltip should say per tick, not per second. lol.
