### ISSUE TITLE
Server, on boot- [ERROR] Strontium recipes failed to generated NullPointerException at gtPlusPlus.xmod.gregtech.loaders.RecipeGen_Fluids.generateRecipes [ GT-PlusPlus-1.7.1.jar]

### ISSUE THREAD

**Issue by ProsperCraft** [draknyte1/GTplusplus#315]
https://gist.github.com/ProsperCraft/97432bb4e06153f74e380fe433ab6c78

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  Gregtech New Horizons
 * Version used: 2.0.4.4

Also include:
 * Gregtech version: gregtech-5.09.32.27.jar 
 * IC2 version:industrialcraft-2-2.2.828a-experimental.jar
 * Java version:openjdk version "1.8.0_171"
 * Operating System:Centos 7 minimal install

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ X]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ X]    Multi Player?

**Comment by draknyte1** [comment]
This isn't a crash, right?
If not, it's just informative logging you can ignore.
