### ISSUE TITLE
Advanced EBF not pulling Pyrotheum

### ISSUE THREAD

**Issue by Wolozo7** [draknyte1/GTplusplus#316]
GTNH 2.0.4.4

I got some Pyrotheum into the hatch before it formed with the multiblock. Since forming, it's not possible to input additional Pyrotheum. Tried with pump between tank and hatch, fluid conduits and inserting cells into the hatch.

![image](https://user-images.githubusercontent.com/34921674/41511796-6ed28662-727e-11e8-998d-1ed6ccc9b2b5.png)

**Comment by Wolozo7** [comment]
Can't tell why but it seems like the problem sorted itself out, cells are empty and tank is full.

**Comment by Wolozo7** [comment]
Sry, but this happened again today. I can't tell when exactly it pulls the pyrotheum from the cells in the hatch and/or the adjacent tank with liquid pyrotheum, but it doesn't happen immediately after filling like it should. I'll build a freezer later today and test that one.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/a1696b9887ed1fc0928b400167943c7a82baf4c1.
