### ISSUE TITLE
Recipes is missing.

### ISSUE THREAD

**Issue by Pilad** [draknyte1/GTplusplus#32]
Not many recipes for machines. So it should be in the final version?
Matter fabrication cpu e.g.

**Comment by draknyte1** [comment]
As it is, the matter fabricator only does UUA/EU to UUM.. So it's nothing amazing yet, which is why I've left recipes up to players and minetweaker for the time being. 

If you find anything missing a recipe, let me know and I'll add one before I release 1.5

**Comment by Pilad** [comment]
Ok. Thanks. And this error whose: https://github.com/Blood-Asp/GT5-Unofficial/issues/714
GT++ or GregTech ?

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/bb17a32950dc90fe9d85f4298296e1644962cf89 - Should fix the safe logging issue.

**Comment by draknyte1** [comment]
Added - https://github.com/draknyte1/GTplusplus/commit/7fbc11cc99be621373ab90a1d760e193f99c5fdc

**Comment by draknyte1** [comment]
Allows Scrap Input: https://github.com/draknyte1/GTplusplus/commit/c1c4146dfd530effc8f9a6b0752523a8183ca708
Refined handling of scrap for UUA bonus and better multipliers: https://github.com/draknyte1/GTplusplus/commit/d57a76a21f55c5703cd8ca83534b6e1e2bc99a3b
