### ISSUE TITLE
[Request] ModID change from miscutils to something meaningfull like gtpp or gregtechplusplus

### ISSUE THREAD

**Issue by DeForce** [draknyte1/GTplusplus#322]
Currently when minecraft is giving error on different mod version upon entering the server it spits out mod ids.

I had wrong version of gt++ and forge was giving me error that "miscutils" mod is missing.
I found that it is actually GT++.

Maybe you can change modID to be more meaningfull? Like gtpp or something. Miscutils is veeeeeeeeeeeeeeeery vague. 

https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/lib/CORE.java#L53

**Comment by draknyte1** [comment]
No. Modid cannot be changed or I would've done so > a year ago. 

All items in a world are registered with a name, that name is 'modid:itemname.name:metavalue', changing the modid would make all existing GT++ content in all players worlds vanish upon update.
