### ISSUE TITLE
Mutation frame too OP for gtnh [1.7.02.00]

### ISSUE THREAD

**Issue by 0lafe** [draknyte1/GTplusplus#323]
The mutation frame for gtnh is way too good for the cost. It mutates and insta kills for the cost of 9 uranium. With the thaumic restorer it has infinite durability for the cost of some gravel or red granite. 

NH already has soul frames for mutation, so I think disabling the GT++ mutation frames for NH would be a good idea.

**Comment by draknyte1** [comment]
Soul frames are pathetic though,
Try suggest a balance option instead.

Seems to me that the Thaumic Restorer is either too OP or shouldn't restore the durability on **Everything**..

**Comment by 0lafe** [comment]
Soul frames + thaumic restorer is fine though. The mutagenic frames do the OP part of the void frame, except cheaper, and instead of blocking mutation multiply it. So that's a little much in my opinion, especially if a limited part of it's function, is the entirety of another item that was deemed too OP/not needed, without the one downside of that already broken item. 

My balance suggestion is that we rely on soul frames and the restorer. That's totally reasonably for a pack that's meant to be difficult.

**Comment by mitchej123** [comment]
I think you're confusing the words difficult and tedious.

**Comment by Prewf** [comment]
Is it possible to make the mutagenic thing un-"thaumic restore"-able? I feel like that's where the real issue is. If you had to consistently consume resources to make this frame, it'd be a reasonable start to balancing it.

**Comment by mitchej123** [comment]
Could probably also bump up the durability, and the amount consumed per use -- that'd increase the cost of the thaumic restoration I believe.

**Comment by 0lafe** [comment]
They should at least be tiered in some other way, they're better than any mutation stuff you can get your hands on before the mutatron. Iirc nothing else does instadeath + mutation multiplier. 

Some uranium isn't really balanced imo for that

**Comment by Prewf** [comment]
Could we bump of the durability to the point where thaumic restoring it would be infeasible (i.e. not an option)? That's a really good idea, if we can't make it un-restoreable.

Also I do agree uranium 238 is a bit too easy. There's a reason void frames were nerfed into non-existence.. xD What if there was a rod or two of uranium 235 added in there? I like uranium itself as a component because it's radioactive (makes the bees more likely to mutate and also explains why they die)

**Comment by 0lafe** [comment]
If it has whatever 1 use translates into durability, then yeah, which makes it seem fairly reasonable, but I still think that the recipe needs a Nerf at minimum. Uranium is too early obtainable, and plentiful. I'd suggest something more late game. Maybe a tungstensteel ingot core, surrounded by some titanium/plutonium rods. 

Late game can still mass produce it, making it just harder to use earlier, and more of a loss when they break.

**Comment by draknyte1** [comment]
Blame Dream for your Shitty frame recipes, he made them cheaper in GTNH than vanilla.. 😂

Durability consumed is 100% handled by forestry, so I can't do anything there. Two uses, for the default cost is entirely balanced. Two uses for Dreams cost is silly because I ask for U235...

**Comment by Dream-Master** [comment]
@draknyte1 oh maybe i did it wrong. What was the original material so guess i doing it wrong.

**Comment by draknyte1** [comment]
Some U238 short rods, then U235 long rods and foil. You might want to change parts to Pu for GTNH.

**Comment by Dream-Master** [comment]
Pu which isotope ? @draknyte1

**Comment by 0lafe** [comment]
>Two uses, for the default cost is entirely balanced

Well, the thing is that becomes infinite with thaumic restorer. 

I still think you should either remove them, Nerf the instadeath quality to no lifestam effects, give 1 use, or blacklist them from the thaumic restorer somehow. They're really, really good right now with them being infinite and dirt cheap. 

Probably Pu-241, Pu-239 is more of a later game thing. 241 is doable in small amounts with t2 rocket, and before that if you really want to put the work in.

**Comment by draknyte1** [comment]
I closed this issue because I removed the capability for the frames to be repaired in https://github.com/draknyte1/GTplusplus/commit/1c4bd547bf5446a31a30408769ce1a05c2d55a2a.

Dream just needs to update the recipe in his scripts so that it uses some Pu and U235 as opposed to straight U238.
