### ISSUE TITLE
Wireless Charger Mark IV does not charge tools

### ISSUE THREAD

**Issue by repo-alt** [draknyte1/GTplusplus#326]
subj

GT-PlusPlus-1.7.1.01-fresh included with GTNH 2.0.4.6

## Steps to Reproduce (for bugs)
Place a charger, 
attach battery buffer, 
put some batteries, 
give yourself charged scanner and empty scanner
scan the charger to make sure it has energy
see that tricorder does not recharge

(On the server I also tried that with HV wrench and LV soldering iron)

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/42174807-27823bd6-7e2c-11e8-823f-c3eadb2404e4.png)
![image](https://user-images.githubusercontent.com/23512002/42174857-4896a906-7e2c-11e8-8871-3ef2b50ea94f.png)
![image](https://user-images.githubusercontent.com/23512002/42174870-548c2524-7e2c-11e8-9c7d-ac301d45f344.png)

**Comment by draknyte1** [comment]
It seems long range mode wasn't proper re-enabled.
Wanna check if local mode works fine?

**Comment by repo-alt** [comment]
I checked local mode and it works. It does charge tools one by one, that's why I probably didn't notice it working previously. Also I noticed that it does not charge tools completely, looks like it passes only full EU packets. That doesn't really matter, though, so, thanks for looking into that.

**Comment by draknyte1** [comment]
I've fixed each of the issues. ;)
