### ISSUE TITLE
[1.7.02.00-fresh] Coke Oven Multiblock Issues

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#327]
## Expected Behavior
When disassembling multiblock with wrench, items should return to inventory once they have left the multiblock structure.

Clicking on the controller block should not cause the GUI to shift the inventory position one cell to the right.

## Current Behavior
Multiblock forms correctly, however, when disassembling multiblock with the wrench, some items (such as the Input Bus, and Controller Block) do not return to inventory once they have left the multiblock structure.

Clicking on the controller block itself also causes the GUI to shift the inventory positions right.

## Possible Solution
 Re-examine code for Coke Oven

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Create Multiblock (I used EV blocks, with the exception of Muffler, which was MV)
 2. Try to dissemble, and/or interact with the Controller block

## Context
Standard Multiblock construction in Survival.

## Game Environment
 * Mod List - https://pastebin.com/tMe0UX51

Also include:
 * Gregtech version: 5.09.32pre4
 * IC2 version: 2.2.828-experimental
 * Java version: Java 8 b172
 * Operating System: Windows 10 Pro x64

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
So.. Breaking the structure doesn't drop all the blocks?
