### ISSUE TITLE
Sub Station Redox cells a bit too cheap

### ISSUE THREAD

**Issue by alphaNOVAircraft** [draknyte1/GTplusplus#331]
Which modpack version are you using?
 GTNH 2.0.4.6

If in multiplayer; On which server does this happen?
Private

What did you try to do, and what did you expect to happen?
I made the energy sub station. I looked up the recipes for the Redox cells that determin the capacity of the Sub Station. I expected that they have a decent price, due to the fact that the EV one ( just some tantal, nothing else expensive) has already the quadruple energy storage per block like a Lapatronic Energy orb, that is compared to the redox cells, extrem expensive. Also upgrading the Redox cells just costs a few plates of a higher tier material and some gas (e.g. Oxygen, but the late ons also more compley like argon or radon. but still extrem cheap)

For Comparison. We are currently in IV and set up a Sub Station with a capacity of over 86 Billion EU, using the LuV Redox cells. The controller has a decent price considered that you shall be able to build it when you reach EV. If we would like to have the same energy storage we would need aroun 860!!!! Lapatronic energy orbs. And they dont just cost some plates and chap gases.

What do you suggest instead/what changes do you propose?
I would definitly nerf the Redox Cells, im fine with the Sub Station controller, this one has a decent price.

For a small adjustment it would already help to make the upgrading of the redox cells const dens plates and not only a singel one. We could consider adding some more tier specific item to the uupgrade recipe.
If im informed correctly the moder Redox energy storages use fluids for the energy storge, so i would suggest adding a pump of the tier you are upgrading the Redox cell

E.g. Recipe of the IV Redox Cell: Redox Cell EV, 4 stainless steel plates, 2000 mb Nitrogen
My Suggestion: Redox Cell EV, 4 Dense Tungstensteel plates, 1 electric pump IV, 4 small Niobium Titanium Fluid Pipes, 1152 mb Molten Platinum.

This should make it still more then worth upgrading the cells, but to get 300 Million EU storage for 4 stainless plates and 2 B nitrogen seems a bit to easy.

**Comment by richardhendricks** [comment]
I think needing the pump on every redox cell is a little excessive. 18 pumps just to form the minimum size multiblock?  I'd stick with battery buffers.

How about adding tier-appropriate rotor blades instead of the full pump?

**Comment by WarlordWossman** [comment]
You don't _need_ to upgrade your cells, doubling the storage is a massive boost, it should cost more than a just a rotor, actually the pump didn't sound super expensive if you ask me.
Makes you think about investing into an upgrade with rotors you would just instantly go for it...

**Comment by richardhendricks** [comment]
I retract my comment, if you are *upgrading* cells then you are already at IV, so you should already be automating crafting anyways.

**Comment by draknyte1** [comment]
This would be a nice suggestion if I wasn't limited by the Assembler having two input slots in 5.08.

**Comment by alphaNOVAircraft** [comment]
But then we still could change the recipe to use a pump if the tier instead of the plates. They just don’t really fit into the concept imo

**Comment by draknyte1** [comment]
I don't see how a pump fits better, if at all.. these cells don't use fucking pumps :']

They're literally 1m^3 batteries.. changing the conductive plates makes far more sense than just attaching random pumps.

**Comment by richardhendricks** [comment]
Vanadium redox cells are fluid flow batteries, so a pump makes some kind of sense.  I don't know if a pump by itself is enough of a cost though.  Maybe a fluid regulator?  that would make it cost a pump and some circuits.

**Comment by alphaNOVAircraft** [comment]
> Maybe a fluid regulator? 

the amount of circuits would be extremly high the higher you go, need ing 2 per cell needs 18 chips for one layer. But we could maybe split up the recipe, in the assembler we add the dense plates of the materials with a gas, then we throw it afain in the assembly with a fluid regulator / pump and some soldering alloy maybe?! We would need a unfinished version of the cells then
