### ISSUE TITLE
Power Sub-Station Max EU capped at 2,147,483,647 EU

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#335]
# Issue Title  
 Power Sub-Station maximum power is capped at 2bil EU

## Expected Behavior
I constructed an 18 high sub-station with all LuV Redox blocks.  Each block should store 1.6bil EU and there are 144 Redox blocks inside.  Maximum expected EU is 230.4bil EU but the limit appears to be capped at 2bil?

Screenshot attached:
![2018-07-21_17 31 32](https://user-images.githubusercontent.com/32101225/43037246-eb162704-8d0b-11e8-9381-b5ec4f675046.png)

**Comment by Dream-Master** [comment]
max int maybe ?

**Comment by draknyte1** [comment]
That's a GUI issue, because of how Minecraft works. Like the rest of the PSS GUI, it's broken. 

Use a scanner.

**Comment by Dream-Master** [comment]
@draknyte1 i remeber @Technus fixing it in the GT gui using bigger vales thqn int but idk how.
