### ISSUE TITLE
Zhuhai bad structure checks

### ISSUE THREAD

**Issue by DeForce** [draknyte1/GTplusplus#336]
![image](https://user-images.githubusercontent.com/7394420/43037613-b000f70a-8d17-11e8-91ba-e5ce48f79a50.png)

Seems like zhuhai structure check is not really a good one. It checks for hatches, buses from other multiblocks, and can lead to very strange but working contraptions

**Comment by TwoTailedFox** [comment]
Makes sense. The structure when I attempted to make it wouldn't recognise a Maintenance Hatch for me on the opposite side of the structure to the controller.

**Comment by Highbeam** [comment]
ah cool, so we can put this in the open without worrying about exploding from rain? :)

**Comment by crszpth** [comment]
As in the referenced issue #361, I'm still trying to form the fishing pond. Trying with GT++ V1.7.02.09 and GT++ 1.7.03.05-GTNH still gave an incomplete structure.

However I've just downloaded a previous version (GT++ v1.7.1) and, on the same save used before, the multiblock correctly formed upon logging into the world.

**Comment by Ghengis88** [comment]
triying to build the fishingpond on GTHN Epsilon server V.2.0.5.1
it is not validating structure,  i tried adding a muffler becous it says it produces pollution but no luck.  I am building in a north/south direction, all busses and hatches are MV eccept muffler that is EV

**Comment by Ghengis88** [comment]
tried with al HV to, no luck

**Comment by Highbeam** [comment]
Is there any news on this?  We have some players resorting to 1000's of single block gt++ fish catchers now :( the fishing pond is surely a better option that that
