### ISSUE TITLE
Auto-opening doors that sense when a player is nearby

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#338]
Plz add auto-opening doors when player entities are nearby.

One low tech variety would look like saloon doors

Higher tech variety would be sliding glass doors, maybe solid doors for the Trek look?

uber tech variety maybe airlock style

**Comment by TwoTailedFox** [comment]
Iron Door.

Stone Pressure Plate.

**Comment by draknyte1** [comment]
@twotailedfox, I asked him to make this.

I'm currently in Japan again and need people to leave suggestions here as opposed to discord.

**Comment by WarlordWossman** [comment]
>  Now what would be interesting is to have the door output state via redstone. When you enter, it could turn on your stuff. dancing_men

just wire up a block update detector and take the first short pulse...

**Comment by draknyte1** [comment]
> just wire up a block update detector and take the first short pulse...

Are you implying I know how anything besides basic redstone works?

**Comment by WarlordWossman** [comment]
I mean you can always use a bud powered piston to detect the block state change :^)

**Comment by Technus** [comment]
My mod adds the online player detector

**Comment by draknyte1** [comment]
> My mod adds the online player detector

And?

The contents of other mods isn't considered when I create content. It's merely disabled after the fact by those who don't need it.

**Comment by Technus** [comment]
Nothing, just pointing out alternative I guess? (idea of such detector comes from the good old tekkit times dont really remember what was adding it back then)

Now i see the point is to make something cheap af for that purpose.

**Comment by Kiwi233** [comment]
Player Detector Cover
This one can emit if any Player is close
