### ISSUE TITLE
NPE crashes the game when gt++ checking new version during PreInit 

### ISSUE THREAD

**Issue by GWYOG** [draknyte1/GTplusplus#34]
Crashreport: http://pastebin.com/sCKApGka
(Using GT++1.4.9-release)

I believe this crash happens everytime the network checking in [NetworkUtils.java](https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/util/networking/NetworkUtils.java) fails and return false. 
Thus the getContentFromURL() method in [NetworkUtils.java](https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/util/networking/NetworkUtils.java) will always return null.
 Then when calculating the value of the field MASTER_VERSION in [Core.java](https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/lib/CORE.java), there will always be a null.toLowerCase(), which will cause a NPE crashing the game.

I think not only the `return null;` in [NetworkUtils.java](https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/util/networking/NetworkUtils.java#L32) should be changed, but also the netIsAvailable() method should use other website rather than google to check the net-connecting status. 
The reason of the latter part is that actually there's a [Greet Firewall](https://en.wikipedia.org/wiki/Great_Firewall) in China which forbids the Chinese to browse some foreign website, such as Google, YouTube or Twitter. So nearly all the Chinese player will fails the net-checking of gt++. I think maybe gt++ should double-check `http://www.baidu.com` (which is a Chinese website) if it fails to connect to google, or use other foreign websites instead of google. (Maybe github?)

**Comment by GWYOG** [comment]
Yeah, I think this bug is a continuation of #27 and is terrible for Chinese players since the existence of the Great Firewall.  DX

**Comment by draknyte1** [comment]
I wasn't aware of this issue for eastern players. 

I'll fix it for 1.5.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/releases/tag/v1.4.9.4-prerelease

**Comment by GWYOG** [comment]
Yeah, it seems that the bug has completely fixed. 
I tested both offline and online. No crash occurred and it fetched the version info on GitHub correctly in the log when I was online.
(Though it always says my GT++ needs update everytime when I login, which made me confused for a while) (Since the [recommended version](https://raw.githubusercontent.com/draknyte1/GTplusplus/master/Recommended.txt) is still 1.4.9-release)

**Comment by draknyte1** [comment]
The most up to date version is still 1.4.9, as I've released the above update as a prerelease. It'll roll around as the official release in the next few days.

**Comment by GWYOG** [comment]
Got it. =D
