### ISSUE TITLE
Pollution Scrubbers can be automated

### ISSUE THREAD

**Issue by DeForce** [draknyte1/GTplusplus#346]
Currently, pollution scrubbers can accept turbines.

If they shouldn't be automateable, they shouldn't be allowed to receive items

**Comment by Highbeam** [comment]
I don't see anything wrong with this.   They eat through turbines like crazy anyway!!! :)

**Comment by draknyte1** [comment]
It's not intended behaviour?..

**Comment by Highbeam** [comment]
My comment was not sarcastic :D yea probably not intended but it’s very expensive to set up and run even if automated with the turbine durability :)

**Comment by Wolozo7** [comment]
Wouldn't call it expensive. Unless one would run the scrubber without a pollution detector, but who'd do that.
