### ISSUE TITLE
Wire Factory - Remove Air block requirement?

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#348]
# Issue Title  
Wire Factory doesn't form if it doesn't have air blocks around it

## Possible Solution
I couldn't get the Wire Factory to form, but after checking the code I see there is a requirement for Air Blocks around it even though this isn't mentioned in the multiblock.

Actually I don't see the need for the air block requirement. Can it be removed?

I wanted to make this multiblock look fancy in my base and it doesn't work. Also, if the air block requirement stays, it will need calibrating to work with Galacticraft.airblocks and other air block types too ?

Furthermore, the requirements ask for 2 Output Bus and 2 Input Bus - I think this can be changed to 1 of each unless theres a reason for it?

**Comment by Highbeam** [comment]
Edit:  The Cutting Machine also has this requirement.  Can this also be updated?

**Comment by Highbeam** [comment]
Cutting Machine still changes to Incomplete Structure when blocks are placed in front of fit.

**Comment by Highbeam** [comment]
opened: https://github.com/draknyte1/GTplusplus/issues/375

**Comment by draknyte1** [comment]
This change isn't yet on GTNH? Please don't open pointless new issues.

**Comment by Highbeam** [comment]
2.0.5.1 is on Epsilon and Delta.

I guess that last commit wasn't included.  Wire Factory and Extruder work fine

**Comment by Dream-Master** [comment]
No we using official version 09 from curse that is not lastest source code. @Highbeam

**Comment by Highbeam** [comment]
apologies alk didn't realise, will look forward to it later :) all the other stuff looks good so far
