### ISSUE TITLE
Missing recipie

### ISSUE THREAD

**Issue by decrobyron** [draknyte1/GTplusplus#35]
No way to make the Etched IV Voltage Wiring. (According to the NEI)

**Comment by draknyte1** [comment]
http://imgur.com/a/xtpur
Recipes exist, this is a gregtech issue. Enable Yttrium Barium Cuprate Foil.

See:
https://github.com/Blood-Asp/GT5-Unofficial/issues/691

**Comment by draknyte1** [comment]
GT_Values.RA.addLaserEngraverRecipe(GT_OreDictUnificator.get(OrePrefixes.foil, Materials.YttriumBariumCuprate, 2L), GT_Utility.copyAmount(0L, new Object[]{aStack}), GregtechItemList.Circuit_Parts_Wiring_IV.get(1L, new Object[0]), 64, 480);
			GT_Values.RA.addLaserEngraverRecipe(GT_OreDictUnificator.get(OrePrefixes.foil, Materials.VanadiumGallium, 2L), GT_Utility.copyAmount(0L, new Object[]{aStack}), GregtechItemList.Circuit_Parts_Wiring_IV.get(1L, new Object[0]), 64, 480);
			GT_Values.RA.addLaserEngraverRecipe(GT_OreDictUnificator.get(OrePrefixes.foil, Materials.NiobiumTitanium, 2L), GT_Utility.copyAmount(0L, new Object[]{aStack}), GregtechItemList.Circuit_Parts_Wiring_IV.get(1L, new Object[0]), 64, 480);

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/releases/tag/v1.4.9.4-prerelease
