### ISSUE TITLE
Extruder Multiblock - Changes to Incomplete Structure after restart

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#352]
# Issue Title  
I've made the Extrusion Multiblock to correct specification:

Controller - front center
Maint - back center
Muffler - bottom center (rear)
Output Bus - bottom center (middle)
Energy Hatch - bottom center (front)
6x Input Bus - 3 each side center
3x Input Bus - top center

## Current Behavior
I left the server last night and both multiblocks were formed.  I returned this morning (assuming after a restart) and both were now showing Incomplete Structures.  Replacing the controller only fixed both multiblocks so the setup is correct.

**Comment by Highbeam** [comment]
Please see also #350.

Making the forming code for all these multiblocks less strict may help?

**Comment by Highbeam** [comment]
I think I've figured this out.

I think this problem relates to the Arc Lamps again.  The arc lamps change air blocks to 'tile.BrightAir.name'.  This can be seen changing the inside (hollow) blocks of the multiblocks and may be causing them to unform when the server restarts?

Can see the adjactent 'hollow' block on this screenshot from SFM:

![2018-08-06_12 31 54](https://user-images.githubusercontent.com/32101225/43712002-fac95ca0-9974-11e8-8d8b-7372a73b08e6.png)

**Comment by draknyte1** [comment]
What mods adds those?
It's fake air blocks aren't added correctly, but I can try manually add support.

**Comment by Highbeam** [comment]
It's galacticraft - the issue was also found on some GT multiblocks (turbine/combustion engine) and fixed here:

https://github.com/GTNewHorizons/NewHorizons/issues/3308

GalacticraftCore:tile.brightAir

> Turbines & Combustion gens have code that requires a certain number of air blocks in front of them to form; the block used for light ( GalacticraftCore:tile.brightAir I've been told) is probably not properly interacting with isAir() and preventing them from forming.


Does the front of the multiblock require air blocks also (3x3)?  I'm not sure why this would be the case but it would be nice to not need this requirement so things like archtitect blocks could partially cover the front corners etc or the multiblock can be hidden behind a wall with the controller exposed like other multis.

**Comment by draknyte1** [comment]
Well if it's GC, I advise not building in space. :p 
I imagine if it fails the air checks on GT, it fails for most mods. Just sounds like a painful living experience. 

I can try implement the fix into GT++ as then it'll help users outside of GTNH. The air requirements in front of multis have been removed though, it was an accidental side effect of copy pasting code.

**Comment by Highbeam** [comment]
It's not a space thing ;)  There's a light called Arc Lamp - when placed it changes the blocks to the tile.brightAir and makes the area very bright as if there was sunshine.  Similar to how the flood lights work

**Comment by Highbeam** [comment]
If the air requirements were removed, it should fix it to be honest as this problem never happens with other multis that are hollow.

**Comment by draknyte1** [comment]
The internal spacing must be air in every multi and if it effects mine, it effects all GT multis.

**Comment by Highbeam** [comment]
yea when I get chance I'll do a test in creative
