### ISSUE TITLE
GT++ hand pump dupes/not working

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#353]
Tried the GT++ hand pump from version
GT-PlsuPlus-1.7.03.05-gtnh

RC multiblock tanks - Appears to work fine via both right click, shift-right click, and via GUI (4B per operation is same as large fluid cells)

GT tanks - shift-right click appears to work. Cannot add fluids to pump if tank has less than pump size of fluid - might be general GT limitation.

GT fluid hatches - Appears to work properly.

Generators - shift-right click appears to work across gas/fluid/semifluid generators. Cannot extract using UI (probably due to GTNH disabling extraction from generators via UI)

Build Craft/Iron tanks portable tanks - right-click works fine.  Dupes fluids on shift-right click.

Thaumcraft Thirsty Tank - Drains fluid but does not update correctly visually. NEI shows
0/16000 Ethylene
1000/16000 ethylene
Trying to remove more with other cells does not dupe. Cannot add other fluids.  Maybe a 0 but not null fluid stack issue? Adding same fluid with an ic2 cell resets to correct value.
Shift-right click same behavior

Ticon tanks - Always dupes fluid, shift or no shift.  Fluid stays in tank. Works fine with IC2 universal fluid cell, does not work with IC2 fluid cell.

Extra Cells 2 Certus Quartz Tank - Always dupes fluids. IC2 universal and normal fluid cells work fine.

Enderstorage Advanced Ender Tank - Always dupes fluids. IC2 universal and normal fluid cells work fine.

EnderIO fluid tank - right-click when pump is empty voids fluids.  shift-right click pump properly fills. right-click when pump has fluids dupes into the target tank.

Modded fluids are a giant PITA I take it?

**Comment by draknyte1** [comment]
Other mods don't use the fluid API properly I assume?

I'll just restrict it to GT tile entities next release I guess. Currently moving house so everything is sorta on hold.

**Comment by richardhendricks** [comment]
Funny enough, I did and retested.  

					if (didDrain) {
						if ((tTileEntity instanceof IGregTechTileEntity)) {
							return this.drainTankGT(tTileEntity, aStack, aWorld, aPlayer, aX, aY, aZ);
						}
					}
				}

Bc tanks work properly when shift-clicked but the rest of the non-GT tanks are properly shut off. 

:)
