### ISSUE TITLE
Material Press controller GUI is visually broken

### ISSUE THREAD

**Issue by DualBallers** [draknyte1/GTplusplus#358]
# Issue
Running GTNH v2.0.4.8 singleplayer
The Material Press controller interface is visually broken. There is no problem forming the machine and it runs without any problems.

![image](https://user-images.githubusercontent.com/30087707/44364856-62a20580-a4c8-11e8-9662-21faccc25e48.png)
 
## Expected Behavior
Expected a nice looking controller interface. 
I am unsure if this issue is connected to #349, but I don't experience the same issues as is described here.

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Fixed at the same time as https://github.com/draknyte1/GTplusplus/issues/349.
