### ISSUE TITLE
3 multiblocks that shift the inventory to the right/screwing it up

### ISSUE THREAD

**Issue by ScriptedPiky** [draknyte1/GTplusplus#359]
# Issue Title  
Multiblocks that do the darnest of things

## Current Behavior
The three multilblocks: Thorium Reactor [LFTR], Industrial Coke Oven, and Matter Fabrication CPU all cause the inventory to shift right and bug out

## Steps to Reproduce (for bugs)
Rightclicking the multiblock

## Context
Mildly aggravating in Multiplayer (and Single Player)

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
GTNH: 2.0.4.5 (Server) and GTNH: 2.0.4.8 (Single Player)
If not using a modpack:

Also include:
 * Gregtech version: 5.09.32.32
 * IC2 version: 2-2.2.828a
 * Java version: 
 * Operating System: Windows

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/1c352224a94da9bb56962f1fe86c6372be8f72f9.
