### ISSUE TITLE
On blast smelter, Zeron-100 or other alloy liquid cannot be processed

### ISSUE THREAD

**Issue by decrobyron** [draknyte1/GTplusplus#36]
Hello, 

http://imgur.com/a/BoWRa

I put the right amount of the resources and config chip on the smelter and it is not working. 
I tried few other alloy smelting but it did not work. 

Tantalloy smelting worked on same machine.

**Comment by draknyte1** [comment]
Using the correct number circuit?
Got enough power?

**Comment by decrobyron** [comment]
Config is 6, as NEI says. 
Power is IV. even with 4 IV orb battery.

**Comment by draknyte1** [comment]
If the recipes are in NEI and other recipes work, I'm not sure. 

I'll take a look later today, it's 4am in a moment.

**Comment by decrobyron** [comment]
Thank you. It is 3 am here. Take your time.

**Comment by draknyte1** [comment]
Thanks for your reports. 
If I find anything, fix will probably be out in v1.5.

**Comment by decrobyron** [comment]
Question:
1. Does Alloy Blast Smelter controller block have the name as the Blast smelter? Why not Alloy blast smelter controller block? 
2. Except energy hatch(which is Insane voltage), all are MV hatch/buses. Is this matter? Does any hatch requires the specific hatch to work with? 
3. Other than recipe in Input bus, do I have to configure other thing? Such as use screw driver or mode changing?
4. Does the number of the resources or order in input bus matter? Such as each stack of the dusts not inputted as NEI order or config chip at the last slot.

**Comment by draknyte1** [comment]
Not sure what you mean for 1.
No, any hatches should work. The input bus should probably be 9 slots, but there is no check to enforce this.
Nope, nothing for 3.
Don't think the order matters for 4.

**Comment by qMrx3D** [comment]
It might have something to do with this code in GregtechMetaTileEntity_AlloyBlastSmelter
`ItemStack[] tInputs = (ItemStack[]) Arrays.copyOfRange(tInputList.toArray(new ItemStack[tInputList.size()]), 0, 2);
`

It only checks the first 2 items, when doing recipe lookup :)

**Comment by draknyte1** [comment]
Well, just Means Input item order matters in the hatches for the time being.
