### ISSUE TITLE
Matter Fabrication CPU dont work

### ISSUE THREAD

**Issue by FallDark** [draknyte1/GTplusplus#360]
# Issue Title  
Matter Fabrication CPU dont work

## Current Behavior
insert circuit to controller but dont work

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
Also include:
 * Gregtech version:5.09.32.33
 * IC2 version: industrialcraft-2-2.2.828a
 * Java version: Java8u151
 * Operating System: Windows 10
### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Try putting it in an input bus.

**Comment by FallDark** [comment]
still dont work

**Comment by draknyte1** [comment]
Ask in the GTNH discord then how the other folks have it working. I think one mode may be broken. 

I'll take a look.

**Comment by FallDark** [comment]
My friend told me it dont work in 2.0.4.7 and now i use beta gt++version still the same

**Comment by draknyte1** [comment]
Unless someone raises a ticket like this, nothing will ever change between versions. 
Contrary to popular belief, I'm not psychic. 

As I said, I'll take a look.

**Comment by Kiwi233** [comment]
I found that Matter Fabrication CPU can only produce UU-M no matter which circuit
