### ISSUE TITLE
Chemical Dehydrater EV - incorrect circuit in pattern

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#364]
The recipe for the Chemical Dehydrater (EV) asks for a HV circuit.
Should be EV

![2018-08-30_00 19 21](https://user-images.githubusercontent.com/32101225/44818755-65001000-abea-11e8-822a-43530f63fa1a.png)

**Comment by draknyte1** [comment]
To be honest, it's probably intended, unless the next two tiers use respective tier circuits.
The lower tier two should us LV/MV, so it seems suitable if so.
