### ISSUE TITLE
Large Mixer does not work for recipes with fluid

### ISSUE THREAD

**Issue by NeroOneTrueKing** [draknyte1/GTplusplus#366]
## Expected Behavior
Putting in the required solid components in an input bus and the required fluid components in an input hatch should work in the large mixer.

## Current Behavior
Mixer recipes that have fluids (like making nitration mixture, superconductor alloy, or fluix crystals) do not work in the large mixer.

## Possible Solution
Wild guess, but it might have to do with how some multiblocks treat each bus as its own inventory recipe purposes so that you can have 9 input buses each with a different programmed circuit number.

## Game Environment
 * Modpack Name:  GTNH
 * Version used: 2.0.4.9

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by NeroOneTrueKing** [comment]
My mixer has multiple input buses, so I tried a couple things:
Test 1: Redstone dust and silicon and a circuit#2 in one bus, coal dust in another bus. Does not run.
Test 2: Redstone dust, silicon, coal dust, and a circuit#2 all in one bus. Runs as expected.

While the mixer does not explicitly say that input buses are separate, it appears to be that way regardless.
Cheers!

**Comment by Kiwi233** [comment]
Hope to fix this in the new version
