### ISSUE TITLE
Certain materials do not have recipes for dust to ingot or fluid.

### ISSUE THREAD

**Issue by ghost** [draknyte1/GTplusplus#371]
## Current Behavior
Certain materials such as Thorium Tetrafluoride, Lithium Fluoride, Zirconium Tetrafluoride, Plutonium-238, and possibly others lack a way to turn a dust into a fluid or an ingot. Some of these also lack a way to turn an ingot into dust, only having a recipe for blocks to dust.

## Possible Solution
Add recipes

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.

GT++ version 1.7.02.09

If you are using a Modpack:

 - Modpack Name: GT New Horizons
 - Version used: 2.0.4.9

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by sthegreat** [comment]
Here is a more complete list for materials that have ingots and dusts without a way to convert them to fluid/ingot (note that I just went thru nei, I don't know which of these are obtainable or have a need for these recipes):

Technetium
Polonium
Francium
Radium
Protactinium
Neptunium
Curium
Fermium
Thorium 232
Berkelium
Thorium Tetrafluoride
Thorium Hexafluoride
Uranium Tetrafluoride
Einsteinium
Uranium Hexafluoride
Zirconium Tetrafluoride
Neptunium Hexafluoride
Technetium Hexafluoridee
Selenium Hexafluoride
The 3 LFTR salts
Plutonium-238
Lithium Fluoride
Actinium
Bromine
Beryllium Fluoride
Astatine
Californium
Americium-241
Polonium-210
Strontium-90

**Comment by draknyte1** [comment]
I think this is all fixed next update.
