### ISSUE TITLE
OpenBlocks Sprinklers

### ISSUE THREAD

**Issue by SampsaxD** [draknyte1/GTplusplus#376]
# Issue Title  
Adding more options for fertilizing with OpenBlocks Sprinkler to GTNH

## Expected Behavior
Currently the only fertilizer you can insert into the sprinkler is bone meal. adding IC2 and Forestry fertilizer would make sense.

## Game Environment
GTNH 2.0.5.1

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ x]    Multi Player?

**Comment by draknyte1** [comment]
Will come back to this someday.
