### ISSUE TITLE
GTNH Control circuit accepts only 1 type of LuV circuit

### ISSUE THREAD

**Issue by Lainiel** [draknyte1/GTplusplus#381]
## Expected Behavior
Wanted to craft GT++ control circuit. Couldn't because it didn't accept my Master quantumcomputer.

Recipe didn't start.
![](https://puu.sh/BvuVU/060bd00c5e.png)
Recipe in question:
![](https://puu.sh/BvuRD/3a9a393134.png)

https://github.com/GTNewHorizons/NewHorizons/issues/3632

## Possible Solution
Fix the recipe to accept any type of LuV circuit.

## Game Environment
GTNH 2.0.5.1

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Ore Dictionary support for things within the assembler is _NOT_ handled by me, but by GT itself.
There's no way for me to allow any circuit beyond an explicit one, so I won't be fixing this,
