### ISSUE TITLE
GT++ portable scanner/gregtech sensor data

### ISSUE THREAD

**Issue by Bryfer** [draknyte1/GTplusplus#384]
# GT++ portable scanner/gregtech sensor data
A few suggestions about this information that can be given from GT++ machines
basicly make it easier to read quickly, and more relevant data

## Expected Behavior
Some of the gt++ machines can be used as multiple machines.
This data will not change if you change mode with a screwdriver, it will still show all available options on the  Advanced Information Panels (AIP)
- I would like this to change so its only showing the current mode

---
I would also like the maintenance issues to show up in a more similar way to the Large Turbines.
Since they change color, it gives the player a better way of quickly detecting if there is problems with the machines
![image](https://user-images.githubusercontent.com/22825059/45712274-2e376d00-bb8c-11e8-9ad2-761d08e52f9f.png)

---

I would also like to see this fuction added since it gives the players a good understanding of how much the machine is actually consuming, currently its only available for gt multis with coils (?)
![image](https://user-images.githubusercontent.com/22825059/45712320-50c98600-bb8c-11e8-9654-3869784ac5dd.png)
 

## Im just gonna post some pictures here to let you know how im currently using the AIP
![image](https://user-images.githubusercontent.com/22825059/45712419-98501200-bb8c-11e8-9052-0d8c191a9738.png)
![image](https://user-images.githubusercontent.com/22825059/45712430-a3a33d80-bb8c-11e8-91fd-3d655f3d8182.png)
![image](https://user-images.githubusercontent.com/22825059/45712452-b0c02c80-bb8c-11e8-8b4c-2b27ed29365d.png)
![image](https://user-images.githubusercontent.com/22825059/45711680-a2711100-bb8a-11e8-9311-dbbe5187d9f5.png)

## Context
 How has this issue affected you? What are you trying to accomplish? 
trying to improve the GUI 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.5.1

Also include: - not relevant to this issue

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
So I just borrowed a heap of stuff from the GTNH fork.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java#L399
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ProcessingArray.java#L412

These two things most notably.
If it works correctly, will close when I push to Github.

**Comment by draknyte1** [comment]
![image](https://user-images.githubusercontent.com/3060479/51035073-bceb5200-15a0-11e9-84e1-c87b9403b0db.png)
