### ISSUE TITLE
Suggestion:  Compatability between Pollution Detection Device and OpenComputers [1.7.02.09]

### ISSUE THREAD

**Issue by Teirdalin** [draknyte1/GTplusplus#386]
So I'm just suggesting a method in the Pollution Detection Device to allow for opencomputers to detect the pollution level,  we would be able to pull the information from the scanner result but it tells the scanner that the pollution is always 0.

An easy fix would just be to have it tell the scanner when scanned the proper pollution level instead of always 0.

Build a Pollution Detection Device, have some pollution in the chunk, use your scanner on it.

Building a grid of pollution detection devices and oxygen recyclers and connecting them all to an opencomputers server and using the data gotten to make an overview of the facilities pollution levels.
![topside](https://user-images.githubusercontent.com/37776581/46425423-832cc480-c6f0-11e8-8572-c979182310b0.png)

As an aside, it'd be nice if we also had a method in machines to see what items are inside them; I know this is a bit unnecessary of a suggestion, but it'd be nice if my system could check the filters condition remotely.

Also this is a recreation of https://github.com/GTNewHorizons/NewHorizons/issues/3699#issuecomment-426605998

I am using this in a modpack.
Gregtech New Horizons
2.0.5.1
https://www.technicpack.net/modpack/mcnewhorizons.677387

 * Gregtech version: 5.09.32.36
 * IC2 version: 2-2.2.828a-experimental
 * Java version: 1.8.0_171_b11
 * Operating System: Windows 10 Home 64-bit, build 17134

 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
I've come to realize that the detection counter is wrong for both current and avg/10 counters.
Should be a simple fix.

**Comment by draknyte1** [comment]
![image](https://user-images.githubusercontent.com/3060479/50402871-ebd88a00-0791-11e9-800c-6bfa7adb23f0.png)
