### ISSUE TITLE
Add Eglin Steel Base Compound to the ABS 

### ISSUE THREAD

**Issue by DualBallers** [draknyte1/GTplusplus#392]
Also reported in GTNH https://github.com/GTNewHorizons/NewHorizons/issues/3742

## Expected Behavior
Eglin Steel Base should be possible to craft in the Alloy Blast Smelter

## Current Behavior
The Eglin Steel Base Compound does not have a recipe in the Alloy Blast Smelter.
The Mixer recipe for this metal is annoying as it is the only recipe that uses circuit(20) (at least in current version of GTNH)

## Possible Solution
Add recipe for the eglin base compound to the ABS.
4 Iron dust + 1 Kanthal dust + 5 Invar dust + circuit(3) = 1440 fluid eglin steel base compound

## Context
Got confused when a GT++ mixed metal could not be processed in the ABS. 

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Base compound should never have an ABS recipe. It’s a half mixed alloy?

**Comment by DualBallers** [comment]
To me it looks like the eglin base compound is the only one of its kind, as it is only available as dust. 
All other comparable "base" materials (e.g. superconductor base and enderium base) are smeltable.

Are there any reason for not skipping the eglin base compound entirely and doing
4 Iron + 1 Kanthal + 5 Invar + 1 Sulfur + 1 Carbon + 4 Silicon + circuit(6) = 16*144 Eglin fluid

I tested with circuit(1) through circuit(6) with a full stack of each dust and combination does not conflict with any other recipe.
