### ISSUE TITLE
wrong recipe for some combs in industrial centrifuge [v1.7.02.09]

### ISSUE THREAD

**Issue by boubou19** [draknyte1/GTplusplus#399]
## Expected Behavior
I was prcessing the lapis combs and redstone combs from gendustry.
I expected to get the output from this recipes:![image](https://user-images.githubusercontent.com/12850933/49898684-f32a9a00-fe59-11e8-8124-666b61b52710.png)
![image](https://user-images.githubusercontent.com/12850933/49898899-8532a280-fe5a-11e8-8f7d-f16e4b6a310a.png)

## Current Behavior
I'm getting fulls dusts instead of tiny piles:
![image](https://user-images.githubusercontent.com/12850933/49898984-c034d600-fe5a-11e8-9f8c-c67a41aa4997.png)

![image](https://user-images.githubusercontent.com/12850933/49898930-97144580-fe5a-11e8-8951-def37efa5308.png)

I don't know if some other combs are affected too.

## Possible Solution
fix the recipe please.

## Steps to Reproduce (for bugs)
 1.set up an industrial centrifuge
 2.process lapis combs or redstone combs from gendustry.

## Context
I was testing the industrial centrifuge to see if it could handle my gigantic amount of combs.

## Game Environment
 * Modpack Name:  GT:NH
 * Version used: 2.0.5.1

 * Gregtech version:5.09.32.36
 * IC2 version:2.2.828a-experimental
 * Java version: java8u161
 * Operating System:W10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
The recipes are duplicated from the singleblock, it’s an issue with GTNH adding these recipes.

**Comment by Dream-Master** [comment]
@draknyte1 and how it can be fixed?

**Comment by Dream-Master** [comment]
my original recipes gives only tiny piles out so what I can fix? @boubou19 which recioes are affected and which Bee combs?

**Comment by boubou19** [comment]
i only tested lapis combs and redstone combs so far. I'll post others when i'll find them

**Comment by Dream-Master** [comment]
ok

**Comment by boubou19** [comment]
i found the issue: it was me having a mismatch of MT scripts with the server. Btw i think a full redstone is a bit too much imo.
