### ISSUE TITLE
Small Liquid Storage Tanks & Multiblock tanks too!

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#4]
Multiblock configurations for Liquid Storage.

The Storage tanks will consume a small amount of EU to either 'refrigerate' or 'warm' the liquid contained inside. Power usage is based on the liquids temperate, so Lava and Cryotheum probably will cost you a chunk more than say, distilled water. Comparable in density to half a drum (Maybe a 1/4 - 64000mb) per block in the structure, this should allow dense, albeit costly, liquid storage.

**Comment by bear989** [comment]
these sound like great ideas, I would love a better alternative for liquid storage.

**Comment by draknyte1** [comment]
Just something I worked on tonight.
![2016-09-03_03 05 26](https://cloud.githubusercontent.com/assets/3060479/18212188/0a47eabc-7185-11e6-9598-178c42ffc285.png)

**Comment by draknyte1** [comment]
![2016-09-10_12 26 40](https://cloud.githubusercontent.com/assets/3060479/18407514/ea2f27aa-7755-11e6-89b9-b989137edab9.png)
![2016-09-10_12 27 31](https://cloud.githubusercontent.com/assets/3060479/18407515/ea313c16-7755-11e6-87f7-2be7a8fdca34.png)

Added some Fluid Storage tanks for all tiers, with recipes.
850c1bae257de7fc3d10b0d66c7944155ce4f02a
a0091aa059dc9e59422f36e6ee658509f549a210

**Comment by draknyte1** [comment]
![2016-09-11_14 44 34](https://cloud.githubusercontent.com/assets/3060479/18415232/7f8608d6-782e-11e6-85a4-8a4b9c80a600.png)
![2016-09-11_14 44 26](https://cloud.githubusercontent.com/assets/3060479/18415233/7fe1192e-782e-11e6-936b-5c0943c4c41d.png)

GT++: x = 93 * 64000  
GT++: x = 5952000  
Casings Count: 93  
Valid Multiblock: true  
Tank Storage Capacity: 5952000L

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/466c2293b44a10648d9b8670e669a67f41ca8e07 & https://github.com/draknyte1/GTplusplus/commit/a270a0901863873c5b8a134290428304141df818 Fixed small tanks, they now store their liquids when wrench moved. :D

**Comment by draknyte1** [comment]
Refined storage with - https://github.com/draknyte1/GTplusplus/commit/411cee902afebc3550e43eeae80b380a21ec7a82 - Now the tanks constantly save the fluid stored to NBT, not just on chunk updates like the were by default.

**Comment by draknyte1** [comment]
Fixed Fluid handling in the Large Multitank. - https://github.com/draknyte1/GTplusplus/commit/158a6c18bd91ac2af8e09361e79757bfafdd0ad6

It now fills the internal buffer from an input hatch, then it will keep the output hatch full.


Remaining Issues;
> No Recipe for the Controller or the casings.
> Controller does not save it's maximum capacity on a world reload.
> Controller does not save it's fluid stored on a world reload.
> Reverse Fluid handling. Currently will fill the tank forever until full, then fill output. It should fill output then fill tank.

**Comment by draknyte1** [comment]
https://youtu.be/xRAoInwcItU?t=1008

As shown by Bear, my small tanks do not work correctly in .24+ yet work fine form .08.30 to .09.23. @Blood-asp @Muramasa- What changed in tile entities?

**Comment by draknyte1** [comment]
Well, fluid save/load handling got a rewrite for portable tanks, now they should work across all versions.
https://github.com/draknyte1/GTplusplus/commit/61d230f4cdf36cf3ccee23415c69f72971a71266 fixed this.

**Comment by draknyte1** [comment]
Fixed the large multitank logic, now they work perfectly.
Output hatch will fill first, then excess fluid is stored in an internal tank.
Fluid type in tank and 96000l is retained when the controller block is moved, and 96000l is added per layer in the tank, up to 20 layers tall.

Fixed in https://github.com/draknyte1/GTplusplus/commit/fa443499f71863e315cc0a89f27c1cb58cd757b9
