### ISSUE TITLE
Adv.EBF is 'Incomplete Stucture' when using New Coils.

### ISSUE THREAD

**Issue by yukieiji** [draknyte1/GTplusplus#401]
# Issue Title  
Adv.EBF is 'Incomplete Stucture' when using Electrum Flux/Awakend Draconium Coils.[GT-PlusPlus-1.7.02.09]

## Expected Behavior
Adv.EBF work well when using Electrum Flux/Awakend Draconium Coils.

## Current Behavior
Adv.EBF is 'Incomplete Stucture' when using Electrum Flux/Awakend Draconium Coils.
![2018-12-19_21 24 03](https://user-images.githubusercontent.com/40425798/50220433-aa349180-03d5-11e9-8c49-a82d8bc6149d.png)
![2018-12-19_21 24 04](https://user-images.githubusercontent.com/40425798/50220434-aa349180-03d5-11e9-8ad9-2ae62058d736.png)

## Steps to Reproduce (for bugs)
1.Setup Adv.EBF with Electrum Flux/Awakend Draconium Coils.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name: GTNH
 * Version used:ver2.0.6.0 and ver2.0.6.2

Also include:
 * Gregtech version:gregtech-5.09.33.03b and gregtech-5.09.33.04
 * IC2 version:industrialcraft-2-2.2.828a-experimental
 * Java version:1.8.0_191
 * Operating System:Windows 10 Pro and Cent OS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Ehh, probably won’t add support for custom coils added by GTNH.
