### ISSUE TITLE
Basic Hand Pump NPE

### ISSUE THREAD

**Issue by DietmarKracht** [draknyte1/GTplusplus#409]
# Issue Title  
 The basic Hand Pump crashes the game when using it onto an everful urn.

## Current Behavior
Righclicking or shift+ rightclicking on an everful urn with the basic hand pump equipped will cause your client to crash. 

## Possible Solution
 Blacklist certian blocks. i believe there are other blocks that might cause these issues.

## Steps to Reproduce (for bugs)
 1.Equipp basic hand pump
 2.right /shift+ right click onto everful urn
 3.enjoy crash
 4.crashlog: https://paste.feed-the-beast.com/view/bea0ae62

## Game Environment
 Happened to me on GTNH Delta Server

**Comment by Dream-Master** [comment]
GTNH Delta Server use GT-PlusPlus-1.7.02.09
