### ISSUE TITLE
Item Detection Cover not working

### ISSUE THREAD

**Issue by HawkridgeV** [draknyte1/GTplusplus#416]
# Issue Title  
Cannot craft item detection cover

## Expected Behavior
weightes gold pressure plate + any of iron aluminium or wrought iron plate in an assembler with soldering alloy gives a item detector cover

## Current Behavior
assembly line does not start (with soldering alloy), other fluids not tested

## Possible Solution
please fix! 

## Steps to Reproduce (for bugs)
 . 
 1.put ingredients into any assembler
 
Multi player GTNH server myftb.de

**Comment by draknyte1** [comment]
Hey buddy, that issue should be reported here: https://github.com/GTNewHorizons/NewHorizons/issues
