### ISSUE TITLE
wireless charger mkVIII doesn't have a recipe

### ISSUE THREAD

**Issue by boubou19** [draknyte1/GTplusplus#418]
## Expected Behavior
I wanted to have a look at the recipe of the wireless charger MK VIII in nei
## Current Behavior
it's the only one who doesn't have one

## Possible Solution
add it pls.

## Steps to Reproduce (for bugs)
 1. look at the wireless charger mk VIII in nei

## Game Environment
 * Modpack Name:  GT:NH
 * Version used: 2.0.5.1

Also include:
 * Gregtech version:5.09.32.36
 * IC2 version:2.2.828a-experimental
 * Java version:jre 8u171
 * Operating System: windows 7

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by Dream-Master** [comment]
fixed i guess
![image](https://user-images.githubusercontent.com/2970688/51935644-a64d5380-2406-11e9-8602-77a8e53b0a72.png)

**Comment by draknyte1** [comment]
I probably forgot to close the ticket last commit, oops. 

I redid them all just because one wasn’t craftable.
