### ISSUE TITLE
Simple Hand pump does not remove fluid from Fluid extractor/canner

### ISSUE THREAD

**Issue by leglerm** [draknyte1/GTplusplus#423]
## Expected Behavior
Handpump picks fluid

## Current Behavior
Nothing

## Steps to Reproduce (for bugs)
Use empty simple hand pump on fluid extractor (or canner) with fluid in the output (input)

## Context
Move fluids
I also tried seed oil to test if its molten metals only and the same occured. 

## Game Environment
GTNH -2.0.5.1

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
I don't recall if it works on the outputs of GT things.
I mean, I guess I can add that behaviour if not.
