### ISSUE TITLE
Large Scale Auto-Asesembler v1.01 can't build up Circuit board[v1.7.02.09]

### ISSUE THREAD

**Issue by benzenesulfonic-acid** [draknyte1/GTplusplus#426]
# Issue Title  
Large Scale Auto-Asesembler v1.01 can't build up Circuit board[v1.7.02.09]

## Expected Behavior
The Chinese tips say the Large Scale Auto-Asesembler v1.01 can be used to build up Circuit board, But I try all three modes of Large Scale Auto-Asesembler , It just can't work. I use it in a Clean room. 
I want to know is Large Scale Auto-Asesembler can build up Circuit board or not. If it can't, I suggest add a “Large” Circuit Assembling Machine

## Game Environment
 * GTNH 2.0.6.0

Also include:
 * Java version:8
 * Operating System:win10

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
CIRCUIT mode is disabled in GTNH and the tooltip is already updated.

In future, there will be capabilities for the current Cn translators to also translate the tool tips to Chinese. :)
