### ISSUE TITLE
The Field Generator V has two scan recipes

### ISSUE THREAD

**Issue by Kiwi233** [draknyte1/GTplusplus#431]
# Issue Title  
The Field Generator V has two scan recipes[v1.7.02.89]
(GTNH 2.0.6.8)

## Expected Behavior
Scan a Field Generator V to get data about the Field Generator VI

## Current Behavior
![image](https://user-images.githubusercontent.com/42833050/53409489-f74b6a00-39fb-11e9-8d92-0c1853310e2c.png)
It has two scan recipes, when i scan a Field Generator V, i will get data about the Containment Casing

**Comment by Dream-Master** [comment]
one of the recipes need to be changed
