### ISSUE TITLE
[1.7.02.89-beta] GT++ A2 Log Spam

### ISSUE THREAD

**Issue by EvgenijM86** [draknyte1/GTplusplus#432]
Original from here - https://github.com/GTNewHorizons/NewHorizons/issues/4111

Spams A2 constantly making giant log files. possibly multi block checking related.

[INFO]  [13:26:58] [Client thread/INFO] [GT++]: A2
[INFO]  [13:26:58] [Client thread/INFO] [GT++]: A2
[INFO]  [13:26:58] [Client thread/INFO] [GT++]: A2

pls fix to make debugging other issues possible.

**Comment by EvgenijM86** [comment]
This happens maybe a couple of times per hour (I use GTNH modpack). It also lags server and game pretty much pauses until the spam is finished.

**Comment by kloftis** [comment]
I updated GTNH to use GT++ 1.7.02.24, but I still get the the A2 message, though it is slightly different:

[B#402]  [20:57:33] [Client thread/INFO] [GT++]: A2

Getting ~40 of these messages a second.

For me, it's not an intermittent thing, but happens whenever the player model is in view (F5 mode, inventory, etc.)

**Comment by draknyte1** [comment]
Don’t use beta builds.
