### ISSUE TITLE
GT++ Frame Housing interfere with Forestry Alverary Components

### ISSUE THREAD

**Issue by leagris** [draknyte1/GTplusplus#46]
Even if disabled in config. The Frame Housing replaces by name one of the Alveary Components. The other Alveary components looses their localized names that are changed to Alveary 1, Alveary 2…

**Comment by draknyte1** [comment]
I dunno, I tried to fix it. 
I'll just remove it, don't really care at this point. 

Blame me all you want, but I simply can't use forestys code properly. I've probably missed something basic, but whatever. 

They've already remade binnies mods, and someone has fixed existing versions through ASM, Chocohead. My thoughts on the matter are, it's pretty obsolete. Nobody else cares enough to have thoughts on it, I've asked for help and the example weren't very helpful..

**Comment by draknyte1** [comment]
As far as I can tell - https://github.com/draknyte1/GTplusplus/commit/2428149c0d5277a9fa0c80faebd89e8c753bfb67 has fixed this and they will no longer be enabled at all in any way shape or form.
