### ISSUE TITLE
iron plated bricks not having a recycling recipe

### ISSUE THREAD

**Issue by bear989** [draknyte1/GTplusplus#47]
there isnt a recipe showing at least to recycle it, this maybe another bloody hiding recipe thing, but usually it would at least show a macerator/pulverizer recipe.

**Comment by draknyte1** [comment]
I never made recycle recipes for it.

**Comment by draknyte1** [comment]
What should it output mate?

**Comment by bear989** [comment]
clay dust for the bricks and 6 iron dust for the iron plates, if shreeded, if you add arc furnace recipes then it would be ash and 6 wrought iron ingots.

**Comment by draknyte1** [comment]
Recipes added in https://github.com/draknyte1/GTplusplus/commit/6ff10a554d56604d82aa400a6c027f785a1f0f12
