### ISSUE TITLE
Gelid cryotheum possible cause of a case of Big Reactor temperature fluctuation

### ISSUE THREAD

**Issue by K0rkki** [draknyte1/GTplusplus#48]
I can't 100% pinpoint the issue to gelid cryotheum, could be the fluid coolants in general or something completely different but just in case decided to post this here aswell since gelid cryotheum played a major role in my testing. https://github.com/erogenousbeef/BigReactors/issues/586

**Comment by draknyte1** [comment]
I think someone else is maintaining BR now. 
Are you able to use that authors latest build?

There was links to it in other issues on the original BR issues page.
