### ISSUE TITLE
iron plated bricks pulverizer recipe

### ISSUE THREAD

**Issue by bear989** [draknyte1/GTplusplus#49]
there is a rock crusher recipe for 6 iron dust and 2 clay dust but not a pulverizer recipe to get both. 
just to be picky :)

**Comment by bear989** [comment]
Iron plated blast furnace controller has 18 iron and 10 bronze but only gives 8 and 10, the double iron plates i guess arent being added in as well as the 3 iron for the bucket.

**Comment by draknyte1** [comment]
They're all added by gregtech automatically. Must be a quirk there
