### ISSUE TITLE
Add some custom Alveary casings.

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#5]
Basically replacements for the frame housing and Mutation casing from ExtraBees, any other ideas are valid.

**Comment by draknyte1** [comment]
It painfully requires me to copy infinite classes forestry to get it working in any way, since Eclipse fails to let me extend 90% of the classes I need. 110% open for suggestions here.

**Comment by draknyte1** [comment]
@mezz, probably not really interested, but any suggestions?
Probably overlooked something simple.

**Comment by mezz** [comment]
I opened up the API for multiblock parts enough that you should be able to implement these without using internal Forestry classes or copying lots of code. I can help more when I'm at my computer, let me know where you are stuck.

**Comment by draknyte1** [comment]
I'll take another look sometime today, had quite the busy weekend.

First attempt netted me textureless Alveary blocks, which would client crash on use (Multiblock did form though)
Second attempt didn't produce anything useable. (This was more of an attempt at reimplementing the entire thing than adding a single new multiblock part)

I'll either end up on IRC later or posting a progress update here, if I'm in need of any assistance. Cheers mate!

**Comment by draknyte1** [comment]
Fixed an issue where my blocks would override the vanilla forestry casings. https://github.com/draknyte1/GTplusplus/commit/a2edbb02533a43e61c820e3687d8f4050d4b97b5 - an oversight on mybehalf probably from 5am coding.

Really need to finish these someday~
