### ISSUE TITLE
Bronze Workbench crashes SP and MP

### ISSUE THREAD

**Issue by redmage17** [draknyte1/GTplusplus#50]

**Comment by draknyte1** [comment]
If you don't provided more details, I can't do anything to fix it.

**Comment by redmage17** [comment]
Happens both in single player and multiplayer try and right click to use it and it crashes. Using most current version of GT++ and GT5u as well as forge for 1.7.10 if that helps. 
[crash-2017-01-08_20.06.49-client.txt](https://github.com/draknyte1/GTplusplus/files/692577/crash-2017-01-08_20.06.49-client.txt)

**Comment by redmage17** [comment]
will test on next release, thank you
