### ISSUE TITLE
Energy Buffer recipes (new recipe suggestion)

### ISSUE THREAD

**Issue by Jelmazmo** [draknyte1/GTplusplus#52]
Maybe it will be better to use not ic2MFE but something from gregtech in initial recipe? Medium Lithium battery, for example, or something like. Some players can disable ic2 machines from crafting so it is actual question.

**Comment by draknyte1** [comment]
Sure, never considered such a thing. 
As they're not meant to be accessible until HV, it'll probably be a lapotron crystal or cluster.. Otherwise I'll implement something as a placeholder of about equal cost :)

**Comment by Jelmazmo** [comment]
You considering to remove energy buffers that less than HV? Maybe but it will require rebalance since lapotron crystal has 10M EU capacity and current HV buffer has 128M. Orb is fine but it is more suitable for EV. Something craftable in assembler like stack of 12 crystals and some plates/wires/molten metal/whatever?

**Comment by draknyte1** [comment]
They're there so you can buffer LV efficiently for say mass fabricators later game. ;)

I'll take a look and make up a new item, which doesn't require IC2 and is better tiered in with the other content, thanks for the suggestion.

**Comment by killslash** [comment]
Oh man, I was hoping these would be an alternative to battery buffers in LV tier. Right now battery buffers have 3x loss as I just found out. I was hoping for a single block energy storage solution, maybe not as big as a fully packed buffer, but avoids the lossyness of it.
