### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Pilad** [draknyte1/GTplusplus#55]
http://pastebin.com/aZp3dBtt

**Comment by draknyte1** [comment]
Two things. 

1.) you didn't follow the crash report format. 
INVALID. 

2.) you're missing the required mod, PlayerAPI.
INVALID.

**Comment by Pilad** [comment]
PlayerAPI in requirements for mods GT++(on curseforge) not write. 
Add PlayerAPI . Minecraft is started. Thank you.

**Comment by draknyte1** [comment]
It is there for the single version on curse that requires it.
![playerapi](https://cloud.githubusercontent.com/assets/3060479/23013271/a169dad6-f475-11e6-9b18-352ccf837581.png)

**Comment by Pilad** [comment]
Ok. Thanks.

**Comment by draknyte1** [comment]
To resolve this in the future, I added this. https://github.com/draknyte1/GTplusplus/commit/ce33b51cbd577083b0fa643d79c192b41372b609
