### ISSUE TITLE
GT++ ruins GT large turbine block texture

### ISSUE THREAD

**Issue by Azruine** [draknyte1/GTplusplus#56]
![2017-02-17_14 28 07](https://cloud.githubusercontent.com/assets/6277538/23053567/d6b7fad0-f51d-11e6-8b04-f4a32c2260e7.png)
![2017-02-17_14 28 15](https://cloud.githubusercontent.com/assets/6277538/23053568/d6b84fee-f51d-11e6-8f6a-f2661fe0a001.png)
![2017-02-17_14 31 16](https://cloud.githubusercontent.com/assets/6277538/23053566/d6b6412c-f51d-11e6-957f-77ce381601e8.png)
![2017-02-17_14 31 21](https://cloud.githubusercontent.com/assets/6277538/23053569/d6b8b9b6-f51d-11e6-8cce-325dc437df50.png)

Using GT 5.09.38 pre3, GT++ 1.4.38alpha.

Both 38alpha and 15release have problem.

Same for GT 5.09.27 :|

That's not a texture pack problem(double checked),

**Comment by draknyte1** [comment]
It is the fault of @Blood-asp

**Comment by Azruine** [comment]
Oh. Got it. Thank :)

**Comment by Dream-Master** [comment]
But it is only a visual thing I guess?

**Comment by Blood-Asp** [comment]
I wonder why this issue was opened in GT++ in the first place... There is nothing of it connected to it afaik so https://github.com/Blood-Asp/GT5-Unofficial/issues would have been the right place. 
I did build all 4 turbines with only GT installed and have no texture issues. Maybe the texturepack you are using is the reason?

**Comment by draknyte1** [comment]
Your texture array indexes overlap mine. That's the issue. 

Please test gregtech with GT++ in the future please to prevent index overlaps and other issues.

**Comment by JohannesGaessler** [comment]
Sorry to say, but this is at least partly on you, @draknyte1.
The casings are separated into units of 16 and you should have made your casing offset a multiple of that, not 57.
It could be reasonably assumed that the GT5U core mod will at some point add new casings and fill up the remaining slots in GT_Block_Casings4, resulting in a collision.

**Comment by draknyte1** [comment]
This is from before your time and will be resolved when I have free time. This wasn't open for discussion.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/dfb374ea275c1bb5e861c5e96fa0688d3b001375.
