### ISSUE TITLE
Tank Recipes need change for GTNH

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#58]
Recipes missing Pump Covers

![image](https://cloud.githubusercontent.com/assets/2970688/23092175/744eaa76-f5c5-11e6-8533-154005d04dcd.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23092177/7bc3c138-f5c5-11e6-903b-6e412541890b.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23092180/880cb06c-f5c5-11e6-9273-08e975b3190e.png)

Tested with GTNH Pack and lastest Gt++ Alpha
https://github.com/GTNewHorizons/NewHorizons

**Comment by draknyte1** [comment]
Are you using your own custom high tier machine components? If so, what are they oredicted as?

**Comment by Dream-Master** [comment]
Yes we does. Have to look at it but I guess at the moment they don't have ordicts. What should I add to be compatible wit Blood asps Gt?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23092401/4e97c056-f5ca-11e6-8aba-314d54eaab96.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23092404/52a4fb00-f5ca-11e6-80de-bec4118b7397.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23092406/562d86fc-f5ca-11e6-99e3-8e9373bdedea.png)

**Comment by Dream-Master** [comment]
We have own Tanks starts from 4000 Buckets. So i guess we will disabled some tanks. maybe not need to write a compatiblity patch for it.

**Comment by Dream-Master** [comment]
Suggestion for GTNH Pack:

ULV Tank : Medium Clay Pipe and TinPlates (32 Buckets)
LV Tank : Large Clay Pipe and Copper Plates (64 Buckets)
MV Tank: Medium Copper Pipe and Iron Plates (128 Buckets)
HV Tank: Large Copper Pipe and Bronze Plates (512 Buckets)
EV Tank: Medium Bronze Pipe and Steel Plates (2048 Buckets)

GTNH Super Tank Tier I = 4000 Buckets

**Comment by draknyte1** [comment]
Tweaked the recipe for the lowest tier to use Clay in https://github.com/draknyte1/GTplusplus/commit/edc9100f55bd30b73cdb4e9b051303c3491843e5.
Also tweaked the recipes to suit you for the other tiers in https://github.com/draknyte1/GTplusplus/commit/2faca0a9becf8837892b9d69edd5c2b1b56c2347.

**Comment by Dream-Master** [comment]
It not show up the right recipes.
Testest with the lastest commits.

**Comment by draknyte1** [comment]
Hmm, maybe it's no detecting your DreamCraft properly.

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/0db2adca9125087935a0cc2ebd46f05c#file-gistfile1-txt
