### ISSUE TITLE
Industrial Coke oven.

### ISSUE THREAD

**Issue by Pilad** [draknyte1/GTplusplus#59]
I  test https://github.com/draknyte1/GTplusplus/releases/tag/v.1.4.9-38-Alpha
Oven not work.

http://imgur.com/a/Ob4c3

**Comment by draknyte1** [comment]
Does it have sulfuric acid or oxygen in its fluid input hatch?

Is the screenshot where there's blocks missing the only one with blocks missing?

**Comment by Pilad** [comment]
No input gateway for the liquid in the description on the controller ))) AndreyKV suggested that she needed oxygen. And the machine stops working, if you do not take coal from the output gateway.

**Comment by Pilad** [comment]
In the picture there is no block, just showed that the emptiness inside.

**Comment by Pilad** [comment]
And blast furnace iron is very slow. About 20 minutes fry 1 bar. It can make the same time as the furnace and bronze? 10 minutes. Or make it into the configuration or add the ability to use tweaker to change through scripts.

**Comment by Pilad** [comment]
Matter condenser is not work - AndreyKV.

**Comment by draknyte1** [comment]
Iron blast furnace says why it's slow in the tooltip, it will not be configurable. 

The recipes for the industrial coke oven in NEI show it needs fluids. I'll update the tooltip to include the fluid input hatch. I'll investigate the output hatch issue, although I have an idea without looking what it might be. 

Matter fabricator works fine for me, I need more information. Consider raising a seperate issue please.

**Comment by draknyte1** [comment]
I appreciate the bug reports guys))
I've had free time this weekend, so I'm trying to fix issues and finish the LFTR.

**Comment by Pilad** [comment]
The furnace is stopped if the gateway 2 carbon. Perhaps the condition is somewhere in the code? You can simply enter the time, to stop the oven if there is a maximum capacity gateway with 16 * 64. If the gateway is 4 * 64 for example, simply to destroy the products. Or keep track of just what the output of the gateway is stopped and the oven if it is full.

**Comment by draknyte1** [comment]
My multiblocks all contain code to stop them if the outputs bus is full.))
By default, Gregtech multiblocks void excess output, which is silly. 

I'll look later tonight when I am home.

**Comment by Pilad** [comment]
Thanks )) I'm sorry for bad english. It is google translate )

**Comment by draknyte1** [comment]
If you want, post original Russian text too. 
I will get one of my Russian friends to give me a better translation))

**Comment by Pilad** [comment]
Cool )))

**Comment by draknyte1** [comment]
Should be fixed now, along with the Matter Fabricator too.
