### ISSUE TITLE
Machine recipe using 32/128/512 eu/t

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#60]
Some machine recipe using 32/128/512....... eu/t.
Better change it to 30/120/480..... eu/t. 

(Because of Cable loss)

**Comment by draknyte1** [comment]
Which recipes exactly?
I add lots..

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/3fd283d8a02a6e9e0888d01407720e80e969d9e5 should change a good lot of them.

**Comment by draknyte1** [comment]
Unless you find anything else, I think this is fixed.
