### ISSUE TITLE
Placeholder ingot shown in some recipes

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#61]
![image](https://cloud.githubusercontent.com/assets/2970688/23283723/e5f99fd0-fa27-11e6-9160-facb2c763499.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23283735/f307a6cc-fa27-11e6-9ab5-4cd3468bcb9d.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23283740/f82bf766-fa27-11e6-9845-e73186968454.png)

guess unfinished stuff.

**Comment by draknyte1** [comment]
I changed material generation, just an unintended side effect of the new system not being fully tested.
