### ISSUE TITLE
Radioactive Dust in the Thaumcraft Arcane Table output slot.

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#62]
If i using newest available source of you mod in my Modpack GTNH i get 100 of this Dust in the Arcane Crafting Table. I can take it out and it refills.
Will test it later with older versions.
![image](https://cloud.githubusercontent.com/assets/2970688/23330163/6b4fab96-fb47-11e6-80e8-c7aae01b3b47.png)

**Comment by draknyte1** [comment]
I have thaumcraft in my dev environment and on my live server, this issue doesn't happen for me.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23334308/35918984-fb9c-11e6-9da5-8999b2ccf129.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23334309/3e597ffe-fb9c-11e6-8370-4fdc45191413.png)
Found another recipe. Maybe this are the source of the bug.

**Comment by Dream-Master** [comment]
get the same amount 100.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23334321/7371d61e-fb9c-11e6-8438-d0497a08b52b.png)

**Comment by draknyte1** [comment]
I don't know where these recipes come from.. But they're not in my dev environment... Sort of hard to investigate.. Roll back a few versions and see if they are still there whenever you can please.

**Comment by Dream-Master** [comment]
ok will try with your lastst alpha and with your stabel version.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23334526/2196ed48-fba1-11e6-8fcb-693e16a79f83.png)
1.4.9.22 works well no wrong recipes.

**Comment by Dream-Master** [comment]
1.4.9.38 testing next

**Comment by draknyte1** [comment]
Resolved in https://github.com/draknyte1/GTplusplus/commit/24242984397425c3d9064940aa8ebe21e176d6e6.
Thanks for the help in debugging this Mate.
