### ISSUE TITLE
Fluid Tanks shows wrong amount in Liter

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#65]
Fluid Tanks shows wrong amount in Liter.

(Tested GTNH Pack)

![image](https://cloud.githubusercontent.com/assets/2970688/23834267/ec5448d8-0753-11e7-83a1-83c0d2ee61e0.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23834288/55bac676-0754-11e7-8a52-c6a5f9f9b30e.png)

show 192000L but holds 1024000L

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/985b9e215a1a97baa19360a0f14dd6c9d7d044bd.
