### ISSUE TITLE
A bunch of pipes require more EU to make then they do to extrude other things

### ISSUE THREAD

**Issue by xarses** [draknyte1/GTplusplus#67]
material| pipe | tool-head 
-|-|-
lead | 160  |128 
dark steel | 160 | 128
tungsten | 640 | 512 
europium | 160 |
clay | 160 |

(I included Clay and Europium because it seems odd that they are randomly 160 when most extruder recipes are 128)

Please verify that these values compute.
P.S. Please verify the processing time for the pipes, as they seem almost 2x more than most tools

**Comment by xarses** [comment]
I also see that the iridium shaft costs and obscene amount,

material | shaft | tool head
-----------|--------|--------------
iridium | 4000 | 128

**Comment by draknyte1** [comment]
Iridium rotor costs are meant to be expensive, As they have Infinite durability. They produce a large magnitude of power as well...
