### ISSUE TITLE
Industrial Centrifuge and Fluid Cells

### ISSUE THREAD

**Issue by iFozar** [draknyte1/GTplusplus#68]
1) The industrial centrifuge produces x6 more liquids than it should. So we can get 432 mB of methane from a pumpkin or 24 mB of tritium from 16 mB of deuterium.

2) The cost of the Fluid Cells is 2.5 (1x double plate, 2x rings) ingots of material (Invar, Bronze, etc.). But we can put the cell in the Fluid Extractor and get 1296mB of this material. This is 9 ingots.
![2017-03-14_09 51 51](https://cloud.githubusercontent.com/assets/26382920/23884201/f5050ab2-089d-11e7-9f1b-1bc5912a954e.png)
![2017-03-14_09 51 55](https://cloud.githubusercontent.com/assets/26382920/23884202/f543868e-089d-11e7-9b2c-badad83a78c3.png)

**Comment by draknyte1** [comment]
I'll look into the industrial centrifuge. 

Fluid extractor bug is a gregtech issue. I don't add that recipe, it's automatically generated. Report it to @Blood-asp.

**Comment by iFozar** [comment]
![2017-03-14_10 10 17](https://cloud.githubusercontent.com/assets/26382920/23884450/4d554708-089f-11e7-9dde-6d9b0241ef16.png)
![2017-03-14_10 10 36](https://cloud.githubusercontent.com/assets/26382920/23884451/4d5c3ca2-089f-11e7-957e-97c88395a883.png)
A couple of screenshots.

Ok, i will write about it to BloodAsp
