### ISSUE TITLE
Mutegenic frames losing inheretence

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#71]
Product bees resulting from the use of mutagenic frames all seem to be Pristine with no generations in captivity and do not inherit any bred traits (tolerances etc) from their parents. It is as though they have been plucked directly from NEI. I think this is not the intended behavior.

**Comment by draknyte1** [comment]
This may related to the fact that the mutation rate is 10x'd
May be an issue in forestry.
@Mezz, any input?

**Comment by mezz** [comment]
I'm not sure, I haven't seen anything like that with regular Forestry hives.
The only "protection" the bees have is against over-production, they can become ignoble.
There is no special handling of high mutation rates.

**Comment by draknyte1** [comment]
Would it be possible that such high mutation rates guarantee pure drones?
Seems odd, but nobody probably ever tried with such high multiplier frames.

@katecw Are you only using a single frame?

**Comment by leagris** [comment]
Mutation chance affect number of transferred chromosomes/traits.
If chance is high enough, all traits are transferred, giving you a pure breed.

**Comment by draknyte1** [comment]
Things you know @leagris.
