### ISSUE TITLE
High Current Industrial Arc furnace does not form

### ISSUE THREAD

**Issue by chochem** [draknyte1/GTplusplus#712]
## Expected Behavior
 I have: 1 controller (top center), 1 energy hatch, 1 muffler hatch (top corner, pointing up), 10 input buses, 1 output bus, 1 maintenance hatch, 1 input hatch, 10 Tempered Arc Furnace Casings. In a hollow 3x3x3. 

## Current Behavior
It does not form.

## Possible Solution
I fixed it by putting all 10 Tempered Arc Furnace Casings in the lower two layers. I got this idea from looking at this code https://github.com/alkcorp/GTplusplus/blob/fcaa16446a044593bf409a2c98631a76fbfc6120/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialArcFurnace.java, which might be horribly outdated, but only does a mPlascreteCount++ for the lower layers, not the top layer. I guess access to code is super useful for testing. ;)

Edit: Does not hold up to further testing, see below.

## Context
This could possibly also fix https://github.com/alkcorp/GTplusplus/issues/572 which was closed but never resolved from what I can see.

## Game Environment
SP, GTNH 2.0.9.0 RC1 but with the slightly newer GT-PlusPlus-1.7.05.68

**Comment by botn365** [comment]
on the midle layer the 4 wall casings that are on the same y or x axes if you replec them witch a hatch does it unform?

**Comment by chochem** [comment]
It does, hmm. My analysis from a short glance at the code was wrong then, I might just have fixed mine by accident. Do you already know what the issue is?

**Comment by botn365** [comment]
prety sure i know now

**Comment by chochem** [comment]
it looks like the bad spot that absolutely needs a casing is at X=controller+1, Y=controller-1 for me

**Comment by Dream-Master** [comment]
@botn365 version 68 is the newest so if it not fixed in the last 24h its still there.

**Comment by botn365** [comment]
i fixed it 7 minutes ago so when this fix gets put in a build is all on alk

**Comment by Dream-Master** [comment]
ok
