### ISSUE TITLE
Dissasembling of energy buffers

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#72]
Energy buffers are very expensive especially in terms of precious ruby dust, though rightly so given their awesomeness. However, this does mean one is encouraged to delay making them as long as possible since you cannot recover those resources which is a shame.

EnderIO, for example, gets around this issue with their capacitor banks by allowing you to use them in the crafting of the next tier.

I propose the addition of dissasembler recipies which allow you to recover the energy cores from energy buffers which could then be used in making the next tier up as you progress through the GT power tiers.

**Comment by draknyte1** [comment]
Valid suggestion, I'll add it in.
Energy Cores and Hull material should be recoverable, possibly via arc furnace (Them cores are tough little things)

**Comment by draknyte1** [comment]
If crafted int a crafting grid, you should be able to disassemble them.
