### ISSUE TITLE
Cutting factory -> Carpeter Block

### ISSUE THREAD

**Issue by Ngar1** [draknyte1/GTplusplus#729]
# Issue Title  
Cutting factory -> Carpeter Block

see also here:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6377#issue-655365191

Which modpack version are you using?
2.0.9. GTNH, myFTB.de

If in multiplayer; On which server does this happen?
Please extend cutting receips from single block cutting mashine to factory cutting machine, like carpeters block to wedge slope and so on.

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ x]    Multi Player?

**Comment by draknyte1** [comment]
They use the exact same recipe map. 
Literally not my issue nor can I fix it.
