### ISSUE TITLE
Industrial coke oven recipies too mean

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#73]
The industrial coke oven recipes for charcoal and coke are far too mean, to the extent that they can represent a net energy deficit.

Comparing both at optimum efficiency (using nitrogen/sulfuric acid), the pyrolyse oven gives you 1 charcoal every 0.8 seconds for 1,536 EU and 1 coke/second for 1,920 EU/coke.

The industrial coke oven, which is a higher technology tier and therefore one would expect would be better, currently produces 1 charcoal every 20 seconds for 12,000 EU and 1 coke every 15 seconds for 36,000 EU/coke. Ie. an order of magnitude both slower and more energy intensive.

First, I suggest that the pyrolyse oven's ratio of 25% more energy and time for coke than charcoal is about right. Logs->charcoal is a burntime improvement of 1,200 whereas coal->coke is 1,600. Less time and 3x the energy for coke (vs. charcoal) in the coke oven does not make sense.

Second, the coke oven should definitely faster and at least comparably efficient, not an order of magnitude more expensive and slower. 1 charcoal is worth 14,400 EU using LV turbines and a large steel boiler so there is room for slightly less efficiency in exchange for more speed (the GT way). When considering charcoal that needs to be reduced by 25% to account for the fact that you could just burn the logs, ie. it is the boost in burn time we're interested in, so 10,800 EU.

First, I suggest making the industrial coke oven process 20 logs or 16 coal in one operation like the pyrolyse oven. The sulfuric acid consumed and creosite produced should also be increased proportionally. That will keep the time/energy ratios the same as for the pyrolyse.

Second, I suggest making the energy required per operation (with sulfuric) be reduced to 46,080 EU/operation - 1.5x the energy of the pyrolyse oven.*

Third, I suggest making the time per operation (again with sulfuric) 8 seconds, or twice as fast as the pyrolyse oven. Given the additional cost of the oven itself and the additional overhead of manufacturing large quantities of sulfuric acid that rate of production is warranted.

For oxygen recipies I suggest the 38,400 EU/operation, or 1.25x the pyrolyse oven with nitrogen*, and 12 seconds per operation. This would make O2 slower but also more efficient than H2SO4, which is not the same as with the pyrolyse where no gas is less efficient and slower than with nitrogen. O2 is of similar difficulty to obtain to N2, so it makes sense to me that it should be comparable to the pyrolyse on N2. The O2 consumption should be adjusted to make it the same as the pyrolyse in terms of L/(char)coal IMHO.

The above changes would make a fairly neat, though linear, progression in efficiency and speed from N2 to O2 to H2SO4.

* At 2x the energy cost of a pyrolyse oven (3,072/charcoal) you would using 30% of the overall energy gained making it a not very efficient process, and higher tier power systems tend to be less efficient than the numbers outlined above (better boilers but worse turbines). Hence I suggest 1.5x (2,304 EU/charcoal) being the maximum and 2x be used as an absolute maximum should you want to make them more expensive than what I've proposed, especially as there are secondary costs in producing the O2/H2SO4.

**Comment by draknyte1** [comment]
It's not meant to be the same as the Pyrolyse though.
As mine existed first, there was no basis to compare against, nor did I ever really go into the maths too much. 

That said, coming back to it to rebuff, along with your maths seems like a rather viable suggestion. Although, always take note that this mod still works with all versions of GT5, including .07 and .08 branches. In which there is no Pyrolyse at all.

**Comment by draknyte1** [comment]
I redid all the Coke Oven recipes for 1.5.6.
We will have to update so you can advise me what you think.
