### ISSUE TITLE
Big Reactors materials and fluids

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#74]
Since GT++ already adds in gelid cryothermium (and puts it to use with cinnabar) without Thermal Expansion, which is very useful for packs like Beyond Reality that use Ender IO instead but do have Big Reactors, it might be worth considering having GT++ add back other materials and fluids useful for Big Reactors like resonant ender and enderium.

**Comment by draknyte1** [comment]
Enderium was never initially added because Gregtech already added it.
This will require a simple api branch check with a try/catch to try add it, since it's rather impossible to differentiate between .09.01 and .09.27, for example.

Not really sure why I missed resonant ender though.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/a908643b6a97bf8097ce03cec4648d2ca9fdd095 re-adds Resonant Ender.

Enderium I will do differently, but expect it in the next day or two.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/daa2a6051920dc8ba91ee832b739aff285cb332f re-adds Enderium by default into GT.
