### ISSUE TITLE
same oreDictionary tag "kobolditeDust" [GTNH-2.0.9.0qf4]

### ISSUE THREAD

**Issue by MotiasNotMe** [draknyte1/GTplusplus#744]
## Current Behavior
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6595
Koboldite dust (Witchery) and Koboldite dust (gt++) having a same oreDict because of this Ender Quarry in Everglades mining Koboldite dust(WT), but not (GT++)

## Possible Solution
Add witchery Koboldite dust to GT_OreDictUnificator.addToBlacklist?

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1.
 2.

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  
 * Version used:
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
They are the same thing. 
Not a bug.

**Comment by MotiasNotMe** [comment]
Koboldite is not a real ore, and may be traded to ingots, nuggets only by the Hobgoblins
Adding it to Everglades at least strange
https://sites.google.com/site/witcherymod/koboldite-dust
Koboldite dust can be obtained by killing some mobs and mining by Hobgoblins
