### ISSUE TITLE
Radon is a Gas

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#81]
I suggest to remove all plates, ingots etc from Radon because it is a Gas.

![image](https://cloud.githubusercontent.com/assets/2970688/26752736/435e78c6-4857-11e7-8ade-d08a677390e2.png)

**Comment by draknyte1** [comment]
Ugh, I thought that I did.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/84f44b23393ee7f565de4eac5ffeaa235c356882.
