### ISSUE TITLE
Tell Alkalus Ingot error

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#85]
A few recipes using this error Ingot.

![image](https://cloud.githubusercontent.com/assets/2970688/26753511/6c8c5496-4868-11e7-81fe-94aa3755c9e1.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26753513/71ea8f0c-4868-11e7-8093-4cab3f2b6f57.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26753514/77a5f012-4868-11e7-8dd5-fc208c8f00f6.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26753516/805609c2-4868-11e7-88d3-763c25eaf95c.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26753518/846763f8-4868-11e7-9a04-ec567bd333a5.png)

**Comment by draknyte1** [comment]
Must be specifically related to GTNH, as my latest dev version has a single recipe which asks for them. Huge Europium pipes. I'll have a look when I find time.
