### ISSUE TITLE
MV potin is used for ULV components

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#86]
potin is used for ULV components but can be made first in mv (mixer 90 eu/t) or did i missing some low tier recipe?

**Comment by bear989** [comment]
good luck with that, been there, done that!

**Comment by Dream-Master** [comment]
What you mean @bear989 are you have the same problem?

**Comment by bear989** [comment]
I went over the issue with some of these materials not being craftable at there tier with @draknyte1 already. they where HV if memory serves originally.

**Comment by bear989** [comment]
potin dust can be hand crafted now, I just logged in and looked it up.

**Comment by Dream-Master** [comment]
but the recipes not shown so far i know. Never test to craft it by hand

**Comment by bear989** [comment]
I shows in mine what version are you using?

**Comment by Dream-Master** [comment]
@bear989 i compiled the lastest aviable source on Github.

**Comment by bear989** [comment]
well I cant help ya there, I have an issue where that new eglin steel recipes are missing for me but others they arent so maybe it is the same kinda issue?

**Comment by draknyte1** [comment]
The use of Potin is intended.
@bear989 check it's not a minetweaker script. 
Not sure I ever fixed the manual crafting recipes.

**Comment by Dream-Master** [comment]
@draknyte1 Are there a manual crafting recipe i did not see?

**Comment by draknyte1** [comment]
I do not think so.
Don't think that ever got fixed, although all 'alloys' that are MV or less should have one.

**Comment by Dream-Master** [comment]
ok will test it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26805618/05770a3a-4a4d-11e7-9e37-08f8f6ca88f2.png)
no but i can add a recipe Shaped/Shapeless in my core mod.

**Comment by bear989** [comment]
yah I forgot we got tired of waiting and made our own recipes,

**Comment by draknyte1** [comment]
I'll just try fix it later.
Everything else I need to fix is relatively small.
