### ISSUE TITLE
conveyors not working on tanks (single block) 

### ISSUE THREAD

**Issue by bear989** [draknyte1/GTplusplus#87]
I hooked a pipe to a ULV tank and placed and conveyor module on the pipe setting it to import and it would not pull empty cells from it. a hopper will work under the tank though.

**Comment by Technus** [comment]
Aren't conveyors for items?

**Comment by draknyte1** [comment]
The internal inventory of tanks and the functionality of the conveyors aren't touched by me, they're straight Gregtech code. So, it's not really my issue here.

**Comment by xarses** [comment]
I'll speak with bear, this works for me
