### ISSUE TITLE
Circuits(IV,LuV,ZPM,UV)

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#88]
Need a complete rewrite because Blood Asp added a tones of new Circuits.

**Comment by draknyte1** [comment]
Considering I support versions back .07, changing the circuits out is more of an option that should be disableable.

**Comment by Dream-Master** [comment]
sure

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/40624443a89abe0bbb8fac18defe4e2066ee835a.
