### ISSUE TITLE
Tinkers Aluminum and Cobalt Dust

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#89]
There are recipes with Tinkers alu/cobalt dust not gt

![image](https://cloud.githubusercontent.com/assets/2970688/26755349/8153ed44-488b-11e7-9f2d-d494e8aef74b.png)

![image](https://cloud.githubusercontent.com/assets/2970688/26755355/a4a6e9fe-488b-11e7-8130-a106ac9599fb.png)

![image](https://cloud.githubusercontent.com/assets/2970688/26755363/b2489abc-488b-11e7-8c38-226477f4954a.png)

**Comment by draknyte1** [comment]
I thought I fixed the Blast Smelter using non-gt dusts ages ago?

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/3839047cb7b620fb98712b32a06fb4680382e0a1.
