### ISSUE TITLE
Disabling the Iron Blast furnace crash

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/GTplusplus#90]
Disabling the Iron Blast furnace in the config i get a crash

https://gist.github.com/Dream-Master/f96d4fea7fce1d155b5e9948e177e7a6

enabling it all works fine.

**Comment by draknyte1** [comment]
It's just crashing due to it adding a recipe for a null entry in the ItemList.
Like a few other things, just requires a simple if check.
