### ISSUE TITLE
eglin has no recipe

### ISSUE THREAD

**Issue by bear989** [draknyte1/GTplusplus#94]
![2017-06-11_20 52 25](https://user-images.githubusercontent.com/8433695/27015927-b13af504-4ee7-11e7-9446-5a273bee3dc2.png)

**Comment by Rongmario** [comment]
Eglin Steel does have a recipe, mixing the dusts to form the alloy, blast furnace -> cooling

![2017-07-05_15 30 05](https://user-images.githubusercontent.com/3684700/27853879-1e3958c8-6197-11e7-8581-9aece8e67f02.png)

**Comment by bear989** [comment]
for some it does, for some it doesnt

**Comment by Rongmario** [comment]
It is indeed.

Hope it is that issue!

**Comment by bear989** [comment]
nope it isnt NEI, it just doesnt work
![2017-07-05_14 16 54](https://user-images.githubusercontent.com/8433695/27878447-4a11cecc-618c-11e7-9e7a-d668e17bb320.png)
that is, in clockwise order, 20 steel, 1 silicon, 4 aluminium, 5 nickel

**Comment by Rongmario** [comment]
Hmm I might compare mod lists.

**Comment by draknyte1** [comment]
I have found that I do not have Eglin on my work laptop instance.
Will debug this properly today. (My modlist here is minimal as fuck)

**Comment by bear989** [comment]
yah ours as well

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/ec9105c1d4a5107ebe2a3772c8b91bd9ca43d5a6.
