### ISSUE TITLE
Tantalum-60 eats moulds in solidifier

### ISSUE THREAD

**Issue by katecw** [draknyte1/GTplusplus#97]
If you put liquid Tantalum-60 into an advanced solidifier (probably all, only tried it with that one) and a plate mould (quite possibly others) the mold destroyed with the creation of the first plate.

**Comment by draknyte1** [comment]
I don't see how.. >_<
```
GT_Values.RA.addFluidSolidifierRecipe(
					ItemList.Shape_Mold_Plate.get(0), //Item Shape
					material.getFluid(144), //Fluid Input
					material.getPlate(1), //output
					32, //Duration
					8 //Eu Tick
					);
```

**Comment by draknyte1** [comment]
![2017-07-03_22 41 19](https://user-images.githubusercontent.com/3060479/27793291-c6b648a6-6040-11e7-9656-d8d52d7493e9.png)
Doesn't seem to exist as an issue anymore. Was fairly sure this was fixed ages ago.
